- .travis.yml
This allows Travis CI to use its new container-based infrastructure,
which should speed up the builds.
> [TASK] Set sudo: false in .travis.yml

- Sniffs/PHP/NewKeywordsSniff.php
This implements the missing keywords, as described in #45 .
> Add some missing keywords to NewKeywords.php

- Sniffs/PHP/DeprecatedFunctionsSniff.php
Added OCI8 deprecated functions.
http://php.net/manual/en/oldaliases.oci8.php
> OCI8 deprecated functions

- composer.json
Implemented composer autoload changes as described in #76 and #67.
> Add autoload to composer.json

- Sniff.php
A few bits of simplification/tidying of Sniff.php, to aid future enhancements.
No behavioural change, just code improvements.
See individual commits for details.
> Tidy version check code

- Sniffs/PHP/ShortArraySniff.php
- Tests/Sniffs/PHP/ShortArraySniffTest.php
- Tests/sniff-examples/short_array.php
> Add short array syntax sniffer

- Sniffs/PHP/ForbiddenNamesSniff.php
- Tests/Sniffs/PHP/ForbiddenNamesSniffTest.php
- Tests/bootstrap.php
Fixes wimg/PHPCompatibility#124
> Fixes wimg/PHPCompatibility#124

- Tests/BaseSniffTest.php
For two sets of two functions, abstracted the duplicate code out to a new method and replaced it with a function call to that new method.
> Minor refactoring to remove code duplication in the `BaseSniffTest` class

- Sniffs/PHP/RemovedExtensionsSniff.php
- Tests/Sniffs/PHP/RemovedExtensionsSniffTest.php
Includes adjusted unit tests.
Ref: http://php.net/manual/en/migration51.extensions.php
> Correct the removal version nr for a few removed extensions.

- Sniffs/PHP/DeprecatedFunctionsSniff.php
- Tests/Sniffs/PHP/DeprecatedFunctionsSniffTest.php
- Tests/sniff-examples/deprecated_functions.php
> Add two more deprecated function(s).

- .coveralls.yml
- .travis.yml
- phpunit-travis.xml
> Redid all fixes for code coverage

- Tests/bootstrap.php
> Fix stupid mistake I made.

- Sniffs/PHP/NewFunctionArrayDereferencingSniff.php
- Tests/Sniffs/PHP/NewFunctionArrayDereferencingSniffTest.php
- Tests/sniff-examples/new_function_array_dereferencing.php
> Fix logic error in `NewFunctionArrayDereferencing` sniff.

- README.md
I hope you don't mind, I think this looks a little cleaner. 
You can preview it here: 
https://github.com/octalmage/PHPCompatibility/tree/readme-updates#thank-you
Thanks!
> Move WP Engine logo.

- Sniff.php
- Sniffs/PHP/DeprecatedFunctionsSniff.php
- Sniffs/PHP/DeprecatedIniDirectivesSniff.php
- Sniffs/PHP/DeprecatedPHP4StyleConstructorsSniff.php
- Sniffs/PHP/ForbiddenGlobalVariableVariableSniff.php
- Sniffs/PHP/ForbiddenNamesSniff.php
- Sniffs/PHP/ForbiddenNegativeBitshiftSniff.php
- Sniffs/PHP/NewInterfacesSniff.php
- Sniffs/PHP/NewKeywordsSniff.php
- Sniffs/PHP/NewScalarTypeDeclarationsSniff.php
- Sniffs/PHP/RemovedFunctionParametersSniff.php
- Sniffs/PHP/RequiredOptionalFunctionParametersSniff.php
- Sniffs/PHP/ValidIntegersSniff.php
- Tests/BaseClass/DoesFunctionCallHaveParametersTest.php
- Tests/BaseClass/GetFQClassNameFromDoubleColonTokenTest.php
- Tests/BaseClass/GetFQClassNameFromNewTokenTest.php
- Tests/BaseClass/GetFQExtendedClassNameTest.php
- Tests/BaseClass/MethodTestFrame.php
- Tests/BaseClass/TestHelperPHPCompatibility.php
- Tests/BaseSniffTest.php
- Tests/Sniffs/PHP/ConstantArraysUsingDefineSniffTest.php
- Tests/Sniffs/PHP/ForbiddenGlobalVariableVariableSniffTest.php
- Tests/Sniffs/PHP/RequiredOptionalFunctionParameterSniffTest.php
- Tests/Sniffs/PHP/ValidIntegersSniffTest.php
- Tests/bootstrap.php
Some spelling, grammar, spacing and documentation fixes. Also some minor strict checking improvements and removing of some unused variables.
Fixes most issues which are unrelated to duplicated code currently being flagged in Scrutinizer and some which aren't flagged ;-)
> Various minor fixes.

- Sniffs/PHP/ForbiddenNamesAsInvokedFunctionsSniff.php
- Tests/Sniffs/PHP/ForbiddenNamesAsInvokedFunctionsSniffTest.php
- Tests/sniff-examples/forbidden_names_function_invocation.php
> Remove clone from the `ForbiddenNamesAsInvokedFunctions` sniff

- Tests/BaseClass/GetFQClassNameFromNewTokenTest.php
- Tests/sniff-examples/utility-functions/get_fqclassname_from_new_token.php
And fix one wrong token nr in the same unit test file.
> Add unit test for issue #338 / infinite loop / out of memory.

- Sniff.php
Bug never came into play as far as I can tell, but should be fixed anyhow.
> determineNamespace() function: Bug fix

- Sniffs/PHP/NewFunctionParametersSniff.php
- Tests/Sniffs/PHP/NewFunctionParametersSniffTest.php
- Tests/sniff-examples/new_function_parameter.php
Ref: http://php.net/manual/en/doc.changelog.php
> PHP 7.0.15/7.1.1: Add new function param for `get_defined_functions()`

- Sniff.php
* Defer to upstream `getCondition()`  method.
* Prevent unnecessary extra token walking when in a scoped namespace.
* Minor efficiency improvement by using `isset()` instead of `in_array()`.
* Minor code style improvements.
> Minor improvements to the namespace utility methods.

- Sniffs/PHP/NonStaticMagicMethodsSniff.php
- Tests/Sniffs/PHP/NonStaticMagicMethodsSniffTest.php
- Tests/sniff-examples/nonstatic_magic_methods.php
> Add support for anonymous classes to NonStaticMagicMethodsSniff

- Sniffs/PHP/NewClassesSniff.php
- Tests/Sniffs/PHP/NewClassesSniffTest.php
- Tests/sniff-examples/new_classes.php
> NewClasses: add one new class which was missing.

- .travis.yml
- Tests/BaseClass/FunctionsTest.php
- Tests/BaseClass/MethodTestFrame.php
- Tests/BaseSniffTest.php
- Tests/PHPUnit6Compat.php
- Tests/TestcaseWrapper.php
- Tests/TestcaseWrapper_v6.php
- Tests/bootstrap.php
- phpcs.xml
With thanks to @GaryJones for reminding me of the `class_alias` function :heart_eyes_cat:
> Minor simplification of the PHPUnit 6 compatibility layer

- Tests/Sniffs/PHP/DeprecatedFunctionsSniffTest.php
- Tests/Sniffs/PHP/DeprecatedIniDirectivesSniffTest.php
- Tests/Sniffs/PHP/NewClassesSniffTest.php
- Tests/Sniffs/PHP/NewFunctionParametersSniffTest.php
- Tests/Sniffs/PHP/NewFunctionsSniffTest.php
- Tests/Sniffs/PHP/NewIniDirectivesSniffTest.php
- Tests/Sniffs/PHP/RemovedExtensionsSniffTest.php
- Tests/Sniffs/PHP/RemovedFunctionParametersSniffTest.php
Some code which I still had lying around after the big tests refactor, but which didn't fit into that PR.
> Test: minor code simplification when toggling testVersion

- .travis.yml
- ruleset.xml
And check for consistent XML code style.
> :green_heart: Validate the ruleset XML file during the build

- CHANGELOG.md
:warning: **NOT FOR MERGE (yet)** :warning: 
Work in progress branch / Changelog for the 7.1.4 release.
Containing all changes merged into `master` up to the moment that I'm creating this PR.
> Changelog for version 7.1.4

- CHANGELOG.md
:sunglasses: (you may want to remove & retag after merging this...)
> Fix release date of latest release & remove unused section in changelog

- Sniffs/PHP/ForbiddenGlobalVariableVariableSniff.php
- Tests/Sniffs/PHP/ForbiddenGlobalVariableVariableSniffTest.php
- Tests/sniff-examples/forbidden_global_variable_variable.php
> ForbiddenGlobalVariableVariable: recognize these even when there is a closing tag instead of a semi-colon.

- README.md
Also: recommend PHP 5.4 or higher instead of 5.3.
> Readme: Minor tweaks to the text in the "Using" section

- CHANGELOG.md
~~**NOT FOR MERGE (yet)**~~
~~Work in progress branch /~~ Changelog for the 7.1.5 release.
> Changelog for version 7.1.5

- README.md
Adding information about the report in the readme. I was not aware that it will produce no report file at start, so I prefer to add information in the readme ;)
> adding reporting usage

- PHPCompatibility/Sniffs/PHP/NewFunctionsSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/NewFunctionsSniffTest.php
- PHPCompatibility/Tests/sniff-examples/new_functions.php
Ref: http://php.net/manual/en/function.pg-lo-truncate.php
> NewFunctions: add PHP 5.6 `pg_lo_truncate()`

- composer.json
No actual changes, just re-ordering the sections for improved human readability.
Order based on the order suggested in the Composer documentation: https://getcomposer.org/doc/04-schema.md
> Composer: reorganize file

- .travis.yml
- PHPCompatibility/Tests/Sniffs/PHP/NewKeywordsSniffTest.php
> Travis: stop testing on HHVM

- framework-rulesets/joomla.xml
Following #615 this PR adds a ruleset for Joomla.
> Add base ruleset for Joomla

- PHPCompatibility/Sniffs/PHP/ForbiddenEmptyListAssignmentSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/ForbiddenEmptyListAssignmentSniffTest.php
- PHPCompatibility/Tests/sniff-examples/forbidden_empty_list_assignment.php
> ForbiddenEmptyListAssignment: Report on empty lists using short list syntax

- PHPCompatibility/Sniff.php
Found via Scrutinizer.
[ci skip]
> Remove unused line of code

- PHPCompatibility/AbstractComplexVersionSniff.php
- PHPCompatibility/Sniff.php
- PHPCompatibility/Sniffs/PHP/DeprecatedTypeCastsSniff.php
- PHPCompatibility/Sniffs/PHP/ForbiddenCallTimePassByReferenceSniff.php
- PHPCompatibility/Sniffs/PHP/NewFunctionParametersSniff.php
- PHPCompatibility/Sniffs/PHP/NewIniDirectivesSniff.php
- PHPCompatibility/Sniffs/PHP/NewKeywordsSniff.php
- PHPCompatibility/Sniffs/PHP/NewLanguageConstructsSniff.php
- PHPCompatibility/Sniffs/PHP/NewMagicMethodsSniff.php
- PHPCompatibility/Sniffs/PHP/NewTypeCastsSniff.php
- PHPCompatibility/Sniffs/PHP/RemovedFunctionParametersSniff.php
- PHPCompatibility/Sniffs/PHP/RemovedGlobalVariablesSniff.php
- PHPCompatibility/Tests/BaseClass/IsNumberTest.php
- PHPCompatibility/Tests/BaseClass/TestHelperPHPCompatibility.php
- PHPCompatibility/Tests/BaseSniffTest.php
- PHPCompatibility/Tests/Sniffs/PHP/NewFunctionParametersSniffTest.php
- PHPCompatibility/Tests/sniff-examples/utility-functions/is_number.php
No functional changes, just spelling and grammer fixes.
[ci skip]
> Various minor documentation fixes

- PHPCompatibility/Sniffs/PHP/NewIniDirectivesSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/NewIniDirectivesSniffTest.php
- PHPCompatibility/Tests/sniff-examples/new_ini_directives.php
Refs:
* https://github.com/php/php-src/blob/3b6e1ee4ee05678b5d717cd926a35ffdc1335929/UPGRADING#L459-L465
* https://github.com/php/php-src/commit/2475337bd8a0fad0dac03db3f5e7e9d331d53653
> PHP 7.3: NewIniDirectives: account for new ini directives

- PHPCompatibility/Sniffs/PHP/DeprecatedIniDirectivesSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/DeprecatedIniDirectivesSniffTest.php
- PHPCompatibility/Tests/sniff-examples/deprecated_ini_directives.php
Refs:
* https://github.com/php/php-src/blob/3f53b02a53448ec5e7d2d0733668da92a9463730/UPGRADING#L315
* https://github.com/php/php-src/commit/e512305581bb1bb3e4226e3073b89f2a25214403
> PHP 7.3: DeprecatedIniDirectives: account for removed ini directives

- phpcs.xml.dist
> CS: tidy up ruleset

- PHPCompatibility/Sniffs/PHP/RequiredOptionalFunctionParametersSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/RequiredOptionalFunctionParametersSniffTest.php
- PHPCompatibility/Tests/sniff-examples/required_optional_function_parameters.php
Refs:
* https://github.com/php/php-src/blob/3f53b02a53448ec5e7d2d0733668da92a9463730/UPGRADING#L182-L183
* https://github.com/php/php-src/commit/f7f48643e779111b23b546689b9fbb4e3affe1e7
* https://github.com/php/php-src/blob/3b6e1ee4ee05678b5d717cd926a35ffdc1335929/UPGRADING#L397
* http://php.net/manual/en/doc.changelog.php
* https://github.com/php/php-src/commit/00cd671233e8181746ff2853365fb2362dd178e8
> PHP 7.3: RequiredOptionalFunctionParameters: account for change in array_push/unshift()

- README.md
... for slightly sharper image results.
[ci skip]
> Readme: use svg for Travis badge

- CHANGELOG.md
> Changelog for releasing version 9.1.0

- CHANGELOG.md
Includes adding a missing entry to an old version.
[ci skip]
> Changelog for releasing version 9.1.1

- CHANGELOG.md
Includes ensuring the file is encoded in Unicode for correct display of @edigu's name (hope I got it right!).
Release date set at June 28th (tomorrow).
> Changelog for version 9.2.0

- PHPCompatibility/Sniffs/FunctionDeclarations/NonStaticMagicMethodsSniff.php
- PHPCompatibility/Tests/FunctionDeclarations/NonStaticMagicMethodsUnitTest.1.inc
- PHPCompatibility/Tests/FunctionDeclarations/NonStaticMagicMethodsUnitTest.php
> NonStaticMagicMethods: add properties of more magic methods

- PHPCompatibility/Sniffs/FunctionNameRestrictions/RemovedPHP4StyleConstructorsSniff.php
- PHPCompatibility/Sniffs/MethodUse/NewDirectCallsToCloneSniff.php
> CS/QA: minor touch-up

- PHPCompatibility/Util/Tests/Core/DoesFunctionCallHaveParametersUnitTest.php
- PHPCompatibility/Util/Tests/Core/FunctionsUnitTest.php
- PHPCompatibility/Util/Tests/Core/GetFQClassNameFromDoubleColonTokenUnitTest.php
- PHPCompatibility/Util/Tests/Core/GetFQClassNameFromNewTokenUnitTest.php
- PHPCompatibility/Util/Tests/Core/GetFQExtendedClassNameUnitTest.php
- PHPCompatibility/Util/Tests/Core/GetFunctionParameterCountUnitTest.php
- PHPCompatibility/Util/Tests/Core/GetFunctionParametersUnitTest.php
- PHPCompatibility/Util/Tests/Core/IsClassConstantUnitTest.php
- PHPCompatibility/Util/Tests/Core/IsClassPropertyUnitTest.php
- PHPCompatibility/Util/Tests/Core/IsNumberUnitTest.php
- PHPCompatibility/Util/Tests/Core/IsNumericCalculationUnitTest.php
- PHPCompatibility/Util/Tests/Core/IsShortListUnitTest.php
- PHPCompatibility/Util/Tests/Core/IsUseOfGlobalConstantUnitTest.php
- PHPCompatibility/Util/Tests/Core/TokenScopeUnitTest.php
- PHPCompatibility/Util/Tests/CoreMethodTestFrame.php
- PHPCompatibility/Util/Tests/TestHelperPHPCompatibility.php
... and add `@since` tags to the class docblocks (if they weren't there already).
Related to #734
> Documentation: improve the utility test class descriptions

- PHPCSAliases.php
- bin/generate-forbidden-names-test-files
- phpunit-bootstrap.php
... for non-class based files.
Related to #734
> Documentation: add @since tags to file docblocks

- PHPCompatibility/Sniffs/IniDirectives/RemovedIniDirectivesSniff.php
- PHPCompatibility/Sniffs/Upgrade/LowPHPCSSniff.php
- PHPCompatibility/Sniffs/Upgrade/LowPHPSniff.php
Don't use double quotes when they're not needed.
> CS: minor tweaks

- .gitattributes
... for the purposes of line end detection.
> .gitattributes: treat the test case files same as PHP files
