PHPCompatibility/PHPCompatibility

- Sniffs/PHP/ForbiddenCallTimePassByReferenceSniff.php
- Tests/Sniffs/PHP/ForbiddenCallTimePassByReferenceSniffTest.php
- Tests/sniff-examples/call_time_pass_by_reference.php
This shall fix the problem with false positives when a bitwise and is mistaken for a call time pass-by-reference.
https://github.com/wimg/PHPCompatibility/issues/39
> Fix for issue #39

- Sniff.php
- Sniffs/PHP/DefaultTimezoneRequiredSniff.php
- Sniffs/PHP/DeprecatedFunctionsSniff.php
- Sniffs/PHP/DeprecatedIniDirectivesSniff.php
- Sniffs/PHP/DeprecatedNewReferenceSniff.php
- Sniffs/PHP/ForbiddenBreakContinueVariableArgumentsSniff.php
- Sniffs/PHP/ForbiddenCallTimePassByReferenceSniff.php
- Sniffs/PHP/ForbiddenNamesAsInvokedFunctionsSniff.php
- Sniffs/PHP/ForbiddenNamesSniff.php
- Sniffs/PHP/LongArraysSniff.php
- Sniffs/PHP/NewClassesSniff.php
- Sniffs/PHP/NewFunctionsSniff.php
- Sniffs/PHP/NewIniDirectivesSniff.php
- Sniffs/PHP/NewKeywordsSniff.php
- Sniffs/PHP/NonStaticMagicMethodsSniff.php
- Sniffs/PHP/RemovedExtensionsSniff.php
- Sniffs/PHP/RemovedHashAlgorithmsSniff.php
Previously, each class was repeating the same rather lengthy version check, to decide whether a sniff error should be reported (based on the specified testVersion), which makes the code hard to read, increases the risk of errors when editing (particularly when new sniffs are added) and makes the logic harder to change in the future (e.g. to specify a range of versions that you need your code to support).
I have therefore created a base class, called PHPCompatibility_Sniff, which all the other sniffs in the project now extend.  This implements PHP_CodeSniffer_Sniff, so child classes no longer need to mention this.  It adds two helper methods, easily available to all sniffs:
* supportsAbove($phpVersion) - returns true if the version being tested against is >= $phpVersion or if no …
> Encapsulated a load of duplicated code into a base class, which the individual sniffs extend.

- Sniffs/PHP/ForbiddenNamesAsInvokedFunctionsSniff.php
- Tests/Sniffs/PHP/ForbiddenNamesAsInvokedFunctionsSniffTest.php
The instanceof operator was introduced in PHP 5.0.  Most tests list this correctly, but one test had it incorrectly pegged at 5.4, which I have fixed.
> Fix version number for instanceof keyword

- Sniffs/PHP/PregReplaceEModifierSniff.php
- Tests/Sniffs/PHP/PregReplaceEModifierSniffTest.php
- Tests/sniff-examples/preg_replace_e_modifier.php
Added a new sniff to check for /e modifier in calls to preg_replace(), which is deprecated as of PHP 5.5.
Sniff is only able to detect this when a literal string is used, so won't detect when this is passed as a variable/constant/etc.
Unit tests written, all of which pass.
Fixes #71.
> Added a new sniff to check for /e modifier in calls to preg_replace()

- Sniffs/PHP/PregReplaceEModifierSniff.php
- Tests/Sniffs/PHP/PregReplaceEModifierSniffTest.php
- Tests/sniff-examples/preg_replace_e_modifier.php
This issue arose because CodeSniffer breaks multi-line strings into multiple fragments, therefore in order to treat these as a single string, you need to join the pieces back together.  This commit actually goes one-stage further, and should also support strings built-up by concatenation (though I it may also accept inappropriate syntax in some cases - it has not been rigorously designed).
I have added appropriate test cases - the one reported in issue #83 plus a couple of others that occurred to me, and all tests pass.
This fixes #83.
> Updated to PregReplaceEModifierSniff to handle mult-line regular expressions.

- Tests/sniff-examples/preg_replace_e_modifier.php
Some minor improvements to the unit tests for the PregReplaceEModifierSniff:
* I defined a constant in a random broken way, that isn't actually PHP code, due to a momentary brain-fade.  Have updated it to use define() as intended.
* I've changed the name of the example function to something that might trigger the notice if it were an actual regex string, to make it a more complete test.  We can't do this for the variable (we can't have a variable like $MyVar$e) and the constant is already defined in this manner.
> Tweaks to PregReplaceEModifier unit tests.

- Tests/BaseSniffTest.php
- Tests/Sniffs/PHP/NewKeywordsSniffTest.php
I've added a helper function for unit-testing, called requiresPHPVersion() to the BaseSniffTest class, and updated code to use it.
This function marks the test as skipped if it is running on a version of PHP for which the test will incorrectly fail (e.g. because the tokenizer won't generate the correct tokens).
Previously there were some tests which used a version_compare() to bypass their functionality on unsupported versions, and others where the body of the test was simply commented out (so it wasn't running on any PHP version) and in both cases the result is that these tests incorrectly appear to pass.  I have updated these tests to use the new function instead, so they are now correctly reported as skipped, which gives a more accurate reflection of the passing state of the …
> Updating unit tests so that skipped tests are marked as such

- Sniffs/PHP/NewKeywordsSniff.php
- Sniffs/PHP/NewLanguageConstructsSniff.php
- Tests/Sniffs/PHP/NewConstructsSniffTest.php
- Tests/Sniffs/PHP/NewKeywordsSniffTest.php
- Tests/sniff-examples/new_constructs.php
- Tests/sniff-examples/new_keywords.php
I've moved the check for T_NAMESPACE_SEPARATOR out of NewKeywordsSniff and into NewLanguageConstructsSniff as this is a more appropriate location (now that this separate file exists).
The unit tests were updated accordingly.
> Moving namespace separator checks into NewLanguageConstructsSniff

- README.md
Recommend to run 'composer update --lock' instead of 'composer update'. This will update unmeant dependencies, but leaves any other dependencies at it version.
> Only run composer update --lock to prevent updating other dependencies

- Sniffs/PHP/DeprecatedFunctionsSniff.php
- Sniffs/PHP/NewFunctionsSniff.php
$forbiddenFunctions declared public, if not, the following error happens with PHPCS 2.3.0:
```
PHP Fatal error:  Access level to PHPCompatibility_Sniffs_PHP_DeprecatedFunctionsSniff::$forbiddenFunctions 
must be public (as in class Generic_Sniffs_PHP_ForbiddenFunctionsSniff) in 
/usr/share/pear/PHP/CodeSniffer/Standards/PHPCompatibility/Sniffs/PHP/DeprecatedFunctionsSniff.php on line 358
```
> Modifications to be able to work with PHP_CodeSniffer version 2.3.0 (stable)

- Sniffs/PHP/PregReplaceEModifierSniff.php
- Tests/Sniffs/PHP/PregReplaceEModifierSniffTest.php
- Tests/sniff-examples/preg_replace_e_modifier.php
> prev: https://github.com/wimg/PHPCompatibility/pull/89
False alarm on patterns without border chars or with doubles separators. Add tests for such cases.
> Fix false alarm by PregReplaceEModifierSniff

- README.md
- Sniff.php
This allows a range of PHP versions to be specified via the testVersion config setting (e.g. "5.0-5.4").
This is based off PR #98, so that should be merged first.
> Allow version ranges

- Sniffs/PHP/ForbiddenCallTimePassByReferenceSniff.php
(PHP notice error relating to 'nested_parenthesis' array index).
> Logs periodically show messages like the following while scanning a large tree:
> PHP Notice: Undefined index: nested_parenthesis in
> ~Sniffs/PHP/ForbiddenCallTimePassByReferenceSniff.php on line 114
The issue is relating to the 'nested_parenthesis' property not being set in the token information in some situations.
This may be related to the following CodeSniffer bug: https://pear.php.net/bugs/bug.php?id=9274.  This indicates that there are a few token types do not include this property, but it is not clear whether this is something that was fixed (in which case this is only an issue for old versions) or wontfixed, in which case current versions are likely to still be affected.  It is also possible that that issue is not …
> Fix for issue #42

- Sniffs/PHP/TernaryOperatorsSniff.php
- Tests/Sniffs/PHP/TernaryOperatorsSniffTest.php
- Tests/sniff-examples/ternary_operator.php
Unit tests included.
Fixed #49.
> Sniff for missing middle of ternary operators in PHP < 5.3.

- Sniffs/PHP/TernaryOperatorsSniff.php
- Tests/Sniffs/PHP/TernaryOperatorsSniffTest.php
Use of the 'elvis operator', i.e. omitting the middle portion of a ternary operator expression is allowed in PHP 5.3 and up. The sniff enforcing presence of the middle portion only executed for versions 5.3+.
Eg the following example is wrong, and this pull request fixes this issue:
kguest@radagast $ sudo phpcs --config-set testVersion 5.4
[sudo] password for kguest: 
Config value "testVersion" updated successfully; old value was "5.5"
kguest@radagast $ phpcscompat .
FILE: ...s/testproject/application/controllers/OutputController.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
75 | WARNING | Middle may not be omitted from ternary operators in
| …
> Fix test against use of the 'elvis operator'

- .travis.yml
- Sniffs/PHP/ForbiddenNamesSniff.php
- composer.json
Build on previous PR for PHPCS 2.6.0, adding T_ANON_CLASS to targeted tokens for ForbiddenNamesSniff.
> Support PHP CodeSniffer 2.6.0

- Sniffs/PHP/NewClassesSniff.php
- Tests/Sniffs/PHP/NewClassesSniffTest.php
- Tests/sniff-examples/new_classes.php
For classes where the constructor has no required parameters, the sniff could fail. This PR fixes that.
Includes unit test demonstrating the issue.
> Allow for class instantiation without parenthesis.

- Sniffs/PHP/PregReplaceEModifierSniff.php
- Tests/Sniffs/PHP/PregReplaceEModifierSniffTest.php
- Tests/sniff-examples/preg_replace_e_modifier.php
I found two bugs/oversights in the  `PHPCompatibility_Sniffs_PHP_PregReplaceEModifierSniff`.
First off, there are several bracket delimiters which are valid in PHP.
Up to now, only the `{}` bracket delimiters were accounted for, while the other valid bracket delimiters `()`, `[]` and `<>` were not.
Ref: http://php.net/manual/en/regexp.reference.delimiters.php
Secondly, while this is barely documented, the `preg_filter()` function actually applies the `e` modifier as well and should be checked for it too.
Ref: http://php.net/manual/en/function.preg-filter.php
The PR contains unit tests for both issues.
> Improve PCRE `e` modifier sniff

- Sniffs/PHP/DeprecatedIniDirectivesSniff.php
- Tests/Sniffs/PHP/DeprecatedIniDirectivesSniffTest.php
Currently for the following line: 
```
$sybase = ini_get('magic_quotes_sybase');
```
You get this error: 
```
INI directive 'magic_quotes_sybase' is deprecated from PHP 5.3 and forbidden from PHP 5.4.
```
I agree that ini_set should probably throw an error, but ini_get causes a large number of false positives. In every situation I've seen it was a check for backwards compatibility. 
Resolves #119.
> Don't throw an error for ini_get on deprecated ini configs. 

- .travis.yml
After the travis build was fixed, it now contains duplicates within the matrix making it effectively run the same check twice. This PR fixes that.
> Remove duplication from the travis matrix.

- Sniffs/PHP/RemovedExtensionsSniff.php
- Tests/Sniffs/PHP/RemovedExtensionsSniffTest.php
If an extension was deprecated for a number of version, the message would say for instance _"Extension 'mysql' is **deprecated since PHP 5.5 and deprecated since PHP 5.6** and removed since PHP 7.0 - use mysqli instead."_
This PR removes the duplication of the deprecation notice from the message.
> Fix duplicate deprecated message.

- ruleset.xml
Might just be me, but this looked inconsistent with the real ruleset name, so I checked with the rulesets within PHPCS itself and none of them use the `_CodeSniffer` suffix.
> Correct ruleset name

- README.md
- Sniffs/PHP/RemovedExtensionsSniff.php
- Tests/Sniffs/PHP/RemovedExtensionsSniffTest.php
- Tests/sniff-examples/removed_extensions.php
This PR will allow for whitelisting userland functions which have names which overlap with deprecated extensions through a custom ruleset:
```xml
<rule ref="PHPCompatibility.PHP.RemovedExtensions">
<properties>
<property name="functionWhitelist" type="array" value="mysql_to_rfc3339,mysql_another_function" />
</properties>
</rule>
```
Fixes #123
@octalmage What do think ? Will this work for you ?
> Add ability to whitelist functions from a custom ruleset to the removedExtensions sniff.

- Sniffs/PHP/DeprecatedFunctionsSniff.php
- Sniffs/PHP/DeprecatedNewReferenceSniff.php
- Sniffs/PHP/ForbiddenBreakContinueVariableArgumentsSniff.php
- Sniffs/PHP/ForbiddenCallTimePassByReferenceSniff.php
- Sniffs/PHP/ForbiddenFunctionParametersWithSameNameSniff.php
- Sniffs/PHP/ForbiddenNamesAsInvokedFunctionsSniff.php
- Sniffs/PHP/ForbiddenNamesSniff.php
- Sniffs/PHP/ForbiddenNegativeBitshiftSniff.php
- Sniffs/PHP/ForbiddenSwitchWithMultipleDefaultBlocksSniff.php
- Sniffs/PHP/NewClassesSniff.php
- Sniffs/PHP/NewFunctionParametersSniff.php
- Sniffs/PHP/NewFunctionsSniff.php
- Sniffs/PHP/NewKeywordsSniff.php
- Sniffs/PHP/NewLanguageConstructsSniff.php
- Sniffs/PHP/NewScalarReturnTypeDeclarationsSniff.php
- Sniffs/PHP/NewScalarTypeDeclarationsSniff.php
- Sniffs/PHP/PregReplaceEModifierSniff.php
- Sniffs/PHP/RemovedFunctionParametersSniff.php
- Sniffs/PHP/RemovedHashAlgorithmsSniff.php
As with the readme change in #130, the ability to change public properties from a custom ruleset will become more well-known, it seemed prudent to verify that all `public` properties are properties which should be user-adjustable.
As most were not, I've changed the visibility of most `public` properties to `protected`.
Also a `public $error` property was available in a lot of classes, but was either not used at all or only used by one method in these classes and overruled within that method no matter what a user might have passed via a custom ruleset, so I've removed these properties in favour of a local method variable.
> Review of visibility of all sniff properties and removing of some superfluous ones

- Sniff.php
- Sniffs/PHP/ConstantArraysUsingDefineSniff.php
- Sniffs/PHP/DefaultTimezoneRequiredSniff.php
- Sniffs/PHP/DeprecatedFunctionsSniff.php
- Sniffs/PHP/DeprecatedIniDirectivesSniff.php
- Sniffs/PHP/DeprecatedPHP4StyleConstructorsSniff.php
- Sniffs/PHP/ForbiddenEmptyListAssignmentSniff.php
- Sniffs/PHP/ForbiddenFunctionParametersWithSameNameSniff.php
- Sniffs/PHP/ForbiddenNegativeBitshiftSniff.php
- Sniffs/PHP/ForbiddenSwitchWithMultipleDefaultBlocksSniff.php
- Sniffs/PHP/NewAnonymousClassesSniff.php
- Sniffs/PHP/NewClassesSniff.php
- Sniffs/PHP/NewFunctionArrayDereferencingSniff.php
- Sniffs/PHP/NewFunctionParametersSniff.php
- Sniffs/PHP/NewFunctionsSniff.php
- Sniffs/PHP/NewKeywordsSniff.php
- Sniffs/PHP/NewLanguageConstructsSniff.php
- Sniffs/PHP/NewScalarReturnTypeDeclarationsSniff.php
- Sniffs/PHP/NewScalarTypeDeclarationsSniff.php
- Sniffs/PHP/ParameterShadowSuperGlobalsSniff.php
- Sniffs/PHP/RemovedFunctionParametersSniff.php
- Sniffs/PHP/RemovedGlobalVariablesSniff.php
- Tests/BaseSniffTest.php
On a whim, I've run the codebase through Scrutinizer (without any specific config) and this threw up some interesting findings.
This PR handles most of these (for the sniff files).
Typical issues found & handled in this PR:
* Returning `false` from the `process()` method. This is wrong. If the process method returns something it will be interpreted as an integer stack position to continue checking from, so returning false could lead to race conditions.
* Variables which are set and subsequently never used.
* Strict(er) checking of variables before/when using them
* Function calls within loops
* Minor documentation inconsistencies
* A particular typo
Also:
* Removed trailing spaces
One thing Scrutinizer threw up which is *not* (yet) handled is the following from the `BaseSniffTest.php` …
> Fix a number of apparent bugs and minor clean-up.

- Sniffs/PHP/NewClassesSniff.php
- Tests/Sniffs/PHP/NewClassesSniffTest.php
- Tests/sniff-examples/new_classes.php
The `NewClasses` sniff checks for instantiation of classes `new DateTime;`, but did not check for classes extending other classes, i.e. `class MyOwnDateTime extends DateTime {}`.
This PR fixes that. Includes unit tests.
As `JsonSerializable` is an interface and not a class, this is not tested with the `extends` syntax. In reality, `JsonSerializable` should probably be moved to a `NewInterfaces` sniff.
> Allow for classes which *extend* potentially newly introduced classes.

- Sniff.php
- Sniffs/PHP/InternalInterfacesSniff.php
- Sniffs/PHP/NewInterfacesSniff.php
- Tests/Sniffs/PHP/InternalInterfacesSniffTest.php
- Tests/Sniffs/PHP/NewInterfacesSniffTest.php
- Tests/sniff-examples/internal_interfaces.php
- Tests/sniff-examples/new_interfaces.php
1, Sniff to verify the use of interfaces against the PHP version in which they were introduced.
2. Sniff to verify that interfaces intended for PHP internal use are not being implemented in user land.
Sniff 1 also includes a check for unsupported methods, particularly that `__sleep()` and `__wakeup()` are not defined within a class implementing the `Serializable` interface as they would be ignored.
All checks unit tested.
I've copied over a method which was added to PHPCS for the upcoming 2.7 release. If at some point PHPCompatibility would up the minimum PHPCS version to 2.7+, this method can be removed.
This has also been documented in the method doc block.
> Two new sniffs for Interfaces

- .scrutinizer.yml
This config will make Scrutinizer ignore the example test files.
> Add minimal scrutinizer config.

- Sniffs/PHP/DeprecatedIniDirectivesSniff.php
- Sniffs/PHP/NewIniDirectivesSniff.php
- Tests/Sniffs/PHP/DeprecatedIniDirectivesSniffTest.php
- Tests/Sniffs/PHP/NewIniDirectivesSniffTest.php
- Tests/sniff-examples/deprecated_ini_directives.php
- Tests/sniff-examples/new_ini_directives.php
Example: the directive `detect_unicode` was renamed in PHP 5.4 to `zend.detect_unicode`.
With the code added now, an `alternative` can be added to the ini array and will be added to the message.
* Add a lot of additional ini directives to detect.
* Added alternative name for a number of ini directives.
* Corrected the introduction version for a few.
* Re-ordered the ini directives to be alphabetical per version list.
Ref: http://php.net/manual/en/ini.list.php
----
See the individual commits for more information. I put those in to make reviewing easier and would suggest squashing them when merging.
The list is still not complete, but a lot *more* complete than it was before.
> Lots of additional ini directives & ability to indicate renamed directives

- Sniffs/PHP/NewKeywordsSniff.php
- Tests/Sniffs/PHP/NewKeywordsSniffTest.php
- Tests/sniff-examples/new_keywords.php
Fixes #129.
Also documents the `__halt_compiler()` unit test code.
> Allow for "const" keyword inside class context.

- .travis.yml
- Tests/BaseSniffTest.php
For some reason which I haven't been able to figure out, PHPCS master still throws an error when `quiet` is not defined and running with a test suite.
This small fix, gets rid of the error and will allow the test suite to run against master again.
The only PHPCS version which *will* give an issue is 2.6.2 which is missing part of the commit for the addition of the quiet parameter in PHPCS.
> Fix issue with running unit tests against current PHPCS master.

- Sniffs/PHP/ValidIntegersSniff.php
- Tests/Sniffs/PHP/ValidIntegersSniffTest.php
- Tests/sniff-examples/valid_integers.php
Checks for:
* binary integers which were introduced in PHP 5.4
* invalid binary integers
* invalid octal integers which were truncated prior to PHP 7 (warning) and give a parse error in 7 (error).
* hexadecimal numeric strings for which the type juggling behaviour and recognition as numeric was inconsistent prior to PHP 7 (warning) and are no longer treated as numeric in PHP 7+(error).
Closes #55
> Add new sniff for various integer types.

- Sniff.php
- Sniffs/PHP/NewFunctionParametersSniff.php
- Sniffs/PHP/RemovedFunctionParametersSniff.php
- Tests/BaseAbstractClassMethodTest.php
- Tests/DoesFunctionCallHaveParametersTest.php
- Tests/GetFunctionParameterCountTest.php
- Tests/Sniffs/PHP/NewFunctionParameterSniffTest.php
- Tests/Sniffs/PHP/RemovedFunctionParameterSniffTest.php
- Tests/TestHelperPHPCompatibility.php
- Tests/bootstrap.php
- Tests/sniff-examples/new_function_parameter.php
- Tests/sniff-examples/removed_function_parameter.php
- Tests/sniff-examples/utility-functions/count_function_parameters.php
- Tests/sniff-examples/utility-functions/does_function_call_have_parameters.php
Abstract out two new methods: `doesFunctionCallHaveParameters()` and `getFunctionCallParameterCount()` to be used with the `NewFunctionParameters` and `RemovedFunctionParameters` parameter sniffs.
Fixes #120, #151, #152.
Builds onto the solutions for #111 and #114.
~~Additional unit tests for these changes are contained in another branch which is waiting for #149.~~ <= unit tests have been added to the branch.
----
[Edit]: This PR also makes the error notice line number slightly more informative. This was the next comma/closing brace line number - which could be on a completely different line as the parameter -, now it is the line number for the function call - which still might not be on the same line as the parameter, but will make finding the parameter easier.
> Get correct function call parameter count.

- Sniff.php
- Sniffs/PHP/NewClassesSniff.php
- Tests/GetFQClassNameFromDoubleColonToken.php
- Tests/GetFQClassNameFromNewTokenTest.php
- Tests/GetFQExtendedClassNameTest.php
- Tests/Sniffs/PHP/NewClassesSniffTest.php
- Tests/sniff-examples/new_classes.php
- Tests/sniff-examples/utility-functions/get_fqclassname_from_double_colon_token.php
- Tests/sniff-examples/utility-functions/get_fqclassname_from_new_token.php
- Tests/sniff-examples/utility-functions/get_fqextended_classname.php
* Remove the `JsonSerializable` item from the `NewClassesSniff` as it's an interface and now covered by the `NewInterfacesSniff`.
* Add recognition for static use of a class - includes unit tests.
* Add recognition of namespaced classes - as class names always resolve to the current namespace, we should check for the namespace and only flag non-namespaced classes.
Ref: http://php.net/manual/en/language.namespaces.fallback.php
* Abstract out and add a number of utility methods which can be reused in the `RemovedClassesSniff` #154, and for the namespace related methods, reused for functions and more.
* Add some `NoViolation` cases to the unit tests.
* Add unit tests for the new utility methods.
> Improve the `NewClassesSniff`.

- Tests/bootstrap.php
Some silly people (=me) still use the PHPCS PEAR install and just have a local fork of PHPCompatibility in the PHPCS PEAR `Standards` directory.
In that case, running the unit tests locally fails miserably while it doesn't *have* to fail as the path is predictable.
This PR solves that.
> Allow for unit tests to be run when using PEAR installed PHPCS.

- Sniffs/PHP/RemovedFunctionParametersSniff.php
- Tests/Sniffs/PHP/RemovedFunctionParameterSniffTest.php
- Tests/sniff-examples/removed_function_parameter.php
* Add code to handle parameters which are first deprecated and only later removed. While a parameter is deprecated, but not yet removed, the sniff will show a warning instead of an error.
* Add deprecation version for the existing parameter checks.
* Add some additional removal parameters.
* Minor rewrite of the actual error message.
Includes unit tests and adjusted documentation.
Question: the sniff name does no longer really cover what this sniff does. Should the sniff be renamed ? and if so, to what ? `DeprecatedFunctionParameters` ?
> Improve removedFunctionParameters sniff.

- Sniffs/PHP/RequiredOptionalFunctionParametersSniff.php
- Tests/Sniffs/PHP/RequiredOptionalFunctionParameterSniffTest.php
- Tests/sniff-examples/required_optional_function_parameters.php
Add a sniff which checks for parameters which were originally required and only became optional in a later PHP version.
Includes two known functions were this is sniff should be applied.
> Add requiredOptionalFunctionParameters sniff.

- Sniffs/PHP/ForbiddenEmptyListAssignmentSniff.php
- Tests/Sniffs/PHP/ForbiddenEmptyListAssignmentSniffTest.php
- Tests/sniff-examples/forbidden_empty_list_assignment.php
* Trigger error when there are only comments between the parenthesis.
* Trigger error when there are empty parenthesis between the list parenthesis.
* Don't trigger error for unfinished code when review is used during live coding (in an editor).
* Slightly simplify the code.
* Remove unnecessary `sprintf()`.
Includes unit tests demonstrating the issue with the comments and the parenthesis.
Includes some extra unit tests for valid list assignments.
As there are now more test cases, refactored the unit tests to use data providers as well.
> Improve `ForbiddenEmptyListAssignment` sniff (code review).

- Sniffs/PHP/DeprecatedPHP4StyleConstructorsSniff.php
- Tests/Sniffs/PHP/DeprecatedPHP4StyleConstructorsSniffTest.php
- Tests/sniff-examples/deprecated_php4style_constructors.php
* Bow out early when PHP7 does not have to be supported.
* Defer to PHPCS native methods for determining the class and function names.
* Don't trigger error for namespaced classes with a method with the same name as the class.
> As of PHP 5.3.3, methods with the same name as the last element of a namespaced class name will no longer be treated as constructor. This change doesn't affect non-namespaced classes.
Ref: http://php.net/manual/en/language.oop5.decon.php
Includes unit test for namespaced class with same name method.
Includes additional unit tests verifying the `noViolation` cases.
> Improve `DeprecatedPHP4StyleConstructors` sniff (code review).

- Sniffs/PHP/NewExecutionDirectivesSniff.php
- Tests/Sniffs/PHP/NewExecutionDirectivesSniffTest.php
- Tests/sniff-examples/new_execution_directives.php
This sniff checks for valid execution directives set with `declare()`.
Ref: http://php.net/manual/en/control-structures.declare.php
The sniff contains three distinct checks:
* Check if the execution directive used is valid. PHP currently only supports three execution directives.
* Check if the execution directive used is available in the PHP versions for which support is being checked. In the case of the `encoding` directive on PHP 5.3, support is conditional on the `--enable-zend-multibyte` compilation option. This will be indicated as such.
* Check whether the value for the directive is valid.
> Add new sniff to check for NewExecutionDirectives.

- ruleset.xml
Relates to: https://github.com/wimg/PHPCompatibility/issues/64
> the sniff should report if there any class method that begin with a double-underscore but which are not one of the magic methods as defined by PHP, as these are reserved for future use. Their presence may result in code breakage in future PHP versions.
The upstream sniff covers this well and as this particular check does not need the `supportsAbove()` or `supportsBelow()` methods, there is no need to duplicate code maintenance efforts.
> Use upstream rule to check for methods using a double underscore.

- Sniffs/PHP/NewFunctionParametersSniff.php
- Tests/Sniffs/PHP/NewFunctionParameterSniffTest.php
- Tests/sniff-examples/new_function_parameter.php
Based on the information found in:
http://php.net/manual/en/doc.changelog.php
http://php.net/manual/en/migration52.parameters.php
http://php.net/manual/en/migration53.parameters.php
By no means claiming completeness, but it's big step in the right direction.
Functions are ordered alphabetically. As some functions have several parameters added in different PHP  versions, this made the most sense.
Also:
* Correct parameter name for the `dirname()` function.
* Add quotes around the parameter name in the error notice.
> Add *a lot* more new function parameters to the `NewFunctionParameter` sniff

- Sniff.php
- Sniffs/PHP/NewScalarTypeDeclarationsSniff.php
- Tests/InClassScopeTest.php
- Tests/Sniffs/PHP/NewScalarTypeDeclarationsSniffTest.php
- Tests/sniff-examples/new_scalar_type_declarations.php
- Tests/sniff-examples/utility-functions/in_class_scope.php
This adds a number of additional checks to the `NewScalarTypeDeclarations` sniff.
* Check that type hints are not being used in pre-PHP 5.0 code.
* Check for valid usage of the `array` and `callable` type  hints.
* Check for invalid type hints which are typical mistakes.
* Check that the `self` type hint is only used within the class scope.
Ref: http://php.net/functions.arguments#functions.arguments.type-declaration
Also:
* The `description` key in the `$newTypes` array did not actually add any value, so I've removed it.
* Minor tweaks to the original error message text.
- Was along the lines of: _"int type is not present in PHP version 5.6 or earlier"_.
- Now: _"'int' type declaration is not present in PHP version 5.6 or earlier"_.
Includes unit tests covering all changes.
This PR also …
> Feature completeness `NewScalarTypeDeclarations` sniff (code review).

- Sniffs/PHP/ForbiddenSwitchWithMultipleDefaultBlocksSniff.php
- Tests/Sniffs/PHP/ForbiddenSwitchWithMultipleDefaultBlocksSniffTest.php
- Tests/sniff-examples/forbidden_switch_with_multiple_default_blocks.php
* Determine whether or not a `default` belongs to this switch or to a nested switch based on token `level` attribute.
* Break out of the switch as soon as we've determined there is more than one `default` case. No need to continue walking through the rest of the switch code.
* Add two additional unit tests with case/fall through type code.
* As there are now more error cases, change the error test to a data provider.
> Minor improvements `ForbiddenSwitchWithMultipleDefaultBlocks` sniff (code review).

- Sniffs/PHP/RemovedGlobalVariablesSniff.php
- Tests/Sniffs/PHP/RemovedGlobalVariablesSniffTest.php
* No need to loop through the array, just checking with isset will suffice.
* Code simplification & strict checking.
> Minor improvements to `RemovedGlobalVariables` sniff.

- Sniffs/PHP/LongArraysSniff.php
* No need to check for `T_VARIABLE` as `process()` is only called when `T_VARIABLE`  is found.
* Strict checking.
* Use PHPCS native error message string replacement.
> Minor improvement to the `LongArrays` sniff (code review).

- Sniffs/PHP/ParameterShadowSuperGlobalsSniff.php
- Tests/Sniffs/PHP/ParameterShadowSuperGlobalsSniffTest.php
- Tests/sniff-examples/parameter_shadow_superglobals.php
It seems this sniff was missed both when implementing the `PHPCompatibility_Sniff` base class as well as when the unit tests were added.
This PR fixes that.
Changes:
* Let class extend `PHPCompatibility_Sniff`.
* Use the `supportsAbove()` function for the compatibility check.
* Defer to the PHPCS native `getMethodParameters()` method for getting the parameter names.
* Do a case-insensitive parameter name compare. While variable names are case-insensitive in PHP, it would still be a really bad idea to bypass the "parameter shadowing super globals" issue by using a lowercase version of the variable name.
* Add unit tests.
> Improve `ParameterShadowSuperGlobals` sniff (code review).

- Sniffs/PHP/LateStaticBindingSniff.php
- Tests/Sniffs/PHP/LateStaticBindingSniffTest.php
- Tests/sniff-examples/late_static_binding.php
Late static binding is only available on PHP 5.3 +.
Ref: http://php.net/manual/en/language.oop5.late-static-bindings.php
This sniff throws two new errors:
1. For LSB detected inside class/interface/trait scope and PHP < 5.3.
2. For LSB detected outside of class/interface/trait scope (not supported).
> Add new sniff to detect Late Static Binding.

- Sniffs/PHP/NonStaticMagicMethodsSniff.php
- Tests/Sniffs/PHP/NonStaticMagicMethodsSniffTest.php
- Tests/sniff-examples/nonstatic_magic_methods.php
- Tests/sniff-examples/nonstatic_magic_methods_traits.php
* Also sniff `trait`s for magic methods.
* Do the method name comparison in a case-insensitive manner as functions and methods in PHP are handled case-insensitively.
* Changed the array format to allow for checking visibility and static requirements based on the requirements of individual functions.
* Added a number of extra PHP magic methods to the array.
_For `__sleep()` and `__toString()` only the visibility is explicitly documented, for `__set_state()` only the fact that it has to be static. So currently only checking the documented requirements._
* Added the `SoapClient` magic methods to the array.
_It does not seem to be explicitly documented whether these have a requirement of being non-static, so that's currently not checked._
* For the `SoapClient` methods no extra check is made …
> Improve `NonStaticMagicMethods` sniff (code review).

- Sniffs/PHP/NewMagicMethodsSniff.php
- Tests/Sniffs/PHP/NewMagicMethodsSniffTest.php
- Tests/sniff-examples/new_magic_methods.php
- Tests/sniff-examples/new_magic_methods_traits.php
Closes #64.
This sniff checks for the definition of magic methods and warns that their magic behaviour will not be invoked prior to the version it was introduced in.
For the `__toString()`  method it has a distinct message which describes the changed behaviour of the magic method between PHP 5.1 and 5.2
Similar to PR #174, the unit test cases are split into two files - one covering classes and interfaces, one covering traits. The trait related unit tests will be skipped on PHPCS 1.x combined with PHP 5.3 or lower.
> Add newMagicMethods sniff.

- Sniffs/PHP/ForbiddenBreakContinueVariableArgumentsSniff.php
- Tests/Sniffs/PHP/ForbiddenBreakContinueVariableArgumentsSniffTest.php
- Tests/sniff-examples/forbidden_break_continue_variable_argument.php
* Bug fix: Throw error on closures. Looks like the intend was for this to be implemented, but the reality was that it wasn't working.
* Break out of the `foreach()` as soon as we've determined there is an error, no need to go through the rest of the tokens.
* Bow out early if check is not applicable.
* Minor code simplification.
* Add a number of additional unit test cases & simplified the test case file.
* Reorganised the unit tests to data providers and moved the documentation for the various tests to the test case file.
> Improve `ForbiddenBreakContinueVariableArguments` sniff (code review).

- Sniffs/PHP/ForbiddenFunctionParametersWithSameNameSniff.php
- Tests/Sniffs/PHP/ForbiddenFunctionParametersWithSameNameSniffTest.php
* Don't use function call in loop construct.
* `getMethodParameters()` could return false or an empty array. Bow out early in that case.
> Minor improvements to the `ForbiddenFunctionParametersWithSameName` sniff (code review).

- Sniffs/PHP/ForbiddenNamesAsInvokedFunctionsSniff.php
* Some code simplification.
* Some more strict checking.
* Defer to native `PHP_CodeSniffer_Tokens::$emptyTokens` variable.
> Minor improvements to `ForbiddenNamesAsInvokedFunctions` sniff (code review).

- Sniffs/PHP/ForbiddenNamesAsInvokedFunctionsSniff.php
Array keys are case-sensitive, while keywords when used wrong might not always use lowercase, so let's do a lowercase compare as the array in the sniff is all lowercase.
> Minor fix in ForbiddenNamesAsInvokedFunctionsSniff.

- Sniffs/PHP/RemovedAlternativePHPTagsSniff.php
- Tests/Sniffs/PHP/RemovedAlternativePHPTagsUnitTest.php
- Tests/sniff-examples/removed_alternative_phptags.php
ASP and Script open tags were removed in PHP 7.
Based on a similar sniff I wrote for PHPCS and WPCS, but adjusted to PHPCompatibility type of check.
Closes #127
> Add sniff for detecting alternative PHP open tags.

- Sniffs/PHP/EmptyNonVariableSniff.php
- Tests/Sniffs/PHP/EmptyNonVariableSniffTest.php
- Tests/sniff-examples/empty_non_variable.php
> Prior to PHP 5.5, empty() only supports variables; anything else will result in a parse error. In other words, the following will not work: empty(trim($name)). Instead, use trim($name) == false.
Ref: http://php.net/manual/en/function.empty.php
The checks in the sniff feel a bit simplistic to me, but it works for all the test cases I could come up with. If anyone can think of some more distinct test cases, please let me know!
> Add new sniff to check for use of `empty()` with non-variable arguments.

- .travis.yml
- Tests/BaseSniffTest.php
* Share the PHPCS instance between tests in the same class & cache run results.
* Caching of the results of the PHPCS runs.
So far I'm not actually seeing much difference, so not sure if this should be merged, but might be useful conceptually for someone to build on to in the future.
> Attempt to make the unit tests a bit faster.

- Sniffs/PHP/DeprecatedIniDirectivesSniff.php
- Sniffs/PHP/ForbiddenNamesAsInvokedFunctionsSniff.php
- Sniffs/PHP/RemovedAlternativePHPTagsSniff.php
- Tests/BaseSniffTest.php
* Fix two parse errors
- use of ternary without middle.
- use of `__DIR__`.
* Back-compat of unrecognized tokens in `ForbiddenNamesAsInvokedFunctions` sniff.
* Fix error message consistency for PHP 5.2 for the `RemovedAlternativePHPTags` sniff.
> Fix compatibility issues with PHP 5.2.

- Tests/bootstrap.php
* Make travis build fail if PHPCS cannot be found. Currently if PHPCS could not be found, PHPUnit would exit with 0 and the travis build would pass. With this change it will exit with 1 and the travis build will fail.
* Allow for PHPUnit to be run when PHPCS has been set up in an arbitrary location.
Location can be passed via the phpunit.xml file or via other means of setting environment options.
Via phpunit config - add the following to the phpunit.xml file:
```xml
<php>
<env name="PHPCS_DIR" value="/path/to/phpcs"/>
</php>
```
> More PHPUnit bootstrap tweaks.

- Sniffs/PHP/NewGroupUseDeclarationsSniff.php
The reversed logic caused the error not to be reported when using test ranges.
> Fix reversed version logic in the `NewGroupUseDeclarations` sniff.

- .travis.yml
Tests for syntax errors in the Sniff and Test files.
Excludes the test case files and the `vendor` directory.
> Add php linting to the travis run.

- .travis.yml
- Tests/Sniffs/PHP/DeprecatedPHP4StyleConstructorsSniffTest.php
- Tests/Sniffs/PHP/ForbiddenNamesSniffTest.php
- Tests/Sniffs/PHP/NewGroupUseDeclarationsSniffTest.php
- Tests/Sniffs/PHP/NewKeywordsSniffTest.php
- Tests/Sniffs/PHP/NewLanguageConstructsSniffTest.php
- Tests/Sniffs/PHP/RemovedAlternativePHPTagsUnitTest.php
* Set up travis to enable testing on PHP 5.2
* Fix unit tests for testing on PHP 5.2 - this is practice means that some tests will be skipped on 5.3.
As composer is not available on PHP 5.2, just pulling in the repos straight from GitHub.
As a side-note, I find the time difference this makes (the main difference is the whole coveralls repo + run) quite significant...
> Travis test on PHP 5.2

- Sniffs/PHP/NewAnonymousClassesSniff.php
The reversed logic caused the error not to be reported when using test ranges.
> Fix reversed logic in the `NewAnonymousClasses` sniff.

- Sniffs/PHP/TernaryOperatorsSniff.php
- Tests/Sniffs/PHP/TernaryOperatorsSniffTest.php
- Tests/sniff-examples/ternary_operator.php
* The sniff was not reporting errors for ranges which included 5.2 or lower, but also included 5.3  or higher. Logic for version testing was using the wrong method.
* Remove unnecessary `sprintf()`
* Added additional unit test - code taken from this sniff library which was not being reported which was the reason I started looking into this one.
> Fix `TernaryOperators` sniff (code review).

- Sniffs/PHP/NewFunctionArrayDereferencingSniff.php
Logic was inadvertently reversed in https://github.com/wimg/PHPCompatibility/commit/26d0b6cf0921f75d93a4faaf09c390f386dde9ff
SupportsAbove = false is not the same as SupportsBelow = true. Using it like that will break on testVersion ranges.
I understand the preference for SupportsAbove though, but that's to do with a different bug altogether - see issue #142. I'd be happy to fix that if someone could confirm the intended behaviour for me.
> Fix reversed version logic.

- Sniffs/PHP/ConstantArraysUsingDefineSniff.php
- Tests/Sniffs/PHP/ConstantArraysUsingDefineSniffTest.php
* Fix bug in version check - `if ($this->supportsAbove('7.0') === false)` is not the same as `if ($this->supportsBelow('5.6') === true)`. This was not caught by the unit tests as they use single versions, but the difference is basically that if `$testVersion` was set to `5.4-7.0`, the message would previously not show and now it will.
* Exit early if the check is not relevant.
* Use the new `getFunctionCallParameter()` method to get the relevant parameter.
* Separate violation and noViolation unit tests and set them up to use data providers.
> Minor improvements to `ConstantArraysUsingDefine` sniff (code review).

- Sniffs/PHP/MbstringReplaceEModifierSniff.php
- Tests/Sniffs/PHP/MbstringReplaceEModifierSniffTest.php
- Tests/sniff-examples/mbstring_replace_e_modifier.php
... which will be deprecated in PHP 7.1
Ref: https://wiki.php.net/rfc/deprecate_mb_ereg_replace_eval_option
> New sniff to check for use of the Mbstring regex e modifier.

- Sniff.php
- Tests/GetFQClassNameFromDoubleColonTokenTest.php
- Tests/GetFQClassNameFromNewTokenTest.php
- Tests/sniff-examples/utility-functions/get_fqclassname_from_double_colon_token.php
- Tests/sniff-examples/utility-functions/get_fqclassname_from_new_token.php
Closes #205
* Adds the test case mentioned in the issue to the unit tests for the `getFQClassNameFromDoubleColonToken()` function  + adds a variant of it to the unit tests for the `getFQClassNameFromNewToken()` function.
* Fixes the issue in both functions.
* Unit tests for the `getFQClassNameFromDoubleColonToken()` function were not being run due to a file name error. Fixed that too.
> Fix PHP Warning in `NewClasses` sniff.

- Sniffs/PHP/ForbiddenBreakContinueVariableArgumentsSniff.php
- Tests/Sniffs/PHP/ForbiddenBreakContinueVariableArgumentsSniffTest.php
- Tests/sniff-examples/forbidden_break_continue_variable_argument.php
Since PHP 5.4, statements like `break 0;` and `continue 0;` is no longer supported.
This PR is supported for this in `Sniffs/PHP/ForbiddenBreakContinueVariableArgumentsSniff.php`.
>The break and continue statements no longer accept variable arguments (e.g., break 1 + foo() * $bar;). Static arguments still work, such as break 2;. As a side effect of this change break 0; and continue 0; are no longer allowed.
http://php.net/manual/en/migration54.incompatible.php
What do you think?
Thank you for good tools 🙇
> Supported sniff for break/continue 0

- Sniffs/PHP/PregReplaceEModifierSniff.php
- Tests/Sniffs/PHP/PregReplaceEModifierSniffTest.php
- Tests/sniff-examples/preg_replace_e_modifier.php
* Use the new `getFunctionCallParameter()` method to retrieve the target parameter info.
* Make the double separators a class property.
* Do the function name comparison in lowercase.
* Show the correct function name in the error message.
* Slight logic simplification.
* Add two extra test cases for regexes build up of strings combined with variables/function calls.
* Fix one test case which was missing any form of delimiters.
* Rework the unit test file to data providers.
> Improve `PregReplaceEModifier` Sniff (code review).

- README.md
As per https://github.com/wimg/PHPCompatibility/issues/142#issuecomment-242345377
Includes minor wording, spelling and layout fixes.
> Correct the information about setting the `testVersion` from a config file

- Sniff.php
- Tests/GetFunctionParametersTest.php
- Tests/sniff-examples/utility-functions/get_function_parameters.php
Prevent code like the following from setting a third parameter in the return value of `getFunctionCallParameters()`:
```php
functionCall( $param1, $param2, );
```
Inspired by #211 - this was the only type of code I could come up with, with which I could reproduce the issue mentioned in #211.
For a real solution to #211 proper, we need more input from the issue reporter.
--------
**Update:** I've added a second commit to this PR which fixes the actual issue as reported in #211 which turned out to be about the short array syntax.
"Normal" array syntax adds a parenthesis nesting level, however the short array syntax does not. So this has to be dealt with separately in the logic to determine where a parameter starts and ends.
Closes #211
> Minor improvement to the `getFunctionCallParameters()` method.

- Tests/BaseClass/DoesFunctionCallHaveParametersTest.php
- Tests/BaseClass/GetFQClassNameFromDoubleColonTokenTest.php
- Tests/BaseClass/GetFQClassNameFromNewTokenTest.php
- Tests/BaseClass/GetFQExtendedClassNameTest.php
- Tests/BaseClass/GetFunctionParametersTest.php
- Tests/BaseClass/MethodTestFrame.php
- Tests/BaseClass/TestHelperPHPCompatibility.php
- Tests/BaseClass/TokenHasScopeTest.php
- Tests/bootstrap.php
* Move files containing tests for methods in the abstract base class `PHPCompatibility_Sniff` to their own subdirectory.
* Move related support files to that same subdirectory.
* Rename the test base class for these tests to a slightly more intuitive name.
* Add `@covers` annotations for each of these tests.
> Minor reorganization of test directory.

- README.md
I was running into issues when locally testing other sniff libs which do use the PHPCS native testing framework.
The short of it was that this would result in a fatal error before any unit tests would be run as PHPCS was trying to load the PHPCompatibility unit test and sniff files and the setup is differently from what PHPCS expects.
I've figured out a solution for this which resulted in PR https://github.com/squizlabs/PHP_CodeSniffer/pull/1146
Once that PR is merged, the loading of the PHPCompatibility unit tests can be bypassed allowing for the testing of other sniff libraries without running into problems.
This PR adds a section to the Readme explaining how to apply the bypass for other developers who work on both PHPCompatibility as well as other sniff libs.
> Add section about testing other sniff libs to readme.

- Sniffs/PHP/ForbiddenCallTimePassByReferenceSniff.php
- Tests/Sniffs/PHP/ForbiddenCallTimePassByReferenceSniffTest.php
- Tests/sniff-examples/call_time_pass_by_reference.php
* Fix PHP version - was 5.4+, but the feature was already deprecated in 5.3. The error message will reflect this now too.
* Prevent errors during live code review.
* Prevent false positives for interface and trait declarations.
* Use the new `getFunctionCallParameters()` method for more precise walking of the parameters.
* Abstracted the actual CTPbR determination out to it's own method.
* Stricter variable checking.
* Added some more test cases and added additional documentation for the test cases.
* Added additional version based tests. The error cases were only tested for throwing an error, now they are also tested for *not* throwing an error in PHP 5.2 and throwing the slightly adjusted error in PHP 5.3.
* Removed a false positive unit test (test case is still there) - bitwise …
> Improve the `ForbiddenCallTimePassByReference` sniff (code review).

- Sniff.php
- Sniffs/PHP/DeprecatedIniDirectivesSniff.php
- Sniffs/PHP/ForbiddenNamesSniff.php
- Sniffs/PHP/MbstringReplaceEModifierSniff.php
- Sniffs/PHP/NewExecutionDirectivesSniff.php
- Sniffs/PHP/NewIniDirectivesSniff.php
- Sniffs/PHP/PregReplaceEModifierSniff.php
- Sniffs/PHP/RemovedHashAlgorithmsSniff.php
- Sniffs/PHP/ValidIntegersSniff.php
- Tests/BaseClass/FunctionsTest.php
... to strip quotes which surround `T_CONSTANT_ENCAPSED_STRING`s in a consistent manner.
Includes unit tests for the newly introduced function.
> Add new `stripQuotes()` method.

- README.md
As discussed in #141 it would be sensible to document what versions of PHP are supported, both for running the sniff and for the compatibility checks it contains.
I hope I have accurately captured the current state of the project in this regard, but please amend as necessary.
> Added note about PHP version support to README.md

- .scrutinizer.yml
As the test methods and data providers are all very similar, Scrutinizer will report on these as if they were duplicates.
Also, it skews the quality score as that's supposed to be about the quality of the library itself, not about the tests covering the library.
> Exclude `tests` directory alltogether from Scrutinizer config.

- Sniffs/PHP/NewFunctionArrayDereferencingSniff.php
- Tests/Sniffs/PHP/NewFunctionArrayDereferencingSniffTest.php
- Tests/sniff-examples/new_function_array_dereferencing.php
> Sniff methods too in `NewFunctionArrayDereferencing` sniff.

- Sniffs/PHP/ForbiddenNegativeBitshiftSniff.php
- Tests/Sniffs/PHP/ForbiddenNegativeBitshiftSniffTest.php
- Tests/sniff-examples/forbidden_negative_bitshift.php
* Prevent undefined index notice when no LNUMBER can be found.
* Prevent undefined index notice on live code review.
* More precise token walking.
Includes additional unit tests for the above.
As there are now more unit tests, these have been reworked to data providers.
The PR contains one additional unit test which still yields a false positive. This has been so annotated.
> Minor improvements to `ForbiddenNegativeBitshift` sniff.

- Sniffs/PHP/EmptyNonVariableSniff.php
- Tests/Sniffs/PHP/EmptyNonVariableSniffTest.php
- Tests/sniff-examples/empty_non_variable.php
Closes #210.
* Disregards tokens within variable variable brackets/array key brackets.
* Includes additional unit tests.
> Fix `EmptyNonVariable` sniff combined with variable variables.

- Sniffs/PHP/DeprecatedFunctionsSniff.php
- Sniffs/PHP/NewClassesSniff.php
- Sniffs/PHP/NewFunctionsSniff.php
- Sniffs/PHP/NewInterfacesSniff.php
- Sniffs/PHP/NewScalarReturnTypeDeclarationsSniff.php
- Sniffs/PHP/NewScalarTypeDeclarationsSniff.php
Additional clean-up of remaining unused `$pattern` references.
Related:
* https://github.com/wimg/PHPCompatibility/commit/26d0b6cf0921f75d93a4faaf09c390f386dde9ff
* https://github.com/wimg/PHPCompatibility/commit/8416162ea81f4067226324f5948f4a50f7958a9b
> Remove unused `$pattern` variables.

- Sniffs/PHP/NewExecutionDirectivesSniff.php
- Tests/Sniffs/PHP/NewExecutionDirectivesSniffTest.php
Changed error level for the invalid value checks for execution directives from error to warning as it doesn't directly translate to a compatibility issue.
Alternatively, these "valid value" checks could be removed if that would be preferred, though it is doubtful anyone who knows what they're doing will ever see them anyway.
> Adjust error level for invalid execution directives to warning.

- Sniffs/PHP/ParameterShadowSuperGlobalsSniff.php
- Tests/Sniffs/PHP/ParameterShadowSuperGlobalsSniffTest.php
- Tests/sniff-examples/parameter_shadow_superglobals.php
Fixes #214
* Check for variables names is now only done in a case-sensitive manner.
* The lowercase test cases have been moved to the 'testValidParameter()' unit test and so annotated in the test case file.
* As there are now more `noViolation` tests, the `testValidParameter()` method has been changed to use a dataprovider.
* Also fixes some copy/paste artifacts in the test documentation of the `testParameterShadowSuperGlobals()` method.
> ParameterShadowSuperGlobalsSniff should only do a case-sensitive check.

- Sniff.php
Account for the fact that namespaces cannot be nested, but they **_can_** be contained within another scope, i.e. the `declare()` scope when used with braces.
> Fix: namespace declarations can be nested within scoped declare() {} statements.

- Sniff.php
Upstream the PR for this method was merged and released in the 2.7.0 release.
> Defer to upstream `findImplementedInterfaceNames()` method if available.

- Sniffs/PHP/DeprecatedPHP4StyleConstructorsSniff.php
- Tests/Sniffs/PHP/DeprecatedPHP4StyleConstructorsSniffTest.php
- Tests/sniff-examples/deprecated_php4style_constructors.php
Both class names as well as function names in PHP are case-insensitive, so this check should be done in a case-insensitive manner.
Also:
* As there are now more unit tests, refactored the test file to use data providers in line with other test files.
* The error message was grammatically incorrect. This has now been fixed.
----
~~_**Note**: the unit tests are currently failing against master. That is unrelated to this PR, but has to do with a change upstream which affects the test framework.
See https://github.com/wimg/PHPCompatibility/pull/235#issuecomment-249254988 for more info._~~ Fixed upstream. Unit tests should pass again.
> Make `DeprecatedPHP4StyleConstructors` sniff case-insensitive.

- Sniffs/PHP/NewClassesSniff.php
- Tests/Sniffs/PHP/NewClassesSniffTest.php
- Tests/sniff-examples/new_classes.php
Class names in PHP are case-insensitive, so this check should be done in a case-insensitive manner.
----
~~_**Note**: the unit tests are currently failing against master. That is unrelated to this PR, but has to do with a change upstream which affects the test framework.
See https://github.com/wimg/PHPCompatibility/pull/235#issuecomment-249254988 for more info._~~ Fixed upstream. Unit tests should pass again.
> Make `NewClasses` sniff case-insensitive.

- Sniffs/PHP/ShortArraySniff.php
- Tests/Sniffs/PHP/ShortArraySniffTest.php
- Tests/sniff-examples/short_array.php
This sniff was using unnecessary nested loops and walking a complete file from the PHP open tag down instead of sniffing for the actual short array tags.
This simplifies the sniff immensely and should make the sniff faster.
Includes some additional unit test cases.
Also:
* Refactored the unit tests to data providers.
* Check the violation case properly against version for violation/noViolation.
* Check non-offending syntaxes for false positives through an improved noViolation test.
----
~~_**Note**: the unit tests are currently failing against master. That is unrelated to this PR, but has to do with a change upstream which affects the test framework.
See https://github.com/wimg/PHPCompatibility/pull/235#issuecomment-249254988 for more info._~~ Fixed upstream. Unit tests should pass again.
> Rewrite the `ShortArray` sniff.

- Sniff.php
- Sniffs/PHP/RemovedHashAlgorithmsSniff.php
- Tests/Sniffs/PHP/RemovedHashAlgorithmsSniffTest.php
- Tests/sniff-examples/removed_hash_algorithms.php
* Add `hash_pbkdf2()` function to the list of functions to check + added unit test to that effect.
* Moved the functions list to the main `PHPCompatibility_Sniff` in anticipation of a `NewHashAlgorithms` sniff (upcoming).
* Do the function name comparison in a case-insensitive manner.
* Use the `PHPCompatibility_Sniff::getFunctionCallParameter()` method to get the target algorithm parameter.
* Refactored the sniff to be more flexible.
- The algorithms to sniff for have been moved to an array with version numbers similar to most other sniffs. This allows for the adding of additional removed algorithms with different PHP removal versions in the future.
- Allow for algorithms being deprecated before being removed.
- The error message now specifically references the algorithm encountered.
* …
> Improve the `RemovedHashAlgorithms` sniff (code review).

- Sniff.php
- Sniffs/PHP/NewHashAlgorithmsSniff.php
- Tests/Sniffs/PHP/NewHashAlgorithmSniffTest.php
- Tests/sniff-examples/new_hash_algorithms.php
Sister-sniff to the `RemovedHashAlgorithms` sniff, this sniff checks for hash algorithms which were newly introduced in PHP.
Ref: http://php.net/manual/en/function.hash-algos.php
Moved the algorithm name determination out of the the `RemovedHashAlgorithms` sniff to the base sniff to prevent code duplication as we need to do exactly the same in this sniff.
> Add new `NewHashAlgorithms` sniff.

- Sniffs/PHP/NewInterfacesSniff.php
`strtolower()` turns everything into a string, so the `is_string()` check would always return `true`. Checking for an empty string instead fixes this.
Alternatively I could separate the two function calls `strtolower($phpcsFile->getDeclarationName())` into two separate lines to make it easier to understand for someone reading the code.
> Minor fix for `NewInterfaces` sniff.

- Sniffs/PHP/RemovedGlobalVariablesSniff.php
- Tests/Sniffs/PHP/RemovedGlobalVariablesSniffTest.php
- Tests/sniff-examples/removed_global_variables.php
Similar to the `ParameterShadowSuperGlobals` sniff, I'd inadvertently made the `RemovedGlobalVariables` sniff case-insensitive as well.
As variables are case-sensitive in PHP, this should be reverted.
Added some additional unit tests to safe-guard this and reworked the unit tests to dataproviders.
> Revert the case-insensitivity of the `RemovedGlobalVariables` sniff.

- Sniffs/PHP/NewIniDirectivesSniff.php
- Tests/Sniffs/PHP/NewIniDirectivesSniffTest.php
- Tests/sniff-examples/new_ini_directives.php
The error message was showing in one version too high.
I.e. `mail.log` ini directives was introduced in PHP 5.3. The error message *should* show for PHP 5.2 and lower, not for PHP 5.3, but in practice it was also showing for PHP 5.3.
Also:
* Adjusted the actual error message to be in line with this. Adjusted the message to mirror similar messages used in other sniffs.
* For ini directives introduced in patch versions of PHP, adjusted the _"last version before"_ in the data array to be in line with the adjusted version check.
* Changed the error message to use the native PHPCS variable replacement.
* Changed the error message **type** to `error` when the ini directive was used in an `ini_set()`, left it as `warning` for `ini_get()`. This is also how it is done in the …
> Fix error message version check in the `NewIniDirectives` sniff.

- Sniffs/PHP/NewScalarTypeDeclarationsSniff.php
- Tests/Sniffs/PHP/NewScalarTypeDeclarationsSniffTest.php
- Tests/sniff-examples/new_scalar_type_declarations.php
Ref:
* http://php.net/manual/en/migration71.new-features.php#migration71.new-features.iterable-pseudo-type
* https://wiki.php.net/rfc/iterable
The sniff name might need adjusting to better cover what the sniff does.
> Add new PHP 7.1 `iterable` type hint

- Sniffs/PHP/NewScalarReturnTypeDeclarationsSniff.php
- Tests/Sniffs/PHP/NewScalarReturnTypeDeclarationsSniffTest.php
- Tests/sniff-examples/new_scalar_return_type_declarations.php
* The `description` key in the data array had no added value as the string could easily be concatenated, so removed it.
* The unit tests needed some refactoring as they were hard-coded to only test on version 7.0 and PHP 7.1 will introduce another new return type (`void`).
* Also - commit 65390fa removed the actual testing for the error message which was apparently breaking the unit tests.
This commit brings those tests back and so far I'm not seeing any breakage in the unit tests because of it.
----
Ref:
* http://php.net/manual/en/migration71.new-features.php#migration71.new-features.void-functions
* https://wiki.php.net/rfc/void_return_type
The sniff name might need adjusting to better cover what the sniff does.
> Minor improvements to the `NewScalarReturnTypeDeclarations` sniff (incl PHP 7.1 addition)

- Sniffs/PHP/LongArraysSniff.php
- Tests/Sniffs/PHP/LongArraysSniffTest.php
- Tests/sniff-examples/long_arrays.php
Fixes #268
---
In other sniffs, "deprecated" generally throws a warning, while "forbidden/removed" throws an error.
This sniff was always throwing a warning.
This has now been mitigated and will throw a warning for deprecated and error for removed.
> Fix issue 268 long array vs class properties

- Sniffs/PHP/NewKeywordsSniff.php
This bug seems to only manifest during unit testing, but would cause unit tests to fail on a `Undefined index "T_OPEN_PARENTHESIS"` in the `addError()` method of this sniff.
As the sniffing is quite token specific, it is weird that a `T_OPEN_PARENTHESIS` token would ever reach that method. All the same, the notice is interfering with other tests, so we might as well prevent it being thrown.
This fix takes care of that.
> Fix weird undefined index bug in `NewKeywords` sniff.

- Sniffs/PHP/PregReplaceEModifierSniff.php
- Tests/Sniffs/PHP/PregReplaceEModifierSniffTest.php
- Tests/sniff-examples/preg_replace_e_modifier.php
Using the `raw` first parameter value worked fine when the string quotes of the first string token and the last string token in the parameter were the same, but was breaking on mixed quotes.
```php
// Compound parameter with same string quotes at the start and end - this was working fine:
'/something' . $variable . 'something else/e'
"/something" . preg_quote($variable) . "something else/e"
"/something" . ' and something more and ' . "something else/e"
// Compound parameter with mixed string quotes at the start and end - this was breaking:
'~'.testme()."~s"
```
This PR fixes this.
Closes #265
> Fix PCRE /e modifier sniff for compound parameter with different quotes.

- Sniffs/PHP/NewFunctionsSniff.php
- Tests/Sniffs/PHP/NewFunctionsSniffTest.php
- Tests/sniff-examples/new_functions.php
While this function appears to be missing from the manual, it is mentioned in the changelog and the associated PR was merged.
Ref:
* http://php.net/ChangeLog-7.php#7.0.7
* https://github.com/php/php-src/commit/e8abb70fc94247450e4016040272fc9459d18371
> PHP 7.0.7: add new `socket_export_stream` function to `NewFunctions` sniff

- Sniffs/PHP/DeprecatedIniDirectivesSniff.php
- Tests/Sniffs/PHP/DeprecatedIniDirectivesSniffTest.php
- Tests/sniff-examples/deprecated_ini_directives.php
Ref:
* http://php.net/manual/en/migration71.incompatible.php#migration71.incompatible.removed-ini-directives
* https://wiki.php.net/rfc/session-id-without-hashing
> PHP 7.1: add removed session ini directives to `DeprecatedIniDirectives` sniff.

- Sniffs/PHP/NewIniDirectivesSniff.php
- Tests/Sniffs/PHP/NewIniDirectivesSniffTest.php
- Tests/sniff-examples/new_ini_directives.php
Ref:
* http://php.net/manual/en/migration71.other-changes.php#migration71.other-changes.session-id-generation-without-hashing
* https://wiki.php.net/rfc/session-id-without-hashing
> PHP 7.1: add new session ini directives to `DeprecatedIniDirectives` sniff

- Sniffs/PHP/NewMultiCatchSniff.php
- Tests/Sniffs/PHP/NewMultiCatchSniffTest.php
- Tests/sniff-examples/new_multi_catch.php
Fixes #251 
Ref:
* http://php.net/manual/en/migration71.new-features.php#migration71.new-features.mulit-catch-exception-handling
* https://wiki.php.net/rfc/multiple-catch
> PHP 7.1: New sniff for catch statements catching multiple exceptions.

- Sniffs/PHP/NewFunctionsSniff.php
- Tests/Sniffs/PHP/NewFunctionsSniffTest.php
- Tests/sniff-examples/new_functions.php
Refs:
* http://php.net/manual/en/migration71.new-functions.php
* http://php.net/manual/en/migration71.new-features.php#migration71.new-features.asynchronous-signal-handling
Related RFCs:
* `curl_...()` - https://wiki.php.net/rfc/new-curl-error-functions
* `is_iterable()` - https://wiki.php.net/rfc/iterable
* `pcntl_async_signals()` https://wiki.php.net/rfc/async_signals
* `session_create_id()` - https://wiki.php.net/rfc/session-create-id
* `session_gc()` - https://wiki.php.net/rfc/session-gc
> PHP 7.1: add new functions to the `NewFunctions` sniff.

- Sniffs/PHP/NewConstVisibilitySniff.php
- Tests/Sniffs/PHP/NewConstVisibilitySniffTest.php
- Tests/sniff-examples/new_const_visibility.php
Introduces a new sniff to detect the use of visibility indicators for `class` & `interface` constants in pre-PHP 7.1 code.
Fixes #249
* AFAIK _class constants_ can not be defined in traits, so traits are disregarded for the purposes of this sniff. Please correct me if I'm wrong in this regard.
* The only valid visibility indicator for constants in `interface`s is `public`. However validating the visibility indicator used is outside the scope of this sniff/sniff library. See: https://github.com/wimg/PHPCompatibility/issues/249#issuecomment-254678830
* Visibility indicators for constants outside class scope are not supported in any PHP version. However, this again is outside the scope of this sniff/sniff library. See: …
> PHP 7.1: New sniff for class constant visibility indicators.

- Sniff.php
- Sniffs/PHP/NewNullableTypesSniff.php
- Tests/Sniffs/PHP/NewNullableTypesSniffTest.php
- Tests/sniff-examples/new_nullable_types.php
PHP 7.1 introduces nullable type hints and nullable return types.
As return types are only recognized in PHPCS 2.3.4+, this return type part of this sniff is not available in earlier PHPCS versions.
For the type hints, the `getMethodParameters()` utility method has been adjusted and a PR for the same has been submitted upstream. https://github.com/squizlabs/PHP_CodeSniffer/pull/1193
Fixes #247 
Ref:
* http://php.net/manual/en/migration71.new-features.php#migration71.new-features.nullable-types
* https://wiki.php.net/rfc/nullable_types
This PR does **not** contain a warning about the backward compatibility break nullable types can cause as it is not possible to reliably test for it.
The backward compatibility break occurs when a parent class or interface defines a default value of `null` …
> PHP 7.1: New sniff for nullable types.

- Sniffs/PHP/ForbiddenBreakContinueOutsideLoopSniff.php
- Tests/Sniffs/PHP/ForbiddenBreakContinueOutsideLoopSniffTest.php
- Tests/sniff-examples/forbidden_break_continue_outside_loop.php
Usage of a break/continue statement outside control structure loops or switch statements was never valid, however since PHP 7.0 it will throw a fatal error.
Fixes #275
> Add new `ForbiddenBreakContinueOutsideLoop` sniff.

- Sniffs/PHP/DeprecatedPHP4StyleConstructorsSniff.php
- Sniffs/PHP/ForbiddenCallTimePassByReferenceSniff.php
- Sniffs/PHP/MbstringReplaceEModifierSniff.php
- Sniffs/PHP/PregReplaceEModifierSniff.php
- Sniffs/PHP/TernaryOperatorsSniff.php
- Sniffs/PHP/ValidIntegersSniff.php
- Tests/Sniffs/PHP/DeprecatedPHP4StyleConstructorsSniffTest.php
- Tests/Sniffs/PHP/ForbiddenCallTimePassByReferenceSniffTest.php
- Tests/Sniffs/PHP/MbstringReplaceEModifierSniffTest.php
- Tests/Sniffs/PHP/PregReplaceEModifierSniffTest.php
- Tests/Sniffs/PHP/TernaryOperatorsSniffTest.php
- Tests/Sniffs/PHP/ValidIntegersSniffTest.php
Looking at all the other sniffs:
* **_Deprecated_** functionality should throw a warning.
* **_Removed_** or otherwise unavailable functionality should throw an error.
This distinction was not consistently applied everywhere.
In part inspired by https://github.com/wpengine/phpcompat/issues/73 (which this solves).
> Improve consistency of warning/error logic.

- Sniffs/PHP/DeprecatedFunctionsSniff.php
- Sniffs/PHP/DeprecatedIniDirectivesSniff.php
- Sniffs/PHP/NewFunctionParametersSniff.php
- Sniffs/PHP/NewFunctionsSniff.php
- Sniffs/PHP/RemovedFunctionParametersSniff.php
- Tests/Sniffs/PHP/DeprecatedFunctionsSniffTest.php
- Tests/Sniffs/PHP/DeprecatedIniDirectivesSniffTest.php
The message text for removed functions and ini directives used "forbidden" was IMHO could be misleading.
The message text has been adjusted to use "removed" instead.
For clarity relevant variable names containing "forbidden" have been adjusted to use "removed" as well.
P.S.: _I kind of have feeling this is a left-over from the first version of these sniffs being based on the PHPCS native `Generic.PHP.ForbiddenFunctions` sniff_.
> Improve message text and variable names for deprecated/removed sniffs.

- Sniffs/PHP/DeprecatedMagicAutoloadSniff.php
Fix issue with `die()` not working + function names are case insensitive.
> Fix issue with DeprecatedMagicAutoloadSniff

- Sniffs/PHP/ForbiddenNamesAsDeclaredSniff.php
- Tests/Sniffs/PHP/ForbiddenNamesAsDeclaredSniffTest.php
- Tests/sniff-examples/forbidden_names_as_declared.php
See: http://php.net/manual/en/migration71.incompatible.php#migration71.incompatible.invalid-class-names
> PHP7.1: Add new reserved words to `ForbiddenNamesAsDeclared` sniff

- Tests/BaseSniffTest.php
They already were on the array key `''` (empty string), but this behaviour might change at any moment, so better be safe than sorry.
> Make it clearer that non-version specific parsed sniff files are also being cached

- Tests/Sniffs/PHP/ConstantArraysUsingDefineSniffTest.php
- Tests/Sniffs/PHP/DeprecatedIniDirectivesSniffTest.php
- Tests/Sniffs/PHP/ForbiddenFunctionParametersWithSameNameSniffTest.php
- Tests/Sniffs/PHP/ForbiddenSwitchWithMultipleDefaultBlocksSniffTest.php
- Tests/Sniffs/PHP/NewMultiCatchSniffTest.php
- Tests/Sniffs/PHP/NewScalarTypeDeclarationsSniffTest.php
- Tests/Sniffs/PHP/RemovedExtensionsSniffTest.php
- Tests/sniff-examples/constant_arrays_using_define.php
- Tests/sniff-examples/deprecated_ini_directives.php
- Tests/sniff-examples/forbidden_function_parameters_with_same_name.php
- Tests/sniff-examples/forbidden_switch_with_multiple_default_blocks.php
- Tests/sniff-examples/new_multi_catch.php
- Tests/sniff-examples/new_scalar_type_declarations.php
- Tests/sniff-examples/removed_extensions.php
If/when #307 will be merged, the code coverage will decrease because unintentionally covered lines will no longer be covered, exposing them more clearly.
For this PR I've gone through the code coverage results of #307 and made a first round of improvements.
This mostly involves the addition of some extra test cases against false positives.
> Improve test code coverage

- Tests/BaseClass/DoesFunctionCallHaveParametersTest.php
- Tests/BaseClass/GetFQClassNameFromDoubleColonTokenTest.php
- Tests/BaseClass/GetFQClassNameFromNewTokenTest.php
- Tests/BaseClass/GetFQExtendedClassNameTest.php
- Tests/BaseClass/GetFunctionParametersTest.php
- Tests/BaseClass/MethodTestFrame.php
- Tests/BaseClass/TokenHasScopeTest.php
Uncouple the `MethodTestFrame` from the `BaseSniffTest` & set the directory path for the utility test files in the parent class.
Also:
- Add documentation for the `$filename` property in all utility test files.
- Make the property `protected`.
> Minor tweaks to the utility tests

- Sniffs/PHP/VariableVariablesSniff.php
- Tests/Sniffs/PHP/VariableVariablesSniffTest.php
- Tests/sniff-examples/variable_variables.php
Crafted to prevent false positives.
Ref:
http://php.net/manual/en/migration70.incompatible.php#migration70.incompatible.variable-handling
https://wiki.php.net/rfc/uniform_variable_syntax
Fixes #309
> PHP 7.0: Add new sniff to detect variable variables for which the behaviour has changed

- Sniffs/PHP/NewKeywordsSniff.php
- Tests/Sniffs/PHP/NewKeywordsSniffTest.php
- Tests/sniff-examples/new_keywords.php
Includes additional unit test for the same.
> Fix `const` keyword used in interfaces throws an error when it shouldn't

- Sniffs/PHP/VariableVariablesSniff.php
Fixes failing unit tests caused by changed behavior of PHPCS > 2.7.1.
See:
* https://github.com/squizlabs/PHP_CodeSniffer/commit/79cd3dcd16179d76e72fdf60853745b6c1f8fb40
* https://github.com/squizlabs/PHP_CodeSniffer/issues/1245
> Recognize T_SELF as well in variable variables.

- Sniff.php
- Sniffs/PHP/PregReplaceEModifierSniff.php
- Tests/BaseClass/DoesFunctionCallHaveParametersTest.php
- Tests/BaseClass/GetFunctionParametersTest.php
- Tests/Sniffs/PHP/PregReplaceEModifierSniffTest.php
- Tests/sniff-examples/preg_replace_e_modifier.php
- Tests/sniff-examples/utility-functions/does_function_call_have_parameters.php
- Tests/sniff-examples/utility-functions/get_function_parameters.php
The first parameter of a `preg_replace()` function call can be either a string or an array.
Up to now, the sniff always treated the first parameter as a string, leading to false positives (and potentially missing messages for regexes within a passed array).
Ref: http://php.net/manual/en/function.preg-replace.php
Now, each individual entry in the array will be analysed and passed along for inspection.
This PR also fixes potential false positives caused by string concatenation which caused the delimiters to be misidentified.
Ref: http://php.net/manual/en/regexp.reference.delimiters.php
Fixes https://wordpress.org/support/topic/wrong-error-preg_replace-e-modifier-is-forbidden-since-php-7-0/
/cc @octalmage
> Allow for an array of regex patterns in the PregReplaceEModifierSniff

- .travis.yml
- Tests/bootstrap.php
- phpcs.xml
* Use the correct coveralls version for each PHP version.
Coveralls 1.x has a PHP 5.3.3 minimum requirement, coveralls 2.x has a PHP 5.5 minimum requirement.
* Coveralls can not run on PHP 5.2 at all, so no need to define the environment variable, set up the log directory or to attempt to run the coveralls command
* Change `install` to `before_install`. This will mark the build as "errored" if the build fails because the environment could not be set up correctly instead of "failed".
* Change `after_script` to `after_success` as running the coveralls code coverage check is not much use if the unit tests fail.
* Run the code of the standard itself through PHPCS to test for cross-version PHPCompatibility. The `phpcs.xml` can later be extended to also include actual code style sniffs.
The …
> Review travis script

- Sniff.php
- Tests/BaseClass/TokenHasScopeTest.php
- Tests/sniff-examples/utility-functions/token_has_scope.php
Sometimes you suddenly discover an upstream method you didn't know about before - and it even turns out that the method already existed in PHPCS 1.x.... ;-)
As the functions do still have added value to reduce duplicate code, I've elected to leave them in, but defer to the upstream method for the actual scope determination.
[Edit]:
Added an additional commit to also allow for anonymous classes in the `inClassScope()` method. (+ additional unit test)
> Defer to upstream `hasCondition()` method for scope determination.

- Sniffs/PHP/ForbiddenGlobalVariableVariableSniff.php
- Tests/Sniffs/PHP/ForbiddenGlobalVariableVariableSniffTest.php
- Tests/sniff-examples/forbidden_global_variable_variable.php
The `ForbiddenGlobalVariableVariableSniff` would currently only detect variable variables in a `global` statement if it was the first variable of the statement.
It basically didn't take multi-variable `global` statements into account.
Includes reworking the test class to use data providers as there are now more test cases.
> Allow for multiple variables made global in ForbiddenGlobalVariableVariableSniff

- Sniffs/PHP/ForbiddenNamesSniff.php
In PHPCS < 2.3.4, the type of the `class` keyword for anonymous classes is still `T_CLASS`.
This fix allows for that.
> Fix anonymous class exclusion for PHPCS < 2.3.4 for ForbiddenNamesSniff

- Sniffs/PHP/NewGroupUseDeclarationsSniff.php
- Tests/Sniffs/PHP/NewGroupUseDeclarationsSniffTest.php
- Tests/sniff-examples/new_group_use_declarations.php
When looking to increase code coverage, this seemed like a quick fix to make.
I've also tested it against various PHPCS versions and the version number previously used for exclusion/test skipping appears wrong and the sniff was throwing notices about an undefined constant in some versions. Turns out the `T_OPEN_USE_GROUP` token was only introduced into PHPCS in v2.6.0.
Includes additional unit test cases to test for more differentiation in syntax.
Removes test exclusion for this sniff on older PHPCS versions.
> Make the NewGroupUseDeclarationsSniff available in PHPCS < 2.6.0

- Sniffs/PHP/PregReplaceEModifierSniff.php
- Tests/Sniffs/PHP/PregReplaceEModifierSniffTest.php
- Tests/sniff-examples/preg_replace_e_modifier.php
(Sister-PR to #314 which fixed this for the Mbstring /e sniff)
> Improve how string tokens are dealt with in PregReplaceEModifierSniff.

- Sniffs/PHP/NewAnonymousClassesSniff.php
- Tests/Sniffs/PHP/NewAnonymousClassesSniffTest.php
This seemed like a quick fix to make.
In PHPCS 2.3.4 - 2.5.2, this sniff would throw an error about the `T_ANON_CLASS` constant not being defined (as it wasn't fully implemented properly in PHPCS until PHPCS 2.6.0).
Pre-PHPCS 2.3.4, the sniff was disregarded and the test skipped.
Includes additional test against false positives (test case was already in place, just not tested).
Removes test exclusion for this sniff on PHPCS <2.3.4.
> Backport the NewAnonymousClassesSniff for older PHPCS versions.

- Sniff.php
The `getMethodParameters()` method in the `PHPCompatibility_Sniff` class is a duplicate of an upstream method. The upstream method missed some type hints and didn't recognize nullable types.
The upstream PRs fixing this have now been merged with some very minor changes to the original merge proposal.
This PR syncs the duplicate method in the `PHPCompatibility_Sniff` class with the version as now merged upstream.
To maintain compatibility with PHPCS version lower than the current `dev-master`, the method cannot be removed until the minimum PHPCS version for the PHPCompatibility library has moved beyond the version in which these changes have been merged.
> Sync the `getMethodParameters()` method with the version now merged in PHPCS

- Sniffs/PHP/ConstantArraysUsingDefineSniff.php
- Tests/Sniffs/PHP/ConstantArraysUsingDefineSniffTest.php
- Tests/sniff-examples/constant_arrays_using_define.php
If a function call is made to set the value of a constant through `define()`, it depends on the function called whether or not the value passed to `define()` is one of the acceptable variable types, but determining what the variable type returned by the function call is (or could be), is outside of the scope of a static analyse tool.
So I believe, in that case we should not throw an error.
Also changes the `testVersion` for the `noViolation` / false positives test to `5.6` to prevet interference from the short array syntax sniff.
Fixes the issue reported in https://github.com/wpengine/phpcompat/issues/101
> Allow for array parameters in a function call used in a define.

- Sniffs/PHP/ForbiddenCallTimePassByReferenceSniff.php
- Tests/Sniffs/PHP/ForbiddenCallTimePassByReferenceSniffTest.php
- Tests/sniff-examples/call_time_pass_by_reference.php
While assigning to a variable within a function call or conditional might not be good practice, the reality is that there is plenty of userland code out there using it.
This PR should fix false positives for variables being assigned by reference within function calls.
It also should fix false positives for variables being compared by reference within function calls.
Refs:
http://php.net/manual/en/language.references.whatdo.php#language.references.whatdo.assign
http://php.net/manual/en/language.operators.assignment.php#40084
Fixes https://github.com/wimg/PHPCompatibility/issues/68#issuecomment-231366445
Fixes https://github.com/wimg/PHPCompatibility/issues/68#issuecomment-265814055
/cc @octalmage
> Fix false positives on assign-by-reference within function call in ForbiddenCallTimePassByReferenceSniff

- Sniffs/PHP/ForbiddenNamesAsDeclaredSniff.php
As this sniff is only relevant if the testVersion includes PHP 7.0+, we might as well bow out early if the `testVersion` does not include PHP 7+.
> Minor efficiency tweak to ForbiddenNamesAsDeclaredSniff

- Tests/BaseClass/FunctionsTest.php
- Tests/BaseClass/MethodTestFrame.php
- Tests/BaseSniffTest.php
- Tests/Sniffs/PHP/ForbiddenBreakContinueVariableArgumentsSniffTest.php
- Tests/Sniffs/PHP/ForbiddenCallTimePassByReferenceSniffTest.php
- Tests/Sniffs/PHP/InternalInterfacesSniffTest.php
- Tests/Sniffs/PHP/NewExecutionDirectivesSniffTest.php
- Tests/Sniffs/PHP/NewMagicMethodsSniffTest.php
- Tests/Sniffs/PHP/NewScalarReturnTypeDeclarationsSniffTest.php
- Tests/Sniffs/PHP/NonStaticMagicMethodsSniffTest.php
- Tests/Sniffs/PHP/RemovedAlternativePHPTagsUnitTest.php
- Tests/Sniffs/PHP/RemovedExtensionsSniffTest.php
- Tests/Sniffs/PHP/ValidIntegersSniffTest.php
Review the `setUp()` and `setUpBeforeClass()` methods if/when used in test classes.
* Make sure that if a `setUp()` or `setUpBeforeClass()` method is used, the parent is always called as well.
* Make sure that the `setUpBeforeClass()` method is always defined as `public static`.
* Make sure that the `setUp()` method is always defined as `protected` as it is in the parent.
* Make sure that these methods all have a docblock.
* Removed an unused `setUp()` method which only fell through to the parent.
> Review test fixtures

- Sniffs/PHP/NewKeywordsSniff.php
- Sniffs/PHP/NewNowdocSniff.php
- Tests/Sniffs/PHP/NewKeywordsSniffTest.php
- Tests/Sniffs/PHP/NewNowdocSniffTest.php
- Tests/sniff-examples/new_keywords.php
- Tests/sniff-examples/new_nowdoc.php
When reviewing test skip conditions I came across the `NewKeywords` sniff which skipped for Nowdoc recognition in PHP 5.2 which is where it is actually important that it *is* recognized.
Turned out this was not that difficult to backport.
* I've removed nowdoc checking from the NewKeywords sniff as the logic is quite distinct and unrelated to anything else in that sniff.
* And I've added a new sniff specifically targetting Nowdoc syntax.
N.B. The unit test failure is due to the issue reported in #330 and will be fixed once #323 has been merged.
> PHP 5.3: Detect NOWDOC syntax

- Sniff.php
- Sniffs/PHP/ForbiddenFunctionParametersWithSameNameSniff.php
- Sniffs/PHP/NewScalarTypeDeclarationsSniff.php
- Sniffs/PHP/ParameterShadowSuperGlobalsSniff.php
- Tests/Sniffs/PHP/ForbiddenFunctionParametersWithSameNameSniffTest.php
- Tests/Sniffs/PHP/NewScalarTypeDeclarationsSniffTest.php
- Tests/Sniffs/PHP/ParameterShadowSuperGlobalsSniffTest.php
- Tests/sniff-examples/forbidden_function_parameters_with_same_name.php
- Tests/sniff-examples/new_scalar_type_declarations.php
- Tests/sniff-examples/parameter_shadow_superglobals.php
* Adjusted the `getMethodParameters()` method to also allow `T_CLOSURE` tokens to be processed. The same change has been PR-ed and merged upstream https://github.com/squizlabs/PHP_CodeSniffer/pull/1293.
* Made sure that any calls from the PHPCompatibility sniffs to that method are made to the local version and not to the PHPCS native one.
* Register the `T_CLOSURE` token for three sniffs which should also be applied to anonymous functions.
* Added unit tests for the same.
The same fix as was made here, but then for the `NewNullableTypes` and `NewReturnTypes`sniffs is contained within #323.
N.B. The unit test failure is due to the issue reported in #330 and will be fixed once #323 has been merged.
> Allow for closures for a number of sniffs which only checked functions.

- Sniff.php
Fix infinite loop and out of memory error when class is not found.
While trying to check a legacy application for PHP compatibility issues, code sniffer terminated with out of memory error. This error is caused by infinite loop in Sniff.php.
Test code:
`<?php
$var = new
`
Creating a pull request with a fix.
> Fix infinite loop and out of memory error

- .travis.yml
The `installed_paths` variable has to point to a top-level `standards` directory, not to an individual standard.
Wasn't causing any problems for now, but should be fixed anyhow (as it will cause an issue with an upcoming PR).
> Travis script: Path fix for PHP 5.2

- Tests/Sniffs/PHP/TernaryOperatorsSniffTest.php
* Add `TEST_FILE` constant
* Use data provider & merge the test methods.
* Remove superfluous message text in the `noViolation` test(s).
* Test against a test version for the `noFalsePositives` test.
* Remove superfluous class property.
* Moved the `noFalsePositives` test down to be inline with most other test classes..
> Refactor the test file for the TernaryOperatorsSniff / ElvisOperator

- README.md
I.e. Git checkout to an arbitrary directory in combination with setting the `installed_path` config variable.
> :books: README: Add information on third installation method

- Tests/Sniffs/PHP/DeprecatedFunctionsSniffTest.php
- Tests/Sniffs/PHP/DeprecatedIniDirectivesSniffTest.php
- Tests/Sniffs/PHP/ForbiddenBreakContinueVariableArgumentsSniffTest.php
- Tests/Sniffs/PHP/ForbiddenNamesAsDeclaredSniffTest.php
- Tests/Sniffs/PHP/ForbiddenNamesAsInvokedFunctionsSniffTest.php
- Tests/Sniffs/PHP/NewClassesSniffTest.php
- Tests/Sniffs/PHP/NewExecutionDirectivesSniffTest.php
- Tests/Sniffs/PHP/NewFunctionParameterSniffTest.php
- Tests/Sniffs/PHP/NewFunctionsSniffTest.php
- Tests/Sniffs/PHP/NewIniDirectivesSniffTest.php
- Tests/Sniffs/PHP/NewInterfacesSniffTest.php
- Tests/Sniffs/PHP/NewLanguageConstructsSniffTest.php
- Tests/Sniffs/PHP/NewMagicMethodsSniffTest.php
- Tests/Sniffs/PHP/NewScalarTypeDeclarationsSniffTest.php
- Tests/Sniffs/PHP/RemovedAlternativePHPTagsUnitTest.php
- Tests/Sniffs/PHP/RemovedExtensionsSniffTest.php
- Tests/Sniffs/PHP/RemovedFunctionParameterSniffTest.php
- Tests/Sniffs/PHP/RemovedHashAlgorithmsSniffTest.php
- Tests/Sniffs/PHP/RequiredOptionalFunctionParameterSniffTest.php
- Tests/Sniffs/PHP/ValidIntegersSniffTest.php
* No need to rebuild the same error message every time when the test assertion is in a loop
* Use the most appropriate quote style - single vs double - for each error message
> Tests: minor efficiency tweaks related to the error messages.

- Tests/BaseSniffTest.php
(Edit: redid this PR to be a little more comprehensive than originally pulled)
* Minor efficiency tweak: use empty instead of count
* Minor information tweak: give some indication of the nr of errors/warnings
* Minor PHPUnit tweak: use `assertCount()` instead of replicating this logic
> BaseSniffTest: Minor tweaks

- Sniffs/PHP/NewExecutionDirectivesSniff.php
The list returned by `mb_list_encodings()` is not going to change during the PHPCS run, so we might as well cache it in a local static variable.
> NewExecutionDirectives sniff: minor efficiency tweak.

- Sniffs/PHP/PregReplaceEModifierSniff.php
- Tests/Sniffs/PHP/PregReplaceEModifierSniffTest.php
- Tests/sniff-examples/preg_replace_e_modifier.php
While IMHO people who use a quote character as a regex delimiter should ~~^%^&%*~~~~ (censored) _find another profession_, it **is** a valid delimiter.
This PR fixes the issue.
Fixes https://github.com/wpengine/phpcompat/issues/115
Originally reported: https://wordpress.org/support/topic/false-positive-preg_replace-e-modifier/
> PregReplaceEModifier: fix another false positive.

- Sniff.php
- Tests/BaseClass/FunctionsTest.php
Hoping that this will make the use of these functions slightly clearer.
Related to #142
> Document & test the `supportsBelow()`, `supportsAbove()` and `getTestVersion()` methods

- Sniffs/PHP/ForbiddenNamesSniff.php
- Tests/Sniffs/PHP/ForbiddenNamesSniffTest.php
Getting rid of one more test exclusion by adding the missing functionality.
> ForbiddenNames: backport forbidden names recognition for namespaces to PHP 5.2

- .travis.yml
- Tests/BaseClass/FunctionsTest.php
- Tests/BaseClass/MethodTestFrame.php
- Tests/BaseSniffTest.php
- Tests/TestcaseWrapper.php
- Tests/TestcaseWrapper_v6.php
- Tests/bootstrap.php
- phpcs.xml
- phpunit-travis.xml
- phpunit.xml
Since today Travis uses PHPUnit 6.x for PHP 7+. The unit tests were not compatible with this and failing because of it.
These relatively minor changes fix that and makes the tests compatible with both PHPUnit < 6 as well as 6+.
Ref: https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-6.0.0
----
**[Edit]** For argument's sake and to document why I'm proposing the solution pulled here:
The alternative to the solution proposed here, would be to add PHPUnit to the `composer.json` file.
There are a couple of arguments against this though:
1. It would increase the build time even more, while I've been trying to bring it down.
2. We would need different PHPUnit versions for PHP 5.2-5.3 (PHPUnit 4.x) and PHP 5.4-PHP7.1 (PHPUnit 5.x) and PHP 7.2/nightly (PHPUnit 6.x) …
> Make the unit tests compatible with PHPUnit v6

- README.md
- Sniff.php
- Tests/BaseClass/FunctionsTest.php
I've improved the testVersion setting so that is now possible to specify partial ranges.
For example:
* "-5.6" means all versions up to PHP 5.6
* "7.0-" means all versions above PHP 7.0
Unit tests and documentation updated.
> Add partial-range support to testVersion parameter

- Tests/BaseClass/DoesFunctionCallHaveParametersTest.php
- Tests/BaseClass/GetFQClassNameFromDoubleColonTokenTest.php
- Tests/BaseClass/GetFQClassNameFromNewTokenTest.php
- Tests/BaseClass/GetFQExtendedClassNameTest.php
- Tests/BaseClass/GetFunctionParameterCountTest.php
- Tests/BaseClass/GetFunctionParametersTest.php
- Tests/BaseClass/MethodTestFrame.php
- Tests/BaseClass/TokenHasScopeTest.php
- Tests/sniff-examples/utility-functions/does_function_call_have_parameters.php
- Tests/sniff-examples/utility-functions/get_fqclassname_from_double_colon_token.php
- Tests/sniff-examples/utility-functions/get_fqclassname_from_new_token.php
- Tests/sniff-examples/utility-functions/get_fqextended_classname.php
- Tests/sniff-examples/utility-functions/get_function_parameter_count.php
- Tests/sniff-examples/utility-functions/get_function_parameters.php
- Tests/sniff-examples/utility-functions/token_has_scope.php
Most utility function tests were currently based on an **exact** token position in the test file.
This made adding/changing unit tests unnecessarily complicated and made the tests very error-prone.
I've now added a helper function to the `MethodTestFrame` class to help get the token position being targeted for a unit test based on comments in the test case file.
The principle of this is similar to how these type of functions are being tested in PHPCS upstream.
This will make these unit tests more stable, more reliable and a **lot** easier to add to/adjust.
Notes:
* Includes one extra unit test case for `testGetFQClassNameFromNewToken()`.
* Includes two extra unit test cases for `testGetFQExtendedClassName()`.
* The test for the `getFunctionCallParameterCount()` function has been split off …
> Tests: stabilize utility function unit tests

- Sniffs/PHP/CaseSensitiveKeywordsSniff.php
- Tests/Sniffs/PHP/CaseSensitiveKeywordsSniffTest.php
- Tests/sniff-examples/case_sensitive_keywords.php
New sniff to detect issues for the below:
> Prior to PHP 5.5, cases existed where the self, parent, and static keywords were treated in a case sensitive fashion. These have now been resolved, and these keywords are always handled case insensitively: SELF::CONSTANT is now treated identically to self::CONSTANT.
Ref: http://php.net/manual/en/migration55.incompatible.php#migration55.incompatible.self-parent-static
> Pre-PHP 5.5: Add sniff to detect use of non-lowercase `self`, `static` and `parent` keywords

- Sniffs/PHP/NewFunctionsSniff.php
- Tests/Sniffs/PHP/NewFunctionsSniffTest.php
- Tests/sniff-examples/new_functions.php
Refs:
* https://wiki.php.net/rfc/socket_getaddrinfo
* https://github.com/php/php-src/pull/2078
> PHP 7.2: Add sniffing for new socket related functions.

- Sniffs/PHP/DeprecatedIniDirectivesSniff.php
- Tests/Sniffs/PHP/DeprecatedIniDirectivesSniffTest.php
- Tests/sniff-examples/deprecated_ini_directives.php
Refs:
* https://wiki.php.net/rfc/deprecations_php_7_2#mbstringfunc_overload
* https://github.com/php/php-src/commit/a8239ff23272a346f6cb8f01bff384f94a3bcb79
Related to #336
> PHP 7.2: Add sniffing for deprecated mbstring.func_overload ini directive

- Sniffs/PHP/NewConstVisibilitySniff.php
- Tests/Sniffs/PHP/NewConstVisibilitySniffTest.php
- Tests/sniff-examples/new_const_visibility.php
> NewConstVisibilitySniff: Add support for anonymous classes

- Tests/Sniffs/PHP/NewMagicMethodsSniffTest.php
- Tests/sniff-examples/new_magic_methods.php
Couldn't be added previously as they would conflict with the reserved function names (double underscore prefix) sniff.
> NewMagicMethods: add tests against false positives

- Sniff.php
- Sniffs/PHP/ForbiddenClosureUseVariableNamesSniff.php
- Sniffs/PHP/ParameterShadowSuperGlobalsSniff.php
- Tests/Sniffs/PHP/ForbiddenClosureUseVariableNamesSniffTest.php
- Tests/sniff-examples/forbidden_closure_use_variable_names.php
> Lexically bound variables cannot reuse names
>
> Variables bound to a closure via the use construct cannot use the same name as any superglobals, $this, or any parameter. For example, all of these function definition will result in a fatal error: ...
Ref: http://php.net/manual/en/migration71.incompatible.php#migration71.incompatible.lexical-names
To sniff for this a new sniff has been added.
Notes:
* The `$superglobals` array which previously was defined as a property of the `ParameterShadowSuperGlobalsSniff` has been moved up to the parent class `PHPCompatibility_Sniff` so it can be used by this sniff as well without duplicating code.
Sniff includes extensive unit tests.
Closes #374
> PHP 7.1: New sniff to check for forbidden variable names in closure use statements

- Sniffs/PHP/DeprecatedFunctionsSniff.php
- Tests/Sniffs/PHP/DeprecatedFunctionsSniffTest.php
- Tests/sniff-examples/deprecated_functions.php
Refs:
* https://wiki.php.net/rfc/deprecate-png-jpeg-2wbmp
* https://github.com/php/php-src/pull/2164 (merged)
> PHP 7.2: Add detection for ext/gd deprecated functions

- Sniff.php
- Sniffs/PHP/RemovedGlobalVariablesSniff.php
- Tests/BaseClass/IsClassPropertyTest.php
- Tests/Sniffs/PHP/RemovedGlobalVariablesSniffTest.php
- Tests/sniff-examples/removed_global_variables.php
- Tests/sniff-examples/utility-functions/is_class_property.php
Prevent false positives for class properties named after removed PHP superglobals in PHPCS 2.4.0-2.7.1.
* Pre-PHPCS 2.4.0, the `T_ANON_CLASS` token was recognized as T_CLASS and supported as such which works perfectly for our purposes.
* PHPCS 2.4.0 - 2.7.1 supported the T_ANON_CLASS *token*, but did not consistently take it into account in all the relevant methods, like `getMemberProperties()`.
* This was finally fixed in PHPCS 2.8.0.
As there is another upcoming sniff which will run into the same issue, I've abstracted the code to determine whether a variable is a class property to a method in the `PHPCompatibility_Sniff`.
Includes unit tests both for anonymous class support in the RemovedGlobalVariable sniff, as well as for the new utility method.
Fixes #333 
One of several PRs to fix …
> Issue #333: add cross-version support for anonymous classes to the RemovedGlobalVariable sniff

- Sniff.php
- Sniffs/PHP/InternalInterfacesSniff.php
- Sniffs/PHP/NewInterfacesSniff.php
- Tests/Sniffs/PHP/InternalInterfacesSniffTest.php
- Tests/Sniffs/PHP/NewInterfacesSniffTest.php
- Tests/sniff-examples/internal_interfaces.php
- Tests/sniff-examples/new_interfaces.php
While there have no new interfaces been introduced since the introduction of anonymous classes, this will make the sniff forward compatible for when those are introduced.
For InternalInterfaces, the change is already relevant.
As there are now more tests, largely reworked the InternalInterfaces unit tests to data providers.
In a similar vain, reworked the `testUnsupportedMethods` test in the `NewInterfaces` unit test file to use a data provider.
> Add anonymous class support in the InternalInterfaces and NewInterfaces sniffs.

- Sniffs/PHP/NewScalarTypeDeclarationsSniff.php
- Tests/Sniffs/PHP/NewScalarTypeDeclarationsSniffTest.php
- Tests/sniff-examples/new_scalar_type_declarations.php
Use of scalar type hints was not reported if the type hint was nullable. Case of one sniff hiding behind another.
> NewScalarTypeDeclarations: Allow the sniff to report even when the type hint is nullable.

- Sniff.php
- Sniffs/PHP/NewClassesSniff.php
- Tests/Sniffs/PHP/NewClassesSniffTest.php
- Tests/sniff-examples/new_classes.php
This issue does not come into play (yet) as no new classes were added since the introduction of anonymous classes, but would start playing up once they will be.
> NewClassesSniff: Detect anonymous classes extending new classes.

- Sniffs/PHP/NewArrayStringDereferencingSniff.php
- Tests/Sniffs/PHP/NewArrayStringDereferencingSniffTest.php
- Tests/Sniffs/PHP/NewFunctionArrayDereferencingSniffTest.php
- Tests/sniff-examples/new_array_string_dereferencing.php
New sniff to detect issues for the below:
> Array and string literals can now be dereferenced directly to access individual elements and characters
Ref: http://php.net/manual/en/migration55.new-features.php#migration55.new-features.const-dereferencing
> PHP 5.5: New sniff to detect array and string literal dereferencing

- .travis.yml
For the build failures, the coveralls version is irrelevant, while the PHPCS version gives you a clue on where to start debugging.
Previously the PHPCS version would - depending on screen size - often be hidden behind the run time. Now it won't anymore.
Before:
After:
> :rocket: Travis: make it easier to see on which PHPCS version a build fails

- Tests/Sniffs/PHP/ForbiddenClosureUseVariableNamesSniffTest.php
- Tests/sniff-examples/forbidden_closure_use_variable_names.2.php
- Tests/sniff-examples/forbidden_closure_use_variable_names.php
The PHPCS Tokenizer has a bug in version 2.5.1 which causes an infinite loop with undefined index notices.
This fix skips the two tests which are affected by this bug when the tests are run on PHPCS 2.5.1 to prevent this.
Commit https://github.com/squizlabs/PHP_CodeSniffer/commit/9a70ae2d4c0a0bd0f48b965202158defb828cadd fixed the issue. The bug only exists in PHPCS 2.5.1.
The bug seems to only affect this sniff when the sniff is run from an IDE during live coding and/or when the file has parse errors.
The `README` for PHPCompatibility already commends using PHPCS 2.6+, so hopefully this bug will rarely rear its head for end-users.
> ForbiddenClosureUseVariable Tests: prevent infinite loop with PHPCS 2.5.1

- README.md
This option is available since PHPCS 2.6.0.
Ref: https://github.com/squizlabs/PHP_CodeSniffer/pull/899
> :books: README: Add information about setting the `installed_path` via the ruleset

- Sniffs/PHP/ForbiddenNamesAsDeclaredSniff.php
- Tests/Sniffs/PHP/ForbiddenNamesAsDeclaredSniffTest.php
Notes:
* Allows for keywords to be soft reserved in earlier PHP version only to become hard reserved later.
* Depending on the `testVersion` set will throw a warning for _soft_ reserved keywords or an error for _hard_ reserved keywords.
* Will compose the error message to contain information on both the soft reservation as well as the hard reservation if a keyword moved between the lists across versions.
By the time one of the soft reserved words becomes a hard reserved word, all we'd need to do is to add a new unit test method with dataprovider (apart from adding the right versions to the lists of course).
Closes #370 (superseded)
> ForbiddenNamesAsDeclared: lower the error level to warning for soft reserved words

- Tests/BaseClass/FunctionsTest.php
* Some tests for ranges containing white-space.
* Some tests for invalid ranges.
> Adding some more unit tests for PHPCompatibility_Sniff::getTestVersion()

- Sniffs/PHP/NewMagicClassConstantSniff.php
- Tests/Sniffs/PHP/NewMagicClassConstantSniffTest.php
- Tests/sniff-examples/new_magic_class_constant.php
Includes unit tests + two additional checks against invalid use of the magic `::class` constant.
Ref: http://php.net/manual/en/migration55.new-features.php#migration55.new-features.class-name
Ref: example #3 http://php.net/manual/en/language.oop5.constants.php
Fixes #364
> PHP 5.5: add new sniff to detect `::class` magic constant

- Sniffs/PHP/NewUseConstFunctionSniff.php
- Tests/Sniffs/PHP/NewUseConstFunctionSniffTest.php
- Tests/sniff-examples/new_use_const_function.php
> The use operator has been extended to support importing functions and constants in addition to classes. This is achieved via the use function and use const constructs, respectively.
Refs:
* http://php.net/manual/en/migration56.new-features.php#migration56.new-features.use
* https://wiki.php.net/rfc/use_function
.. as I'm not sure if it is a valid syntax in the first place:
```php
use const Baz, function Foo\Bar as bar;
```
> PHP 5.6: Add new sniff to detect importing const and function via a use statement

- Sniff.php
- Sniffs/PHP/NewNullableTypesSniff.php
- Sniffs/PHP/NewScalarTypeDeclarationsSniff.php
- Sniffs/PHP/ParameterShadowSuperGlobalsSniff.php
And start using the new `token` index for more precise error line indication in the case of multi-line function declarations.
> `getMethodParameters()`: Sync in upstream changes.

- Sniffs/PHP/ConstantArraysUsingConstSniff.php
- Tests/Sniffs/PHP/ConstantArraysUsingConstSniffTest.php
- Tests/sniff-examples/constant_arrays_using_const.php
> It is also now possible to define a constant array using the const keyword:
Ref: http://php.net/manual/en/migration56.new-features.php#migration56.new-features.const-scalar-exprs
Includes unit tests
> PHP 5.6: New sniff to detect constant arrays defined using the `const` keyword

- Tests/Sniffs/PHP/NewMagicMethodsSniffTest.php
- Tests/sniff-examples/new_magic_methods.php
No new magic methods were introduced since the introduction of anonymous classes, but the sniff does allow for them and is now unit tested for it too.
> Add unit tests for anonymous classes to the NewMagicMethodsSniff

- Sniff.php
- Sniffs/PHP/NewHeredocInitializeSniff.php
- Tests/BaseClass/IsClassConstantTest.php
- Tests/Sniffs/PHP/NewHeredocInitializeSniffTest.php
- Tests/sniff-examples/new_heredoc_initialize.php
- Tests/sniff-examples/utility-functions/is_class_constant.php
> As of PHP 5.3.0, it's possible to initialize static variables and class properties/constants using the Heredoc syntax
Ref:
* http://php.net/manual/en/language.types.string.php#language.types.string.syntax.heredoc
* http://php.net/manual/en/migration53.new-features.php
This PR adds a new sniff to detect this.
Fixes #51 
-----
[Edit]:
I have updated this PR since #393 was merged to use the new `PHPCompatibility_Sniff::isClassProperty()` method.
This PR now includes addition of two more new utility functions `PHPCompatibility_Sniff::isClassConstant()` and `PHPCompatibility_Sniff::validDirectScope()`.
The `PHPCompatibility_Sniff::isClassConstant()` is also needed by some other PRs which is why it was turned into a utility method.
The …
> PHP 5.3: Add new sniff to detect heredoc initialization

- Sniffs/PHP/NewClosureSniff.php
- Tests/Sniffs/PHP/NewClosureSniffTest.php
- Tests/sniff-examples/new_closure.php
Closures were introduced in PHP 5.3.
However, until PHP 5.4, they could not be declared as `static`, nor could they use the `$this` variable when declared within a class context.
Ref: http://php.net/manual/en/functions.anonymous.php
This will now be sniffed for.
Additionally this PR contains two extra checks for incorrect/unsupported usage of the `$this` variable in closures for PHP 5.4 and higher:
* usage of `$this` in static closures is not supported by PHP
* usage of `$this` in closures outside of a class context is not supported by PHP
Related #24
> NewClosures sniff: add checking for new features added in PHP 5.4

- Sniffs/PHP/ForbiddenNamesSniff.php
- Tests/sniff-examples/forbidden_names_correct_usage.php
Bow out earlier, no need for the rest of the logic if it is an anonymous class.
Includes unit test.
> ForbiddenNames: minor tweak to the anonymous classes skip code.

- Sniff.php
- Sniffs/PHP/NewInterfacesSniff.php
- Tests/Sniffs/PHP/NewInterfacesSniffTest.php
- Tests/sniff-examples/new_interfaces.php
Notes:
* Adds a new method to the `PHPCompatibility_Sniff` class to retrieve just the typehints from a function declaration.
* Adds the logic to the sniff to detect usage of new interfaces as type hints.
> NewInterfacesSniff: Detect new interfaces when used as type hints.

- Sniffs/PHP/NewClassesSniff.php
- Tests/Sniffs/PHP/NewClassesSniffTest.php
- Tests/sniff-examples/new_classes.php
* Add Exception classes to the new classes sniff to be sniffed for using all the existing checks
* Add checking for use of new Exception classes in catch statements. Includes support for multi-catch statements (PHP 7.1)
Includes extensive unit tests.
> NewClasses sniff: Detect new Exception classes

- .travis.yml
- README.md
As PHPCS 3.0 has been released and become the `master` branch, the builds will fail.
This PR changes the "high" branch to build against to `2.9.x-dev`/`2.9` which is the patch branch for the 2.x series and limits the "last stable" build to the 2.x series.
It also adds a note to the Readme annotating that PHPCS 3.x is currently not (yet) supported.
> Fix the build.

- Sniffs/PHP/ForbiddenNamesSniff.php
- Tests/Sniffs/PHP/ForbiddenNamesSniffTest.php
- Tests/sniff-examples/forbidden_names_correct_usage.php
- Tests/sniff-examples/forbidden_names_correct_usage_use.php
The `ForbiddenNames` sniff should report on use of reserved keywords in `use const ...` and `use function ..` statements independently of the `testVersion` which was set.
Reporting on the use of those constructs for PHP versions in which they are not available is covered by the separate `NewUseConstFunction` sniff.
> ForbiddenNames: always report on `use` statements using `const` or `function`

- Sniffs/PHP/NewConstVisibilitySniff.php
- Tests/Sniffs/PHP/NewConstVisibilitySniffTest.php
- Tests/sniff-examples/new_const_visibility.php
_Part of a review to see which sniffs would benefit from using the new `isClassProperty()`  and `isClassConstant()` methods as introduced in #391 and #393._
* Use the new `isClassConstant()` utility method as introduced in #391.
* Bow out early if not testing for PHP < 7.1 (was originally done later as some "debug" checks were slated to go in and didn't)
> Minor refactor of the `NewConstVisibility` sniff.

- Sniffs/PHP/NewKeywordsSniff.php
- Tests/Sniffs/PHP/NewKeywordsSniffTest.php
- Tests/sniff-examples/new_keywords.php
_Part of a review to see which sniffs would benefit from using the new `isClassProperty()`  and `isClassConstant()` methods as introduced in #391 and #393._
This gives more precise results on when to throw an error for the `const` keyword.
Changes the `condition` index in the version array from an array of token scopes to a call back function. As `const` is so far the only one with a condition, this has no impact on the other keywords.
> NewKeywords sniff: use the new `isClassConstant()` utility method.

- Sniff.php
- Tests/BaseClass/FunctionsTest.php
The overwriting of `$testVersion` within the function created a second entry with `array(null,null)` as value. This in effect broke the function result caching.
This resulted in the very first sniff calling the `supportsBelow()` method to report an error, but any subsequent calls to `supportBelow()` - even from the same sniff - would fail causing errors not to be reported.
Includes unit test to safeguard against this in the future.
Related to #371 and #142. /cc @MarkMaldaba
> :fire: Hot fix: using unbounded ranges in `testVersion` only showed first error

- Tests/BaseClass/IsClassPropertyTest.php
- Tests/Sniffs/PHP/NewHeredocInitializeSniffTest.php
- Tests/Sniffs/PHP/NewMagicMethodsSniffTest.php
- Tests/Sniffs/PHP/NonStaticMagicMethodsSniffTest.php
Traits are only recognized when either PHP > 5.3 or PHPCS > 2.3.4.
Skip the tests for the correct version and add proper skip annotation.
> Tests: Skip tests involving traits in combi with the right PHPCS version

- Sniff.php
Anonymous classes which extend a "new" class would not be recognized correctly in combination with PHPCS < 2.8.0 and > 2.4.0.
To fix this we need to emulate the upstream `findExtendedClassName()` method.
Fixes #334
> NewClasses sniff: Improve support for anonymous classes.

- Sniff.php
- Sniffs/PHP/DeprecatedPHP4StyleConstructorsSniff.php
- Sniffs/PHP/ForbiddenCallTimePassByReferenceSniff.php
- Sniffs/PHP/ForbiddenClosureUseVariableNamesSniff.php
- Sniffs/PHP/ForbiddenEmptyListAssignmentSniff.php
- Sniffs/PHP/ForbiddenFunctionParametersWithSameNameSniff.php
- Sniffs/PHP/ForbiddenNamesAsDeclaredSniff.php
- Sniffs/PHP/ForbiddenNamesAsInvokedFunctionsSniff.php
- Sniffs/PHP/ForbiddenSwitchWithMultipleDefaultBlocksSniff.php
- Sniffs/PHP/NewClosureSniff.php
- Sniffs/PHP/NewExecutionDirectivesSniff.php
- Sniffs/PHP/NewFunctionArrayDereferencingSniff.php
- Sniffs/PHP/NewHeredocInitializeSniff.php
- Sniffs/PHP/NewInterfacesSniff.php
- Sniffs/PHP/NewLanguageConstructsSniff.php
- Sniffs/PHP/NewScalarTypeDeclarationsSniff.php
- Sniffs/PHP/NonStaticMagicMethodsSniff.php
- Sniffs/PHP/PregReplaceEModifierSniff.php
- Sniffs/PHP/RemovedFunctionParametersSniff.php
* minor strict checking improvements
* minor code simplifications
* make sure that the output of `findNext()`/`findPrevious()` is always checked against `false` before use
* one `break` for efficiency
* remove one unused variable
* minor whitespace fixes
* minor documentation fixes
Partially based on Scrutinizer feedback, partially little things collected along the way which didn't fit into any other PR.
> Various small fixes

- CONTRIBUTING.md
- README.md
- composer.json
While I'm nearly ready with the PHPCS 3.x compatible version, it cannot be pulled/released yet until a new stable version of PHPCS 3 has been released as the latest stable version contains a number of insurmountable bugs.
So, for now, make it explicit that PHPCS 3.x is not (yet) supported.
These changes will be reverted from within the PHPCS 3.x compat branch.
* Also: in `CONTRIBUTING` PHPUnit 3.x was referenced, while PHPCS itself recommends PHPUnit 4 and this standard can deal with PHPUnit 4, 5, 6.
> (temporarily) Make it very clear that PHPCS 3.x is not (yet) supported

- README.md
I noticed the new `versionEye` check in the build tests and figured adding a badge for it would be useful (even though at this moment it will say "out of date" because of PHPCS 3.x).
Also:
* The license badge was not linking to a license (will be fixed when both this PR as well as #447 will be merged)
* There was no Scrutinizer badge for code quality, so I've added that too.
* VersionEye has a sister-site PHPEye which provides useful info about the PHP versions against which a repo is being tested. Figured that would be useful to show as well.
> :books: Add some more badges and reorganize their display order.

- Sniff.php
Turns out the bug where scoped `use` statements did not have scope, existed longer than previously checked for.
> Fix PHPCS 2.0-2.2 compatibility for the `inUseScope()` method.

- Sniff.php
Any sniff using this function in combination with PHPCS 1.5.x < 1.5.6 and PHP < 5.6 would break on the `T_ELLIPSIS` token not being defined.
> Fix PHPCS 1.5.x compatibility for the `getMethodParameters()` method.

- Sniffs/PHP/NewExecutionDirectivesSniff.php
Turns out the parenthesis bug with `declare` existed longer than previously checked for.
> NewExecutionDirectives: Fix compatibility with PHPCS 2.0-2.3.3

- .travis.yml
- Tests/Sniffs/PHP/DefaultTimezoneRequiredSniffTest.php
- Tests/Sniffs/PHP/NewKeywordsSniffTest.php
- composer.json
HHVM currently fails to run the unit tests when using the default PHPUnit version from the Travis image, so require a set PHPUnit version through Composer and running the unit tests using that PHPUnit version instead.
Also:
* Simplified the conditional for Coveralls and only have it as a dev requirement when run via Travis. For "normal" unit test runs, Coveralls is not needed.
* HHVM: skip select unit tests for HHVM (2 tests to be precise out of thousands, so that's not too bad).
Fixes https://github.com/wimg/PHPCompatibility/pull/449#issuecomment-301343035
> Test builds against HHVM

- Sniffs/PHP/ForbiddenBreakContinueVariableArgumentsSniff.php
- Tests/Sniffs/PHP/ForbiddenBreakContinueVariableArgumentsSniffTest.php
- Tests/sniff-examples/forbidden_break_continue_variable_argument.php
Fixes #460 (at least it should).
Even though I have not been able to reproduce the issue, even with the code sample in the test file, this minor change should fix the issue even so.
----
~~NOTE: DO NOT MERGE AT THIS MOMENT! Rebased against the composer fix branch for testing.~~ Re-rebased on `master`, should be ok to merge now.
> Fix break/continue variable argument bug with closing tag after break/continue

- Sniffs/PHP/DeprecatedNewReferenceSniff.php
- Tests/Sniffs/PHP/DeprecatedNewReferenceSniffTest.php
- Tests/sniff-examples/deprecated_new_reference.php
The sniff was presuming a certain code style, while an assignment might be aligned differently depending on the project code style.
This fixes that.
> DeprecatedNewReference sniff: minor improvement for accuracy

- Sniffs/PHP/NewKeywordsSniff.php
- Tests/Sniffs/PHP/NewKeywordsSniffTest.php
- Tests/sniff-examples/new_keywords.php
`yield from` turns out to be tokenized as a distinct new token `T_YIELD_FROM` which was previously not accounted for in PHPCompatibility.
Some additional logic needed to be added to deal with distinguishing between the `yield` and `yield from` keywords as we now have to deal with overlapping and multi-token keywords.
Fixes #476
> PHP 7.0/NewKeywordsSniff: sniff for `yield from`.

- bin/generate-forbidden-names-test-files
It always seemed kind of hidden and misplaced in the `sniff-examples` directory.
> Move Forbidden names test file generator script to `/bin` directory

- PHPCompatibility/Tests/BaseClass/FunctionsTest.php
The default file encoding changes in PHPCS 3.0 to utf-8. This test file was not correctly encoded to be compatible with that.
> Fix file encoding

- PHPCompatibility/Tests/BaseClass/FunctionsTest.php
While running some tests with PHPCS 3.x, I noticed that the `testVersion` wasn't always being reset properly after each test in this file. This fixes that.
> Fix bleed through in unit tests

- README.md
Any linting of XML files will usually flag these extra spaces before `/>` as redundant, so remove these from the examples in the readme.
> Docs: Remove trailing space in empty XML tag

- PHPCSAliases.php
… in the auto loader to allow for PHP cross-version compatibility difference.
> Minor fix: better to do the class name comparison in a case insensitive manner

- PHPCSAliases.php
`PHP_CodeSniffer_Sniff` is an interface, not a class, so should be checked for as such.
This will prevent `Warning: Cannot declare interface \PHP_CodeSniffer_Sniff, because the name is already in use` errors when other external standards use the same methodology to create cross-version compatibility.
> PHPCS 3.x compat: create the aliases correctly

- .travis.yml
No need to do it for each build.
> Build: only lint the PHP files once per PHP version.

- .travis.yml
- composer.json
N.B.: Since this PR was originally pulled, two more travis script related commits have been added. The original PR description only deals with the first commit. The others are outlined in a follow on comment.
--------
Build against various PHPCS versions, not just the oldest and most recent.
As discussed a while back:
As PHPCompatibility is supposed to support all PHPCS versions from 1.5.x upwards to the current version, it would be good to run the build tests against interim versions of PHPCS as well to make sure it actually does.
Over the last few months I've been running tests around this and have send in a number of PRs to solve issues with:
* sniffs which (silently) did not support all PHPCS versions
* test exclusions relating to specific/earlier PHPCS versions
These have all been …
> Build: Mix up the build matrix and composer specificity

- .gitattributes
- .github/CONTRIBUTING.md
This PR adds a `.gitattributes` file to keep the archives GH creates of the repo clean of development related files.
People using Composer can still get these files in their setup if they really want to, by using `--prefer-source`.
Refs:
* [Reddit: I don't need your tests in my production](https://www.reddit.com/r/PHP/comments/2jzp6k/i_dont_need_your_tests_in_my_production)
* [Blog: I don't need your tests in my production](https://blog.madewithlove.be/post/gitattributes/)
This PR presumes that #483 and #493 will be merged.
> Add a .gitattributes file

- .github/CONTRIBUTING.md
- CHANGELOG.md
- README.md
- composer.json
Readme:
* Updated install instructions
* Updated (minimum) requirements information for running PHPCompatibility
* Added a warning section about upgrading to PHPCompatibility 8.0.0
Contributing:
* Updated instructions on how to run the unit tests
* Adjust (minimum) requirements information for new features
Changelog:
* Extensive upgrade instructions
* Note about the changed version numbering
Composer:
* Up the minimum required PHPCS version to 3.0.2 to benefit from one more fix to the autoloading
Also:
* Use spaces not tabs for the code samples in Readme/Contributing/Changelogs.
* Added some more empty lines here and there to improve readability in Readme/Contributing.
Fixes #472
Fixes #306
All: testing with the new install instructions & testing the upgrade instructions is highly …
> Update readme, contributing  and changelog for v 8.0.0

- PHPCompatibility/Sniffs/PHP/DeprecatedFunctionsSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/DeprecatedFunctionsSniffTest.php
- PHPCompatibility/Tests/sniff-examples/deprecated_functions.php
PHP 7.2: `create_function()` is now a deprecated function
Refs:
* https://wiki.php.net/rfc/deprecations_php_7_2#create_function
* https://github.com/php/php-src/commit/eaeecc523b665cfa856a376b9c55ca7fc9b7b596
----
PHP 7.2: `each()` is now a deprecated function
Refs:
* https://wiki.php.net/rfc/deprecations_php_7_2#each
* https://github.com/php/php-src/commit/06a034016280435feb80eea4d674ca5688ab4c06
----
PHP 7.2: `gmp_random()` is now a deprecated function
Refs:
* https://wiki.php.net/rfc/deprecations_php_7_2#gmp_random
* https://github.com/php/php-src/commit/fbeb900be4948d9a1bdc3e139937777534cc27e4
> PHP 7.2: deprecated functions

- PHPCompatibility/Sniffs/PHP/DeprecatedIniDirectivesSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/DeprecatedIniDirectivesSniffTest.php
- PHPCompatibility/Tests/sniff-examples/deprecated_ini_directives.php
PHP 7.2: `track_errors` ini directive is now deprecated
Slated to be removed in PHP 8.0.
Refs:
* https://wiki.php.net/rfc/deprecations_php_7_2?s[]=track_errors#php_errormsg
* php/php-src@c61daf4
* php/php-src@47a1ab3
----
PHP 7.2: `sql.safe_mode` ini directive has been removed
Refs:
* https://github.com/php/php-src/blob/PHP-7.2/UPGRADING#L333
* php/php-src@197051f
> PHP 7.2: deprecated/removed ini directives

- PHPCompatibility/Sniffs/PHP/ForbiddenNamesAsDeclaredSniff.php
- PHPCompatibility/Sniffs/PHP/NewReturnTypeDeclarationsSniff.php
- PHPCompatibility/Sniffs/PHP/NewScalarTypeDeclarationsSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/ForbiddenNamesAsDeclaredSniffTest.php
- PHPCompatibility/Tests/Sniffs/PHP/NewReturnTypeDeclarationsSniffTest.php
- PHPCompatibility/Tests/Sniffs/PHP/NewScalarTypeDeclarationsSniffTest.php
- PHPCompatibility/Tests/sniff-examples/new_return_type_declarations.php
- PHPCompatibility/Tests/sniff-examples/new_scalar_type_declarations.php
`object` was already a soft reserved keyword as of PHP 7.0.
As of PHP 7.2, it:
* can be used as a parameter type hint
* can be used as a return type hint
* has become a "hard" reserved keyword.
References:
* https://wiki.php.net/rfc/object-typehint
* https://github.com/php/php-src/pull/2080
> PHP 7.2: `object` can now be use as a typehint

- PHPCompatibility/Sniffs/PHP/NewTypeCastsSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/NewTypeCastsSniffTest.php
- PHPCompatibility/Tests/sniff-examples/new_type_casts.php
Addresses sniffing for the `(unset)` and `(binary)` type casts as these were added after PHP 4.
This is a sister-PR to the new `DeprecatedTypeCasts` sniff which will detect `(unset)` being deprecated as of PHP 7.2 / PR #498.
Refs:
* http://php.net/manual/en/language.types.type-juggling.php#language.types.typecasting
> :sparkles: New `NewTypeCasts` sniff

- PHPCompatibility/Sniffs/PHP/DeprecatedTypeCastsSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/DeprecatedTypeCastsSniffTest.php
- PHPCompatibility/Tests/sniff-examples/deprecated_type_casts.php
Addresses sniffing for the `(unset)` type cast which will be deprecated in PHP 7.2.
This is a sister-PR to the new `NewTypeCasts` sniff / PR #497.
Refs:
* http://php.net/manual/en/language.types.type-juggling.php#language.types.typecasting
* https://wiki.php.net/rfc/deprecations_php_7_2#unset_cast
* https://github.com/php/php-src/commit/7a73c5f6bba386e0d82dd467e9dacceb10b851e3
> :sparkles: New `DeprecatedTypeCasts` sniff

- PHPCSAliases.php
When the `installed_paths` variable is set via the ruleset and not using `--config-set` on the command line, PHPCS has trouble loading arbitrary files for external rulesets, like the main `Sniff` class.
Discovered in the WordPress Coding Standards, but the same issue applies to PHPCompatibility as well.
See: WordPress-Coding-Standards/WordPress-Coding-Standards/issues/1087
The underlying issue has been reported upstream https://github.com/squizlabs/PHP_CodeSniffer/issues/1591 and should be fixed there.
In the mean time, this will fix it for the time being.
I believe that this fix warrants a release of 8.0.1 soon after.
> Hotfix: temporary plaster to fix upstream issue

- PHPCompatibility/Sniff.php
- PHPCompatibility/Sniffs/PHP/NewReturnTypeDeclarationsSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/NewReturnTypeDeclarationsSniffTest.php
- PHPCompatibility/Tests/sniff-examples/new_return_type_declarations.php
* `parent` while undocumented in http://php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration.types, is actually accepted as a valid return type declaration - see: https://3v4l.org/lOpPS
* `iterable` was added in PHP 7.1.
Refs:
- http://php.net/manual/en/language.types.iterable.php
- https://wiki.php.net/rfc/iterable
> NewReturnTypeDeclarations: add two missing valid types

- PHPCompatibility/Sniffs/PHP/NewGroupUseDeclarationsSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/NewGroupUseDeclarationsSniffTest.php
- PHPCompatibility/Tests/sniff-examples/new_group_use_declarations.php
Refs:
* https://github.com/php/php-src/blob/PHP-7.2/UPGRADING#L110
* https://wiki.php.net/rfc/list-syntax-trailing-commas - out of this RFC only the group use trailing comma's has been implemented.
* https://github.com/php/php-src/commit/12300f465e5bed1fa7d0bc445aef68b6a2753c3b
> PHP 7.2 / NewGroupUseDeclarations: add sniffing for trailing comma's

- PHPCompatibility/Sniff.php
- PHPCompatibility/Tests/BaseClass/GetFQExtendedClassNameTest.php
- PHPCompatibility/Tests/sniff-examples/utility-functions/get_fqextended_classname.php
Synced in the changes as were just merged from squizlabs/PHP_CodeSniffer/pull/1473
This allows the method to also detect the "Extended Classname" for interfaces extending other interfaces.
Adjusted the related `getFQExtendedClassName()` method accordingly and added unit tests for this change.
The change to the `FindExtendedClassname()` method is tested upstream.
> Sync `FindExtendedClassname()` method with upstream

- .travis.yml
The new Trusty images as per Sept 7 include an image for PHP 7.2 (even though it hasn't been released yet) and nightly is now PHP 7.3-dev.
> Travis: run the build tests against PHP 7.2 as well

- PHPCompatibility/Sniffs/PHP/ForbiddenNamesAsInvokedFunctionsSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/ForbiddenNamesAsInvokedFunctionsSniffTest.php
- PHPCompatibility/Tests/sniff-examples/forbidden_names_function_invocation.php
How the PHP and PHPCS tokenizers tokenize the function name in a method call varies wildly across versions, sometimes its tokenized as its own token, often times its tokenized as `T_STRING`.
In practice this meant that method invocations pre-PHP 7.0 were not always caught by this sniff, while they should be.
At the same time, for PHP 7.0+, those should be exempt for the purposes of this sniff as the keyword reservation has been relaxed to allow these keywords to be used as method names.
Both these issues are fixed by this PR.
Fixes #515
> ForbiddenNamesAsInvokedFunctions: don't throw error on method invocations / PHP 7.0+

- PHPCompatibility/Sniff.php
- PHPCompatibility/Tests/BaseClass/FunctionsTest.php
Minor simplification of the code in the `getTestVersion()` method.
* Use 2 instead of 4 regexes.
* Always check if the min and max versions are within bounds.
* Return early.
> Sniff::getTestVersion(): simplify regex logic.

- PHPCompatibility/Tests/Sniffs/PHP/RemovedAlternativePHPTagsSniffTest.php
There were still two test skips left without skip explanation.
> Tests: add test skip explanations.

- PHPCompatibility/Sniffs/PHP/NewLanguageConstructsSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/NewLanguageConstructsSniffTest.php
While this language construct is already tokenized correctly in PHPCS, PHP itself has not yet implemented it.
The RFC has been approved a while back and it was slated to go into PHP 7.2, but as of PHP 7.2 RC4 no implementation has been merged and it is not expected to go into PHP 7.2 anymore.
As PHPCS already recognized the token, it was already added to the `NewLanguageConstructs` sniff a while back.
All this PR does is up the PHP version number used for the compares.
> NewLanguageConstructs: Update the version number for T_COALESCE_EQUAL

- PHPCompatibility/Tests/BaseClass/IsClassPropertyTest.php
- PHPCompatibility/Tests/sniff-examples/utility-functions/is_class_property.php
Case 21 didn't exist, so testing for it is useless and can lead to unpredictable results.
> Tests: fix case numbering error

- phpcs.xml.dist
Exclude patterns are regexes and should escape regex special characters (except for the `*`).
See: squizlabs/PHP_CodeSniffer/issues/1592
> PHPCS ruleset: stabilize the exclude patterns

- PHPCompatibility/Sniffs/PHP/OptionalRequiredFunctionParametersSniff.php
- PHPCompatibility/Sniffs/PHP/RequiredOptionalFunctionParametersSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/OptionalRequiredFunctionParametersSniffTest.php
- PHPCompatibility/Tests/Sniffs/PHP/RequiredOptionalFunctionParametersSniffTest.php
- PHPCompatibility/Tests/sniff-examples/optional_required_function_parameters.php
Previously a `RequiredOptionalFunctionParameters` sniff has been added which checks for missing function call parameters which were required and only became optional in a later PHP version.
This PR adds a sister-sniff which checks for missing function call parameters which originally were optional, but later became required.
Initially this sniff checks for the `$results` parameter for the `parse_str()` function for which the optional nature of the parameter became deprecated in PHP 7.2 (soft required).
It is expected that the parameter will become hard required in PHP 8.0.
Refs:
* http://php.net/manual/en/migration72.deprecated.php#migration72.deprecated.parse_str-no-second-arg
* https://wiki.php.net/rfc/deprecations_php_7_2#parse_str_without_second_argument
* http://php.net/parse_str
* …
> PHP 7.2: New OptionalRequiredFunctionParameters sniff

- PHPCompatibility/Sniffs/PHP/RemovedGlobalVariablesSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/RemovedGlobalVariablesSniffTest.php
- PHPCompatibility/Tests/sniff-examples/removed_global_variables.php
> `track_errors` ini setting and `$php_errormsg` variable
>
> When the `track_errors` ini setting is enabled, a `$php_errormsg` variable is created in the local scope when a non-fatal error occurs. Given that the preferred way of retrieving such error information is by using `error_get_last()`, this feature has been deprecated.
Refs:
* http://php.net/manual/en/migration72.deprecated.php#migration72.deprecated.track_errors-and-php_errormsg
* https://wiki.php.net/rfc/deprecations_php_7_2#create_function
* http://php.net/manual/en/reserved.variables.phperrormsg.php
**Implementation notes:**
As the `$php_errormsg` variable is not a superglobal, quite some extra checks are needed.
All the same, adding it to the `RemovedGlobalVariables` sniff seemed like the most logical place for this variable …
> PHP 7.2: RemovedGlobalVariables: add detection for use of $php_errormsg

- PHPCompatibility/Sniffs/PHP/DynamicAccessToStaticSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/DynamicAccessToStaticSniffTest.php
- PHPCompatibility/Tests/sniff-examples/dynamic_access_to_static.php
New sniff to detect dynamic access to static methods and properties, as well as class constants, prior to PHP 5.3.
We may run into some false positives, though I've done due diligence and ran the sniff over a couple of semi-large PHP projects with various minimum PHP requirements (WordPress (5.2), PHP_CodeSniffer (5.4), PHPUnit 6.x (7.0) ) to see if could find any and so far, I haven't.
Fixes #534
> PHP 5.3: New `DynamicAccessToStatic` sniff

- PHPCompatibility/Sniffs/PHP/NewClosureSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/NewClosureSniffTest.php
- PHPCompatibility/Tests/sniff-examples/new_closure.php
... and adjust the error message to mention `bindTo()`.
Includes slight adjustments to the unit tests to document why this change was made.
This is an implementation of option 2 as mentioned in https://github.com/wimg/PHPCompatibility/issues/527#issuecomment-344348068
Fixes #527
> NewClosures: downgrade "$this found in closure outside class" to warning

- PHPCompatibility/Sniff.php
- phpcs.xml.dist
PHPCS upstream has added a new sniff to verify normalized array indentation.
As the PHPCS build check for the PHPCompatibility standard is run against `master`, we can start taken advantage of that.
This commit adds the relevant changes to the PHPCompatibility own ruleset to do so and fixes the one instance where the code did not yet comply with this.
> Build/PHPCS: check array indentation

- PHPCompatibility/Sniffs/PHP/ForbiddenCallTimePassByReferenceSniff.php
- PHPCompatibility/Sniffs/PHP/ForbiddenEmptyListAssignmentSniff.php
- PHPCompatibility/Sniffs/PHP/ForbiddenFunctionParametersWithSameNameSniff.php
- PHPCompatibility/Sniffs/PHP/ForbiddenNamesSniff.php
- PHPCompatibility/Sniffs/PHP/NewKeywordsSniff.php
- PHPCompatibility/Sniffs/PHP/NonStaticMagicMethodsSniff.php
- PHPCompatibility/Sniffs/PHP/RemovedAlternativePHPTagsSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/NewKeywordsSniffTest.php
- PHPCompatibility/Tests/Sniffs/PHP/ValidIntegersSniffTest.php
- phpcs.xml.dist
Apparently PSR2 turns a couple of the superfluous whitespace checks off.
This turns these back on.
There is one additional check turned off in PSR2 which I've left alone: the check for multiple blank lines in a row.
IMO, sometimes it's useful to use two blank lines to break up code for improved readability, so I'm quite happy to leave that one turned off.
> Build/PHPCS: improve check for superfluous whitespace in files

- CHANGELOG.md
- README.md
- composer.json
The `DealerDirect/phpcodesniffer-composer-installer` Composer plugin contained code which is incompatible with PHP 5.3. This has been fixed in [version 0.4.3](https://github.com/Dealerdirect/phpcodesniffer-composer-installer/releases/tag/v0.4.3) through PR https://github.com/Dealerdirect/phpcodesniffer-composer-installer/pull/39.
By upping the recommended version we prevent issues when users still use PHPCS 1.x/2.x in combination with PHP 5.3.
> Up the version for recommended Composer plugin.

- .travis.yml
The PHP-Coveralls project has *finally* tagged [some releases](https://github.com/php-coveralls/php-coveralls/issues/203). Using the tagged versions allows Travis to cache the package download which should hopefully make the builds a little faster.
The minimum PHP version for v 2.x is PHP 5.5, for the 1.x branch, it's PHP 5.3.3, so depending on the build, different versions are being used.
Other notes:
* The repository has moved from `satooshi/php-coveralls` to `php-coveralls/php-coveralls`.
* As of PHPCoveralls 2.x, the command to call coveralls has changed from `coveralls` to `php-coveralls`
This PR takes all of the above into account. Keeping my fingers crossed that the build will pass & coverage will be reported correctly (again).
Fixes #549 (hopefully... let's see if it really did …
> Travis: Use stable versions of Coveralls

- PHPCompatibility/Sniffs/PHP/DeprecatedFunctionsSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/DeprecatedFunctionsSniffTest.php
- PHPCompatibility/Tests/sniff-examples/deprecated_functions.php
Refs:
* http://php.net/manual/en/migration72.deprecated.php#migration72.deprecated.read_exif_data-function
* https://github.com/php/php-src/commit/ba28d75c2c72bc17841dbc410496e8d62e139681
> PHP 7.2: DeprecatedFunctions: add read_exif_data()

- PHPCompatibility/Sniffs/PHP/ForbiddenCallTimePassByReferenceSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/ForbiddenCallTimePassByReferenceSniffTest.php
- PHPCompatibility/Tests/sniff-examples/call_time_pass_by_reference.php
This was a known false positive and annotated as such in the unit test files.
Simplified the `isCallTimePassByReferenceParam()` method by using the upstream `isReference()` function to determine whether a _bitwise and_ is a reference or not.
The upstream method has [some issues pre PHPCS 3.1.1](https://github.com/squizlabs/PHP_CodeSniffer/pull/1609), but none which impact this sniff.
Fixes #39
> ForbiddenCallTimePassByReference: fix false positive for "bitwise and" preceded by global constant

- PHPCompatibility/Sniffs/PHP/VariableVariablesSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/VariableVariablesSniffTest.php
- PHPCompatibility/Tests/sniff-examples/variable_variables.php
Whitespace and comments are allowed to be interspersed in variables, so the sniff should take this into account.
> VariableVariables: improve code style independent sniffing

- PHPCompatibility/Sniffs/PHP/NewFunctionsSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/NewFunctionsSniffTest.php
- PHPCompatibility/Tests/sniff-examples/new_functions.php
Refs:
* http://php.net/manual/en/migration72.new-functions.php#migration72.new-functions.spl
* https://github.com/php/php-src/commit/5097e2ee13de12b4445b4123e1554c0733c6853c
Note: other than in the changelog, this function is currently undocumented and not yet mentioned in the manual!
The missing documentation has been reported: https://bugs.php.net/bug.php?id=75723
> PHP 7.2/New Functions: add spl_object_id()

- README.md
The same message was now shown twice, with one still containing a typo.
This PR moves the message out of the installation instructions, to the readme section on running PHPCompatibility.
It also improves the grammer of the text.
> Readme: Improve grammar of the reporting information

- PHPCompatibility/Sniffs/PHP/ForbiddenGlobalVariableVariableSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/ForbiddenGlobalVariableVariableSniffTest.php
- PHPCompatibility/Tests/sniff-examples/forbidden_global_variable_variable.php
The `ForbiddenGlobalVariableVariable` sniff was a little overzealous and would throw errors for valid variable variables.
The sniff has now been partially refactored.
The following improvements were made:
* Don't throw errors for non-complex variable variables. Issue #537.
* Correctly handle variable variables with whitespace or comments within the variable.
* Throw an `error` for *each* forbidden variable. Previously only one error would be thrown per `global` statement.
- The error is now thrown on the line containing the variable, not the line containing the `global` keyword.
- The error message now shows the problem variable encountered.
* Throw a `warning` for non-bare variables encountered in a `global` statement.
- This warning has a separate errorcode allowing for easy exclusion. …
> ForbiddenGlobalVariableVariable: fix false positives and more

- PHPCompatibility/Sniffs/PHP/DeprecatedIniDirectivesSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/DeprecatedIniDirectivesSniffTest.php
- PHPCompatibility/Tests/sniff-examples/deprecated_ini_directives.php
Refs:
* https://github.com/php/php-src/blob/eb5ba59ad5cd40ef47cb6bdbe8dbb15e2f4d6e42/UPGRADING#L359-L362
* https://github.com/php/php-src/pull/2591
* https://github.com/php/php-src/commit/f25ecdacf805f840f743b67b6d84485b2deceb4f
> PHP 7.2 / DeprecatedIniDirectives: add removed `opcache.fast_shutdown` directive

- .travis.yml
- composer.json
Validate the composer.json file on each build.
Ref: https://getcomposer.org/doc/03-cli.md#validate
Also updates the license identifier in the `composer.json` file to `LGPL-3.0-or-later` (see more about this below).
The license could also be limited to just LGPL 3.0 by using `LGPL-3.0-only`.
@wimg Let me know if that's would be preferred.
Notes:
* This check has not been restricted to a specific PHP version as there may be different versions of Composer being run on different Travis PHP images, so validating the file once against each PHP/Composer combi should make sure the file is properly validated.
* `--strict` checking is disabled with reason. As of Composer 1.6.0, the SPDX license identifiers v3.0 for GPL/LGPL/AGPL are supported and the old license identifiers are deprecated.
So using …
> Travis/Build: validate the composer.json file

- PHPCompatibility/Sniff.php
- PHPCompatibility/Tests/Sniffs/PHP/NewReturnTypeDeclarationsSniffTest.php
- PHPCompatibility/Tests/sniff-examples/new_return_type_declarations.php
PHPCS will identify the last token in a namespaced class name based return type as the `T_RETURN_TYPE` token and will tokenize the preceeding namespace and namespace separator tokens as normal, i.e. `T_STRING` and `T_NS_SEPARATOR`.
This change aligns the behaviour of the `getReturnTypeHintToken()` method with PHPCS upstream, so multi-line return declarations will report on the same line across PHPCS versions.
Includes unit test covering the change in the `NewReturnTypes` sniff.
> Sniff: align `getReturnTypeHintToken()` bc method with PHPCS behaviour

- PHPCompatibility/Sniff.php
- PHPCompatibility/Sniffs/PHP/NewClassesSniff.php
- PHPCompatibility/Sniffs/PHP/NewInterfacesSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/NewClassesSniffTest.php
- PHPCompatibility/Tests/Sniffs/PHP/NewInterfacesSniffTest.php
- PHPCompatibility/Tests/sniff-examples/new_classes.php
- PHPCompatibility/Tests/sniff-examples/new_interfaces.php
Verification whether interfaces/classes added in newer PHP versions were being used as return type declarations was missing from the sniffs.
This fixes that.
Uses the new `Sniff::getReturnTypeHintName()` method which has been added to the `Sniff` class in a separate commit.
> NewInterfaces/Classes: add recognition of return type declarations

- PHPCompatibility/Tests/sniff-examples/new_return_type_declarations.php
Nothing "relevant" as it does not have influence on the tokenizer, but just a form of leading by example.
> NewReturnTypeDeclarations: fix parse errors in unit test case file (duplicate function names)

- PHPCSAliases.php
- PHPCompatibility/Sniffs/PHP/ReservedFunctionNamesSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/ReservedFunctionNamesSniffTest.php
- PHPCompatibility/Tests/sniff-examples/reserved_function_names.php
- PHPCompatibility/ruleset.xml
This was previously handled by an upstream sniff - see PR #173 -.
The "problem" with the previous implementation is that when PHPCompatibility is used in a custom ruleset which also includes sniffs from other rulesets, a "conflict" would be created if another ruleset included the `Generic.NamingConventions.CamelCapsFunctionName` sniff as well.
PHPCompatibility silenced two of the error messages from that sniff and unless you are actually aware of that and know how to re-enable those, chances are that this will go unnoticed and non-camelCaps function and method name issues would go unreported because of it.
This breaking of other rulesets, is, of course, undesired.
This is now solved by the introduction of a new sniff which extends the upstream sniff to allow it to benefit from the …
> New `ReservedFunctionNames`sniff

- PHPCompatibility/Sniff.php
- PHPCompatibility/Sniffs/PHP/ForbiddenNamesAsDeclaredSniff.php
- PHPCompatibility/Sniffs/PHP/ForbiddenNamesAsInvokedFunctionsSniff.php
- PHPCompatibility/Sniffs/PHP/ForbiddenNamesSniff.php
- PHPCompatibility/Sniffs/PHP/InternalInterfacesSniff.php
- PHPCompatibility/Sniffs/PHP/NewClassesSniff.php
- PHPCompatibility/Sniffs/PHP/NewInterfacesSniff.php
- PHPCompatibility/Sniffs/PHP/NonStaticMagicMethodsSniff.php
- PHPCompatibility/Sniffs/PHP/RemovedAlternativePHPTagsSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/RemovedAlternativePHPTagsSniffTest.php
- phpcs.xml.dist
[PHPCS 3.2.x introduced new inline PHPCS annotations](https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.2.0) which allow for far more selective ignores inline.
Up to now, the PHPCompatibility library used either file-based excludes from the ruleset or a work-around by using `constant()`.
Work-arounds to get round PHPCS notices is kind of counter to the whole idea.
Blanket file-based excludes are risky as they can ignore too much.
As the PHPCS check for the PHPCompatibility library is run on a high PHPCS version anyhow (the PHPCS check in Travis runs against PHPCS `master`), we can switch over and start using the new annotations.
This PR removes both the work-arounds as well as the file-based excludes, in favour of using selective inline ignores.
> Use new PHPCS annotations

- PHPCompatibility/Tests/BaseClass/IsUseOfGlobalConstantTest.php
- PHPCompatibility/Tests/sniff-examples/utility-functions/is_use_of_global_constant.php
Verifies and safe-guards that multi-constant declarations are handled correctly.
> Sniff/isUseOfGlobalConstant: add unit tests covering multi-constant declarations

- PHPCompatibility/Tests/BaseClass/MethodTestFrame.php
As `$end` is used in a `findNext()` and the `$end` parameter of `findNext()` is _EX_clusive, rather than inclusive - in contrast to `findPrevious()` - see upstream issue squizlabs/PHP_CodeSniffer#1319 -, the `$i - 1` is wrong.
Wasn't causing any issues (yet) as the `Case` comments used so far were always preceded by a T_WHITESPACE anyway, but the code should be correct.
> MethodTestFrame: minor fix

- PHPCompatibility/Sniffs/PHP/DeprecatedTypeCastsSniff.php
Remove superfluous check.
At this time, the sniff only registers the exact tokens needed - i.e. there are no work-arounds in place for cross-PHPCS version compatibility -, so there is no chance that the tokenType would not be one of the target token types.
> DeprecatedTypeCasts: minor simplification

- PHPCompatibility/Sniffs/PHP/ConstantArraysUsingConstSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/ConstantArraysUsingConstSniffTest.php
- PHPCompatibility/Tests/sniff-examples/constant_arrays_using_const.php
While not all that common, multi-constant declarations are supported in PHP.
When such a declaration is encountered, the sniff should throw an error for each constant declared with an array value.
> ConstantArraysUsingConst: handle multi-constant declarations correctly

- PHPCompatibility/Sniffs/PHP/DeprecatedNewReferenceSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/DeprecatedNewReferenceSniffTest.php
Minor textual change to the error message + error code in line with previous changes to other sniffs.
The change in the errorcode can be considered a BC break, but only for people explicitly excluding the errorcode or ignoring it using the new PHPCS annotations.
> DeprecatedNewReference: "removed" not forbidden

- PHPCompatibility/Sniff.php
- PHPCompatibility/Sniffs/PHP/NewScalarTypeDeclarationsSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/NewScalarTypeDeclarationsSniffTest.php
- PHPCompatibility/Tests/sniff-examples/new_scalar_type_declarations.php
Based on a variety of tests run on 3v4l, I've come to the conclusion that this sniff needs adjusting.
* `parent` is a valid parameter type declaration.
* `self` and `parent` were not recognized properly until PHP 5.2. Before that, they would be treated as class names.
This PR adjusts the sniff to deal correctly with this, based on these finding.
Includes adjusted unit tests.
N.B.: While there has previously been discussion on whether or not the "debug"-type errors like `self used outside of class scope` - introduced in #168 - are warranted, the above mentioned tests showed that as of PHP 7.0, using `self`/`parent` as a type declaration outside class scope results in a fatal error.
I've documented this inline.
> NewScalarTypeDeclarations: fix incorrect results

- PHPCompatibility/Sniffs/PHP/OptionalRequiredFunctionParametersSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/OptionalRequiredFunctionParametersSniffTest.php
- PHPCompatibility/Tests/sniff-examples/optional_required_function_parameters.php
> crypt() will now raise an E_NOTICE error if the salt parameter is omitted.
Refs:
* http://php.net/manual/en/migration56.changed-functions.php#migration56.changed-functions.core
* http://php.net/manual/en/function.crypt.php#refsect1-function.crypt-changelog
It was simplest to build this into the `OptionalRequiredFunctionParameters` sniff, even though it is a slightly different state than the original intention of the sniff was for. The principle however is the same.
> PHP 5.6: throw a warning when a call to crypt() is missing $salt

- README.md
As PHP 5.2 is not supported anymore anyway, it is confusing and misleading to display it as being "not tested".
Other than that, the current "tested" badge does not reflect that the library is tested against PHP 7.2 (and nightly and HHVM).
I've [asked the maintainer of PHP-Eye a question about this on Twitter](https://twitter.com/jrf_nl/status/972472140913049600). Hopefully that will be fixed soon.
[skip ci]
> README: remove PHP "not tested" badge

- PHPCompatibility/Sniffs/PHP/NewFunctionParametersSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/NewFunctionParametersSniffTest.php
- PHPCompatibility/Tests/sniff-examples/new_function_parameter.php
Discovered while trolling through http://php.net/manual/en/doc.changelog.php. Most of these are not annotated in the migration or source changelogs, though they are in the function documentation changelogs.
See the individual commits for more details.
> Add more new function parameters

- PHPCompatibility/Sniffs/PHP/RequiredOptionalFunctionParametersSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/RequiredOptionalFunctionParametersSniffTest.php
- PHPCompatibility/Tests/sniff-examples/required_optional_function_parameters.php
> 7.3.0 	bcscale() can now be used to get the current scale factor; when used as setter, it now returns the old scale value. Formerly, scale was mandatory, and bcscale() always returned TRUE.
Ref: http://php.net/manual/en/function.bcscale.php#refsect1-function.bcscale-changelog
This includes a minor bugfix to the sniff logic as the sniff did not take into account that the first parameter of a function may become optional. This is now correctly accounted for.
> PHP 7.3: the `scale` parameter of bcscale() is now optional

- PHPCompatibility/Sniffs/PHP/NewHashAlgorithmsSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/NewHashAlgorithmsSniffTest.php
- PHPCompatibility/Tests/sniff-examples/new_hash_algorithms.php
> 7.1.0 	Support for sha512/224, sha512/256, sha3-224, sha3-256, sha3-384 and sha3-512 has been added.
Refs:
* http://php.net/manual/en/function.hash-algos.php
* https://github.com/php/php-src/commit/49a7be069700efbb98dbb076bb0891c748c343f4
* https://github.com/php/php-src/commit/d244b54c67cc2725283b78d4bb128501ae7910d3
> PHP 7.1: detect newly added hash algorithms

- README.md
Up to now, if a `testVersion` had been set in the ruleset, the command-line would not overrule. This has now changed and this change will be included in PHPCS 3.3.0.
Ref: squizlabs/PHP_CodeSniffer#1821
[ci skip]
> Readme: add note about command-line vs ruleset

- PHPCompatibility/Sniff.php
- PHPCompatibility/Tests/BaseClass/IsNumberTest.php
- PHPCompatibility/Tests/BaseClass/TestHelperPHPCompatibility.php
- PHPCompatibility/Tests/sniff-examples/utility-functions/is_number.php
These methods can be used to determine if variable assignments, function call parameters or array values would be regarded as a (positive/negative) number by PHP.
The `isNumber()` method is used to determine whether something would be regarded as a number by PHP.
This method takes type juggling from string and boolean to integer/float into account.
The method will return `false` if something isn't a number as well as when it couldn't be reliably determined, so should only be used for testing whether something definitely *is* a number (well, that is _would be regarded as a number by PHP_).
The method will return `false` when it encounters calculations, even when all parts of the calculation are numbers. Handling this even better, is something which could possibly be added later (in a …
> Sniff: add three utility methods to handle number recognition

- .github/CONTRIBUTING.md
- README.md
- framework-rulesets/wordpress.xml
Frameworks/CMSes often provide backfills for PHP native functionality which is not available in the minimum PHP version supported by the framework/CMS.
As suggested in #530, this is a first PR adding a framework specific ruleset to PHPCompatibility.
To give some context:
In the WordPress community, there is currently a project under way called [Tide](https://make.wordpress.org/tide/).
This project uses the PHPCompatibility library to analyse all the plugins (50.000+) and themes (3.000+) hosted on wordpress.org and will in the near future be used to start displaying PHP compatibility information for each of them on the wordpress.org website.
With that in mind, I expect a significant number of developers in the WordPress community will want to start using PHPCompatibility as part of their …
> Add a WordPress specific PHPCompatibility ruleset

- bin/generate-forbidden-names-test-files
Files without extension are not checked by PHPCS, so this file was missed in the big code style clean up of the code base.
> CS: clean up `generate-forbidden-names-test-files` file

- composer.json
PHPUnit 7.x has come out in the mean time and is already in use on some of the Travis images (notably the images for PHP 7.2 and nightly).
Looks like the current unit test suite will work on PHPUnit 7.x without issues, so let's indicate that.
Also makes sure that if PHPUnit 4.x is used, it will get a compatible version as per https://github.com/wimg/PHPCompatibility/pull/511#issuecomment-335676926.
> Composer: allow for PHPUnit 7.x

- PHPCompatibility/Sniffs/PHP/NewGeneratorReturnSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/NewGeneratorReturnSniffTest.php
- PHPCompatibility/Tests/sniff-examples/new_generator_return.php
> Generator Return Expressions
>
> This feature builds upon the generator functionality introduced into PHP 5.5. It enables for a `return` statement to be used within a generator to enable for a final expression to be returned (return by reference is not allowed). > This value can be fetched using the new `Generator::getReturn()` method, which may only be used once the generator has finished yielding values.
Refs:
* http://php.net/manual/en/migration70.new-features.php#migration70.new-features.generator-return-expressions
* https://wiki.php.net/rfc/generator-return-expressions
* https://github.com/php/php-src/commit/5c230baf75fb17d1d0b8ec407a7479d02b25068a
The new sniff checks for and reports on `return` statements being found in generator functions.
> PHP 7.0: New sniff to detect generator return expressions

- PHPCompatibility/Sniffs/PHP/NewNullableTypesSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/NewNullableTypesSniffTest.php
- PHPCompatibility/Tests/sniff-examples/new_nullable_types.php
* Adds a unit test where the param and return type declarations are divvied up over several lines interspersed with comments and (new) PHPCS annotations.
* Changes the `processReturnType()` method to allow for comments interspersed in the declaration.
* Removes some duplicate code/minor code simplification.
> NewNullableTypes: make the return type part of the sniff more code style independent

- composer.json
This dependency will prevent packages with known security issues from being installed through Composer.
The package will always have to be at `dev-master` to make sure that the latest security information available will be used.
Unfortunately, we can't add it as a `dev` dependency to PHPCompatibility itself as it would prevent us from testing on PHPCS 1.x and most of the 2.x range, which contain a known security vulnerability.
We can, however, support the project and try to help spread it by suggesting it to the users of PHPCompatibility.
Refs:
* https://github.com/Roave/SecurityAdvisories
* https://www.bleepingcomputer.com/news/security/php-community-takes-steps-to-stop-installation-of-libraries-with-unpatched-bugs/
* https://websec.io/2018/03/10/Package-Protection-Roave-SecurityAdvisorie …
> Composer: suggest Roave/SecurityAdvisories dependency

- PHPCompatibility/PHPCSHelper.php
- PHPCompatibility/Sniff.php
- PHPCompatibility/Sniffs/PHP/ForbiddenNegativeBitshiftSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/ForbiddenNegativeBitshiftSniffTest.php
- PHPCompatibility/Tests/sniff-examples/forbidden_negative_bitshift.php
The `ForbiddenNegativeBitshift` was only listening to "bitshift right", while the change made in PHP 7.0 also affects:
* bitshift left
* bitshift left assignments
* bitshift right assignments
These tokens have now been added to the array to listen to and negative bitshifting for these will now also be reported.
Refs:
* http://php.net/manual/en/migration70.incompatible.php#migration70.incompatible.integers.negative-bitshift
* https://wiki.php.net/rfc/integer_semantics
The sniff should err on the side of caution and only report when it can be determined with some form of certainty that the operand is a negative number.
I.e. calculations with variables which may or may not result in a negative number should not be reported.
To this end, the new `isNegativeNumber()` utility method is used to …
> ForbiddenNegativeBitshift: fix false positive and underreporting

- README.md
The VersionEye service has been terminated.
Refs:
* https://github.com/versioneye/versioneye/issues/730
* https://blog.versioneye.com/2017/10/19/versioneye-sunset-process/
[ci skip]
> README: remove VersionEye badge

- PHPCompatibility/Sniffs/PHP/PCRENewModifiersSniff.php
- PHPCompatibility/Sniffs/PHP/PregReplaceEModifierSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/MbstringReplaceEModifierSniffTest.php
- PHPCompatibility/Tests/Sniffs/PHP/PCRENewModifiersSniffTest.php
- PHPCompatibility/Tests/Sniffs/PHP/PregReplaceEModifierSniffTest.php
- PHPCompatibility/Tests/sniff-examples/pcre_new_modifiers.php
... which will initially sniff just for the new `J` modifier which was added in PHP 7.2.
Fixes #556
As the logic needed to retrieve the regex modifiers was already available in the `PregReplaceEModifier` sniff, I've made some small adjustments to that sniff to make it more easily extendable and feature complete.
The new sniff is - of course - accompanied by unit tests, but only cursory as the main logic behind the sniff is already tested extensively in the unit tests for the `PregReplaceEModifier` sniff.
> PHP 7.2: New PCRENewModifiers sniff

- .travis.yml
Now the `framework-rulesets` directory and the first framework/CMS ruleset has been added, it seems like a good idea to make sure that those rulesets are also verified during the Travis run:
* Lint each ruleset in that directory for valid XML
* Check the codestyle of the ruleset which has been added - this second check will need to be added for each individual ruleset
> Travis/CS/QA: lint CMS/framework ruleset and check codestyle

- PHPCompatibility/Sniffs/PHP/RemovedGlobalVariablesSniff.php
Turns out that using `end()` on a nested array in a (very) large array such as the `$tokens` array can be with large files, is significantly slower than copying the nested array to a local variable and using `end()` on that.
See: https://github.com/squizlabs/PHP_CodeSniffer/commit/6d15547ed874d0061c83e380496162e2ec2020c8#r28189947
> Minor performance optimization

- PHPCompatibility/Sniffs/PHP/NewKeywordsSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/NewKeywordsSniffTest.php
- PHPCompatibility/Tests/sniff-examples/new_keywords.php
A number of tokens are not correctly back-filled across PHP versions by various PHPCS versions.
To that end, a _token translation table_ is used to recognize tokens tokenized as `T_STRING` as the keyword anyway.
At the same time, PHPCS sometimes retokenizes too aggressively, changing `T_STRING` tokens to a keyword token when it shouldn't.
Most PHP keywords can be safely used as variable (and property) names and as of PHP 7, as the name of class constants.
> Using them as variable names is generally OK, but could lead to confusion. 
Ref: http://php.net/manual/en/reserved.keywords.php
As property names when referenced and class constant names, both when referenced as well as when declared, are tokenized as `T_STRING`, this leads to false positives from this sniff.
At the same time, keywords …
> NewKeywords: fix too aggressive accounting for PHPCS cross-compat

- PHPCompatibility/Sniffs/PHP/NewConstantScalarExpressionsSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/NewConstantScalarExpressionsSniffTest.php
- PHPCompatibility/Tests/sniff-examples/new_constant_scalar_expressions.php
… where previously only static values were allowed.
> It is now possible to provide a scalar expression involving numeric and string literals and/or constants in contexts where PHP previously expected a static value, such as constant and property declarations and default function arguments.
Refs:
* http://php.net/manual/en/migration56.new-features.php#migration56.new-features.const-scalar-exprs
* https://wiki.php.net/rfc/const_scalar_exprs
* https://wiki.php.net/rfc/const_scalar_expressions
Includes extensive unit tests.
Notes:
* The sniff has been set up in a way that the `HeredocInitialize` sniff will be able to extend it in the near future as that sniff ought to use the same base logic as is contained in the `process()` method of this sniff (The `HeredocInitialize` sniff currently …
> PHP 5.6: New sniff to detect constant scalar expressions

- PHPCompatibility/AbstractFunctionCallParameterSniff.php
- PHPCompatibility/Sniffs/PHP/MbstringReplaceEModifierSniff.php
- PHPCompatibility/Sniffs/PHP/PCRENewModifiersSniff.php
- PHPCompatibility/Sniffs/PHP/PregReplaceEModifierSniff.php
This adds a new abstract base class to do the initial checks necessary of whether a T_STRING token is a function/method call and whether the function called is one of the target functions.
Child classes are expected to set:
* The `$targetFunctions` array to indicate the names of the functions (as array keys) which the child class is looking for.
* [Optional] the `$isMethod` property to `true` if they are looking for method calls.
Child classes are expected to implement a `processParameters()` method to examine the contents of the parameters passed to the function call.
This abstract class will form the base for the new sniffs to address #475, #553, #557 and #559 as outlined in #601.
This allows for a minor code duplication clean-up and for a more rigorous check if a `T_STRING` token is …
> Add new AbstractFunctionCallParameterSniff & start using it in two sniffs

- PHPCompatibility/Sniff.php
- PHPCompatibility/Tests/BaseClass/IsShortListTest.php
- PHPCompatibility/Tests/sniff-examples/utility-functions/is_short_list.php
... to determine whether a short array is in actual fact a short list syntax.
The utility method also accounts for two different PHPCS tokenizer bugs, one which affects PHPCS 1.5.x and the other which affects PHPCS 2.0 - 2.7.x.
There may be more tokenizer bugs we need to account for, but these are the ones I've found so far.
Includes dedicated unit tests.
This new utility function is needed for ~~three~~ five new sniffs + one existing sniff, which all deal with, or at least have to be able to recognize, short `list` constructs.
> Sniff: Add new `isShortList()` utility function

- PHPCompatibility/Tests/BaseSniffTest.php
The `PHP` category was hard-coded in the unit test `getSniffCode()` function logic. As per #601, more categories are going to be used, this needs to be changed.
> Unit Tests: allow for sniffs in other categories

- PHPCompatibility/Tests/BaseClass/IsClassPropertyTest.php
- PHPCompatibility/Tests/sniff-examples/utility-functions/is_class_property.php
Verifies and safe-guards that multi-property definitions are handled correctly.
------
~~**Note**: the build is currently not passing for the PHPCS check on the PHPCompatibility files because of a known upstream bug.
See https://github.com/squizlabs/PHP_CodeSniffer/issues/1898 and https://github.com/squizlabs/PHP_CodeSniffer/pull/1899 for more details.
This is expected to be fixed soon.~~
The fix for the upstream issue has been merged, so the builds are passing again.
> Sniff/isClassProperty: add unit tests covering multi-property definitions

- PHPCompatibility/Sniffs/PHP/NewFunctionsSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/NewFunctionsSniffTest.php
- PHPCompatibility/Tests/sniff-examples/new_functions.php
Ref:
* https://wiki.php.net/rfc/is-countable
* https://github.com/php/php-src/commit/d0ee2a8254c69546c7191ac26cdc0499eba27acf
I expect that lots of userland `is_countable()` functions will be/have been added since PHP 7.2 added the "counting non-countable" warning.
This should give people plenty of warning that they'll need to wrap that function within a `if (function_exists() === false ) {}` wrapper.
---
P.S.: build failure is unrelated to this PR, see #639
> PHP 7.3/NewFunctions: add new `is_countable()` function

- PHPCompatibility/Sniffs/PHP/NewScalarTypeDeclarationsSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/NewScalarTypeDeclarationsSniffTest.php
While in PHP 5 "type hints" were introduced, the name of these have since been changed to "type declarations" to better cover their usage.
This brings the error message text in line with the changed terminology.
> NewScalarTypeDeclarations: minor message text change

- PHPCompatibility/Sniff.php
The return is expected to be an `int` `$stackPtr`, not a token code.
> `getReturnTypeHintToken()`: bug fix

- composer.json
Just suggesting a package does not explain to a user why it would be interesting for them to install it and I've already had question about the suggestion.
The `suggest` entry in the `composer.json` file has a value which is not actually intended for version constraints, but to add a hint to the user about why they should install the package.
Up to now, the value in the PHPCompatibility `composer.json` was used for a version constraint. While this is still a good idea to mention in this case as the Composer plugin needs a certain version to be compatible with the same PHP versions PHPCompatibility supports and the `security-advisories` needs to be at the uncommon `dev-master`, adding the hint on why the package is suggested should help users even more.
Ref: …
> Composer: add informational notes about the suggested dependencies

- PHPCompatibility/Sniff.php
- PHPCompatibility/Tests/BaseClass/IsNumberTest.php
- PHPCompatibility/Tests/sniff-examples/utility-functions/is_number.php
I originally wrote the utility function just to recognize negative numbers. At a later point, I changed it around to also recognize positive numbers and zero and moved the positive/negative check to separate functions.
However, I must have been distracted while doing this as there are two cases which would evaluate to zero which I had not yet adapted the function for.
The first two commits fix these two bugs and adds unit tests for them.
The last commit improves the handling of numbers which are preceded by multiple signs, i.e `-+-+- 10`.
Includes unit test as well.
Related to #610
> Utility `isNumber()`: various improvements

- PHPCompatibility/Sniffs/PHP/NewClosureSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/NewClosureSniffTest.php
- PHPCompatibility/Tests/sniff-examples/new_closure.php
As pointed out by @moorscode, closures can be nested within closures. As the sniff was, that would result in the notices for the inner closure being thrown twice.
The first commit fixes this.
Includes unit test, though this can not be automatically tested with the unit test framework as is.
The unit test is there so manual testing will pick up on it.
Not mentioned in the manual, but both the test sample provided by @asadkn as well as further tests I ran confirmed that this was changed in PHP 5.4
Fixes #668
> NewClosure: report usage of self/parent/static for PHP < 5.4 + prevent double notices

- phpcs.xml.dist
As the PHPCompatibility own check for consistent code style is run on PHPCS 3.x, we may as well take advantage of some of the new features.
* Clean up the report by only showing the relevant part of the path to the scanned file.
* Whenever possible scan files in parallel for speed improvement.
> PHPCS: add some PHPCS 3.x options to the PHPCompatibility native ruleset

- PHPCompatibility/Sniffs/PHP/ArgumentFunctionsUsageSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/ArgumentFunctionsUsageSniffTest.php
- PHPCompatibility/Tests/sniff-examples/argument_functions_usage.php
Add a sniff which checks for usage of the `func_get_args()`, `func_get_arg()` and `func_num_args()` functions and the changes regarding these function in PHP 5.3.
Covers:
>  func_get_arg(), func_get_args() and func_num_args() can no longer be called from the outermost scope of a file that has been included by calling include or require from within a function in the calling file.
Ref: http://php.net/manual/en/migration53.incompatible.php
> PHP 5.3.0 This function can now be used in parameter lists.
Refs:
* http://php.net/manual/en/function.func-get-args.php#refsect1-function.func-get-args-changelog
* http://php.net/manual/en/function.func-get-arg.php#refsect1-function.func-get-arg-changelog
* http://php.net/manual/en/function.func-num-args.php#refsect1-function.func-num-args-changelog …
> PHP 5.3: New ArgumentFunctionsUsage sniff

- PHPCompatibility/Sniffs/PHP/NewClassMemberAccessSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/NewClassMemberAccessSniffTest.php
- PHPCompatibility/Tests/sniff-examples/new_class_member_access.php
> Class member access on instantiation has been added, e.g. (new Foo)->bar().
Refs:
* http://php.net/manual/en/migration54.new-features.php#migration54.new-features
* https://wiki.php.net/rfc/instance-method-call
> Class member access on cloning has been added, e.g. (clone $foo)->bar().
Ref: http://php.net/manual/en/migration70.new-features.php#migration70.new-features.others
I've ran the sniff against a couple of code bases to test against false positives and fixed the ones I found.
I've coded the sniff to err on the side of caution, but I will not be surprised if some false positive/negatives will be reported once this sniff is active.
If they are, I will of course fix them.
Fixes #53
> PHP 5.4/7.0: New sniff to detect class member access on object instantiation/cloning

- PHPCompatibility/Sniffs/PHP/NewTrailingCommaSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/NewTrailingCommaSniffTest.php
- PHPCompatibility/Tests/sniff-examples/new_trailing_comma.php
Trailing comma's in function calls, method calls, `isset()` and `unset()` will be allowed as of PHP 7.3.
Refs:
* https://wiki.php.net/rfc/trailing-comma-function-calls
* https://github.com/php/php-src/commit/b591c329ee3129adbdc35141bb1542d119f7a2a1
I've kept the name of the sniff generic to allow for adding more constructs in the future in case trailing comma's will start to be allowed in, for instance, `list()`.
Includes unit tests which are largely based on the example code in the RFC/unit tests in PHP core.
> PHP 7.3: new sniff to detect trailing comma's in function calls, isset() and unset()

- framework-rulesets/joomla.xml
We added Symfony's PHP 7.3 polyfill and support `is_countable()` through it.
> Add is_countable to Joomla ruleset

- PHPCompatibility/Sniff.php
- PHPCompatibility/Tests/BaseClass/GetFunctionParametersTest.php
- PHPCompatibility/Tests/sniff-examples/utility-functions/get_function_parameters.php
Closures can be declared within function calls when the function expects a call-back.
This situation was only partially handled within the `Sniff::getFunctionCallParameters()` method.
Most of the time when a comma is encountered within a closure, it will be at a different nesting level than the original function call/array, which meant it would be disregarded and the method would return the correct results.
However, there are some, albeit rare, situations in which the comma would be at the target nesting level, causing the method to split the closure into two or more "parameters".
I came across this while working on a PR for WPCS which uses the same utility function.
As far as I know, this bug has not caused any issues for any of the PHPCompatibility sniffs so far, but the situation …
> Sniff::getFunctionCallParameters(): correctly handle closures when passed as param

- PHPCompatibility/PHPCSHelper.php
Found via Scrutinizer.
`$this` does not exist in a static method, nor has `$tokens` been set as a property (copy/paste artefact).
Not a bug which was actively encountered so far.
> PHPCSHelper: minor bugfix

- .github/CONTRIBUTING.md
Also:
* Link to the PHPCompatibility native PHPCS ruleset.
* Minor textual change.
[ci skip]
> CONTRIBUTING: add note about adding framework ruleset to Travis script

- PHPCompatibility/PHPCSHelper.php
- PHPCompatibility/Sniffs/PHP/DiscouragedSwitchContinueSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/DiscouragedSwitchContinueSniffTest.php
- PHPCompatibility/Tests/sniff-examples/discouraged_switch_continue.php
- composer.json
As of PHP 7.3, using `continue` to target `switch` will start throwing an `E_WARNING`.
> . "continue" statements targeting "switch" control flow structures will now
> generate a warning. In PHP such "continue" statements are equivalent to
> "break", while they behave as "continue 2" in other languages.
Refs:
* https://github.com/php/php-src/blob/04e3523b7d095341f65ed5e71a3cac82fca690e4/UPGRADING#L47-L58
* https://github.com/php/php-src/commit/04e3523b7d095341f65ed5e71a3cac82fca690e4
* https://wiki.php.net/rfc/continue_on_switch_deprecation
This PR adds a new sniff to detect this.
Notes:
* This sniff runs into the same difficulties with unscoped control structures as the `ForbiddenBreakContinueOutsideLoop` sniff.
For this sniff, I've elected to prevent the false positives which plague the …
> PHP 7.3: New `DiscouragedSwitchContinue` sniff

- README.md
PR #687 raised the minimum supported PHPCS 2.x version to `2.3.0` in the `composer.json`. This should also be reflected in the information in the Readme.
Also: as PHPCS is a dependency of PHPCompatibility, people shouldn't add it to their `require-dev`, but should leave it up to PHPCompatibility to require it.
[ci skip]
N.B.: I'm aware that this PR will have an imaginary conflict with PR #689, so just ping me and I'll rebase either one depending on which one gets merged first.
> README: Update minimum PHPCS version requirement and composer install instructions

- .github/CONTRIBUTING.md
- CHANGELOG.md
- PHPCompatibility/Sniff.php
- PHPCompatibility/Tests/sniff-examples/call_time_pass_by_reference.php
- README.md
- composer.json
Updated:
* `composer.json` - just the organisation name, I've left the package name as it was as I'm not sure whether changing that would cause problems.
* Updated references in the install instructions in the `Readme` and the `8.0.0` changelog to point to the repo in the new organization.
* Updated GH links in markdown files to point to the repo in the new organization.
* Updated references to issues within the codebase to point to the repo in the new organization.
* Updated the links + images for the badges in the `readme`.
Note: I've *not* updated all the links in the Changelog as GH redirects them anyway and we do not need to rewrite history.
Related to #688
> Update texts for move to GH organization

- PHPCompatibility/PHPCSHelper.php
- PHPCompatibility/Sniffs/Upgrade/LowPHPCSSniff.php
- README.md
As it has been decided that PHPCS 1.5.x support will be dropped in PHPCompatibility 9.0.0, this will give users of PHPCS versions below the next minimum recommended version - 2.6.0 - advance notice.
`2.6.0` is already mentioned in the readme as the minimum recommended version and has been for a while (since July 2017).
`2.3.0` will be the next minimum _supported_ version. A note to that effect has also been added to the Readme.
The sniff will throw a `warning` when the PHPCS version PHPCompatibility is run on, is below the minimum recommended version and an `error` when the PHPCS version is below the minimum supported version.
The error message contains delimiter lines to improve the readability of the (very long) message.
Unfortunately, using line breaks is not an option as the …
> New sniff to check minimum supported/recommended PHPCS version

- CHANGELOG.md
~~**NOT FOR MERGE (yet)**~~
~~Work in progress branch /~~ Changelog for the 8.2.0 release.
See: https://github.com/wimg/PHPCompatibility/milestone/22
Quite a massive release yet again....
[ci skip]
> Changelog for version 8.2.0

- PHPCompatibility/Sniffs/PHP/NewKeywordsSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/NewKeywordsSniffTest.php
- PHPCompatibility/Tests/sniff-examples/new_keywords.php
You learn something new every day and today I learned that the PHP magic constants are case _insensitive_. Who knew ?
Proof: https://3v4l.org/8l1GP
Found via: https://wiki.php.net/rfc/case_insensitive_constant_deprecation#unaffected_php_functionality
> NewKeyword: bug fix - magic constants are case insensitive

- PHPCompatibility/Sniffs/PHP/NewFunctionParametersSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/NewFunctionParametersSniffTest.php
@jrfnl I did not see any other PHP 4 entries, so if this isn't the format that you want, please let me know.
Ref: https://github.com/php/php-src/commit/7f89d8c13a7c4d86a4efb8b15609533bf2928d9e
Updates: https://github.com/PHPCompatibility/PHPCompatibility/commit/eba7501e48209d933ddb930f08830529fe6931a5
> PHP 4.3: new php_uname() $mode parameter

- phpunit-travis.xml
As of PHPUnit 7.2 the XML configuration is validated against the XSD and throws a warning.
The `<log>` element should, according to the PHPUnit manual, be nested within a `<logging>` element.
```
PHPUnit 7.2.7 by Sebastian Bergmann and contributors.
Warning - The configuration file did not pass validation!
The following problems have been detected:
Line 14:
- Element 'log': This element is not expected.
Test results may not be as expected.
```
From: https://travis-ci.org/PHPCompatibility/PHPCompatibility/jobs/407612965#L799-L805
Refs:
* https://phpunit.readthedocs.io/en/7.1/configuration.html#logging
* https://phpunit.de/manual/5.7/en/appendixes.configuration.html#appendixes.configuration.logging
* https://github.com/sebastianbergmann/phpunit/issues/3066
* …
> Fix PHPUnit 7.2 compatibility

- PHPCompatibility/Sniffs/PHP/RemovedFunctionParametersSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/RemovedFunctionParametersSniffTest.php
- PHPCompatibility/Tests/sniff-examples/removed_function_parameter.php
> The declaration of case-insensitive constants has been deprecated. Passing `true` as the third argument to `define()` will now generate a deprecation warning. The use of case-insensitive constants with a case that differs from the declaration is also deprecated.
Refs:
* https://wiki.php.net/rfc/case_insensitive_constant_deprecation
* https://github.com/php/php-src/blob/3b6e1ee4ee05678b5d717cd926a35ffdc1335929/UPGRADING#L262-L266
* https://github.com/php/php-src/commit/3588d8af129489eda3e3fdb9612b09a4da16dcfd
N.B.: sniffing for the _"use of case-insensitive constants"_  is not covered and would be neigh impossible to sniff anyway.
> PHP 7.3: DeprecatedFunctionParameters: account for change to define()

- PHPCompatibility/PHPCSHelper.php
No need to check the method as it's not actually used (didn't give correct results on runtime). The class however is needed, so is a good enough indicator of being on PHPCS 3.x.
> PHPCSHelper: minor fix

- PHPCompatibility/Sniff.php
- PHPCompatibility/Sniffs/PHP/ConstantArraysUsingDefineSniff.php
- PHPCompatibility/Sniffs/PHP/DeprecatedFunctionsSniff.php
- PHPCompatibility/Sniffs/PHP/DeprecatedIniDirectivesSniff.php
- PHPCompatibility/Sniffs/PHP/ForbiddenClosureUseVariableNamesSniff.php
- PHPCompatibility/Sniffs/PHP/NewFunctionArrayDereferencingSniff.php
- PHPCompatibility/Sniffs/PHP/NewFunctionParametersSniff.php
- PHPCompatibility/Sniffs/PHP/NewFunctionsSniff.php
- PHPCompatibility/Sniffs/PHP/NewIniDirectivesSniff.php
- PHPCompatibility/Sniffs/PHP/ParameterShadowSuperGlobalsSniff.php
- PHPCompatibility/Sniffs/PHP/RemovedFunctionParametersSniff.php
- PHPCompatibility/Sniffs/PHP/RequiredOptionalFunctionParametersSniff.php
Where possible, change `in_array()` calls to `isset()` by changing array values to array keys.
> Sniff speed: apply some efficiency fixes

- PHPCompatibility/Sniffs/PHP/NewClassesSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/NewClassesSniffTest.php
- PHPCompatibility/Tests/sniff-examples/new_classes.php
Refs:
* https://github.com/php/php-src/blob/600cb4b46755a9170eaa32606528a6908bc98975/UPGRADING#L231
* https://github.com/php/php-src/blob/3f53b02a53448ec5e7d2d0733668da92a9463730/UPGRADING#L106
* https://github.com/php/php-src/commit/d04917c7b361fd07e098fe29ae931fb6fac1d9e0
* https://github.com/php/php-src/commit/e823770515bd0530bd3c09ea273c720b4df33734
> PHP 7.3: NewClasses: account for new CompileError and JsonException

- PHPCompatibility/Sniffs/PHP/ForbiddenNamesSniff.php
- PHPCompatibility/Sniffs/PHP/InternalInterfacesSniff.php
- PHPCompatibility/Sniffs/PHP/NewClassesSniff.php
- PHPCompatibility/Sniffs/PHP/NewInterfacesSniff.php
- PHPCompatibility/Sniffs/PHP/NonStaticMagicMethodsSniff.php
- PHPCompatibility/Sniffs/PHP/ReservedFunctionNamesSniff.php
The `T_ANON_CLASS` token is a PHPCS native constant, not a back-filled constant.
> CS: remove unnecessary cs-ignore annotations

- PHPCompatibility/Sniffs/PHP/DeprecatedFunctionsSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/DeprecatedFunctionsSniffTest.php
- PHPCompatibility/Tests/sniff-examples/deprecated_functions.php
Refs:
* https://wiki.php.net/rfc/image2wbmp
* https://github.com/php/php-src/blob/3f53b02a53448ec5e7d2d0733668da92a9463730/UPGRADING#L162
* https://github.com/php/php-src/commit/3cbf594dfd0708dc36f1655c50e16fa963e61501
> PHP 7.3: DeprecatedFunctions: account for deprecation of image2wbmp()

- PHPCompatibility/Sniffs/PHP/DeprecatedFunctionsSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/DeprecatedFunctionsSniffTest.php
- PHPCompatibility/Tests/sniff-examples/deprecated_functions.php
Refs:
* https://wiki.php.net/rfc/deprecations_php_7_3#undocumented_mbstring_function_aliases
* https://github.com/php/php-src/blob/cf3b852109a88a11370d0207cd3b72a53b6a64c3/UPGRADING#L284-L300
* https://github.com/php/php-src/commit/e6016ab20d6699cac9441686903051b3a815cbba
> PHP 7.3: DeprecatedFunctions: add deprecation of undocumented Mbstring function aliases

- PHPCompatibility/Sniffs/PHP/MbstringReplaceEModifierSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/MbstringReplaceEModifierSniffTest.php
- PHPCompatibility/Tests/sniff-examples/mbstring_replace_e_modifier.php
> MbstringReplaceEModifier: also recognize the use of the /e modifier when alias functions are used

- PHPCompatibility/Tests/Sniffs/PHP/DeprecatedMagicAutoloadSniffTest.php
* Add `@group` annotations.
* Set a default value for the `$isTrait` parameter and leave it out in most cases in the data provider.
As the sniff also checks whether the function is declared in a namespace, the only two cases which are problematic, are the non-namespaced function declarations within a trait and an interface.
> DeprecatedMagicAutoload: minor improvements to the test case file

- PHPCompatibility/Sniffs/PHP/DeprecatedIniDirectivesSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/DeprecatedIniDirectivesSniffTest.php
- PHPCompatibility/Tests/sniff-examples/deprecated_ini_directives.php
> The pdo_odbc.db2_instance_name ini setting has been formally deprecated. It
has already been deprecated in the documentation since PHP 5.1.1.
Refs:
* https://wiki.php.net/rfc/deprecations_php_7_3#pdo_odbcdb2_instance_name_phpini_directive
* https://github.com/php/php-src/blob/cf3b852109a88a11370d0207cd3b72a53b6a64c3/UPGRADING#L302-L304
* https://github.com/php/php-src/commit/fb0e8c65b9d196db44c7d92890e3540f863b6c8b
> PHP 7.3: DeprecatedIniDirectives: add deprecation of pdo_odbc.db2_instance_name

- PHPCompatibility/Sniffs/PHP/NewIniDirectivesSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/NewIniDirectivesSniffTest.php
- PHPCompatibility/Tests/sniff-examples/new_ini_directives.php
> syslog.filter
> New INI to set syslog filter type to filter the logged messages. There are
3 supported filter types - all, no-ctrl and ascii. It is used only when
error_log is set to syslog.
Refs:
* https://github.com/php/php-src/blob/cf3b852109a88a11370d0207cd3b72a53b6a64c3/UPGRADING#L514-L517
* https://github.com/php/php-src/commit/2010c02e5c3c70880a53cb0403ce696708f4d590
* https://github.com/php/php-src/commit/c85504386d16f943cc79263187710a05cefea265
* https://github.com/php/php-src/commit/e5a99563363a656c06f836957002550ff7fdb720
> PHP 7.3: NewIniDirectives: add new syslog.filter

- PHPCompatibility/Sniffs/PHP/DeprecatedFunctionsSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/DeprecatedFunctionsSniffTest.php
- PHPCompatibility/Tests/sniff-examples/deprecated_functions.php
> The fgetss() function and the string.strip_tags stream filter have been deprecated.
This also affects the SplFileObject::fgetss() method and gzgetss() function.
Refs:
* https://wiki.php.net/rfc/deprecations_php_7_3#fgetss_function_and_stringstrip_tags_filter
* https://github.com/php/php-src/blob/cf3b852109a88a11370d0207cd3b72a53b6a64c3/UPGRADING#L320-L321
* https://github.com/php/php-src/commit/d9acfa45b849a9444ae5f341fd016137e4212066
> PHP 7.3: DeprecatedFunctions: add deprecation of fgetss() and gzgetss() functions

- PHPCompatibility/Sniffs/FunctionParameters/SetlocaleStringSniff.php
- PHPCompatibility/Tests/Sniffs/FunctionParameters/SetlocaleStringSniffTest.php
- PHPCompatibility/Tests/Sniffs/FunctionParameters/SetlocaleStringTestCases.inc
----
> "Support for the category parameter passed as a string has been removed.
> Only LC_* constants can be used as of this version [7.0.0]. "
Refs:
* http://php.net/manual/en/migration70.changed-functions.php#migration70.changed-functions.core
* http://php.net/manual/en/function.setlocale.php
* https://web.archive.org/web/20061114024645/http://www.php.net:80/manual/en/function.setlocale.php
> PHP 4.2/7.0: New sniff to detect passing string literal category to setlocale()

- PHPCompatibility/Sniffs/Lists/ShortListSniff.php
- PHPCompatibility/Tests/Sniffs/Lists/ShortListSniffTest.php
- PHPCompatibility/Tests/Sniffs/Lists/ShortListTestCases.inc
----
> The shorthand array syntax ([]) may now be used to destructure arrays for assignments (including within foreach), as an alternative to the existing list() syntax, which is still supported.
Refs:
* http://php.net/manual/en/migration71.new-features.php#migration71.new-features.symmetric-array-destructuring
* https://wiki.php.net/rfc/short_list_syntax
* https://github.com/php/php-src/commit/4f077aee836ad7d8335cf62629a8364bdf939db9
Fixes #248
> PHP 7.1: New sniff to detect short list syntax for symmetric array destructuring

- PHPCompatibility/Sniffs/FunctionParameters/FopenModeSniff.php
- PHPCompatibility/Tests/Sniffs/FunctionParameters/FopenModeSniffTest.php
- PHPCompatibility/Tests/Sniffs/FunctionParameters/FopenModeTestCases.inc
----
> Version | Description
> --- | ---
> 7.0.16, 7.1.2 | The `e` option were added.
> 5.2.6 | The `c` and `c+` options were added
Ref: http://php.net/manual/en/function.fopen.php#refsect1-function.fopen-changelog
> New sniff to detect new modes available to fopen()

- PHPCompatibility/Sniffs/FunctionParameters/GetClassNullSniff.php
- PHPCompatibility/Tests/Sniffs/FunctionParameters/GetClassNullSniffTest.php
- PHPCompatibility/Tests/Sniffs/FunctionParameters/GetClassNullTestCases.inc
----
> "Previously, passing NULL to the get_class() function would output the name of the enclosing class. This behaviour has now been removed, where an E_WARNING will be output instead.
> To achieve the same behaviour as before, the argument should simply be omitted."
Refs:
* http://php.net/manual/en/migration72.incompatible.php#migration72.incompatible.no-null-to-get_class
* https://wiki.php.net/rfc/get_class_disallow_null_parameter
* http://php.net/manual/en/function.get-class.php
Fixes #557
> PHP 7.2: New sniff to detect passing `null` to get_class()

- PHPCompatibility/Sniffs/FunctionParameters/NonCryptoHashSniff.php
- PHPCompatibility/Tests/Sniffs/FunctionParameters/NonCryptoHashSniffTest.php
- PHPCompatibility/Tests/Sniffs/FunctionParameters/NonCryptoHashTestCases.inc
----
> "The hash_hmac(), hash_hmac_file(), hash_pbkdf2(), and hash_init() (with HASH_HMAC) functions no longer accept non-cryptographic hashes."
Refs:
* http://php.net/manual/en/migration72.incompatible.php#migration72.incompatible.hash-functions
Fixes #559
> PHP 7.2: New sniff to detect usage of non-cryptographic hashes

- PHPCompatibility/Sniffs/PHP/NewGeneratorReturnSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/NewGeneratorReturnSniffTest.php
- PHPCompatibility/Tests/sniff-examples/new_generator_return.php
The sniff didn't take well enough into account that generator functions could be nested within other (anonymous) functions or could have other nested constructs within the generator within which a `return` statement was fine.
Previously, it would check if the `yield` had a (named) `function` scope and if not, if it had a anonymous function scope.
This caused the false positive as reported by @mjrider as for a `yield` in a closure nested within a named function, the named function would be examined, not the closure.
The fix in this PR changes that logic to find the deepest nested function òr closure within which the `yield` exist.
Additionally, this fix makes sure that the sniff doesn't get confused over `return` statements found in even deeper nested scopes, such as a closure nested …
> NewGeneratorReturn: bug fix for generator return with nested functions

- PHPCompatibility/Sniff.php
- PHPCompatibility/Sniffs/PHP/ForbiddenCallTimePassByReferenceSniff.php
- PHPCompatibility/Tests/BaseClass/GetFunctionParametersTest.php
- PHPCompatibility/Tests/Sniffs/PHP/ForbiddenCallTimePassByReferenceSniffTest.php
- PHPCompatibility/Tests/sniff-examples/call_time_pass_by_reference.php
- PHPCompatibility/Tests/sniff-examples/utility-functions/get_function_parameters.php
Inspired by upstream PHPCS PR https://github.com/squizlabs/PHP_CodeSniffer/pull/2109, I ran the upstream sniff against the unit test cases from PHPCompatibility and the PHPCompatibility sniff against the upstream unit test cases.
The PHPCompatibility sniff already took the test case which is addressed in the upstream PR into account.
All the same, it didn't catch the `$foo(&$myvar);` test case (line 25 PHPCS unit test case file) and it gave a false positive for `Hooks::run( [ &$updates ] );` (line 30 PHPCS unit test case file).
Both are now addressed in this PR.
This minor adjustments allows these functions also to be used for retrieving the function call parameters of calls to a closure contained in a variable, like so `$d( $a, $b );`.
Fixes the following: …
> ForbiddenCallTimePassByReference: fix some false positives and false negatives

- README.md
... as it appears to be no longer maintained.
This PR adds two new badges instead:
1. A badge displaying the minimum supported PHP version as per the `composer.json` file.
2. A badge showing the real PHP versions the code is tested against. This is a custom badge and will need to be manually updated if/when a new runtime to test against is added to the Travis script, but as this happens approximately once a year, that shouldn't be much of an issue.
[ci skip]
> Readme: replace PHPeye badge

- PHPCompatibility/Sniffs/PHP/NewFunctionsSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/NewFunctionsSniffTest.php
- PHPCompatibility/Tests/sniff-examples/new_functions.php
> Added sapi_windows_cp_set(), sapi_windows_cp_get(), sapi_windows_cp_is_utf8(), sapi_windows_cp_conv() for codepage handling.
Refs:
* https://github.com/php/php-src/blob/6acee09f40fd16320ccadc0f662033ddff75d053/UPGRADING#L251-L253
* php/php-src@3d3f11e
> In PHP 7.1.2: Added hash_hkdf() function, which implements the HMAC-based Derivation Function (HKDF) algorithm according to RFC 5869. The implementation combines the Extract and Expand steps.
Refs:
* https://github.com/php/php-src/blob/6acee09f40fd16320ccadc0f662033ddff75d053/UPGRADING#L261-L264
* php/php-src@4bf7ef0
> Added pcntl_signal_get_handler() that returns the current signal handler for a particular signal.
Refs:
* https://github.com/php/php-src/blob/6acee09f40fd16320ccadc0f662033ddff75d053/UPGRADING#L266-L268
* …
> PHP 7.1: NewFunctions: add more new functions

- PHPCompatibility/Sniffs/PHP/NewIniDirectivesSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/NewIniDirectivesSniffTest.php
- PHPCompatibility/Tests/sniff-examples/new_ini_directives.php
_Yeah_ for incomplete changelogs.
These changes are **not** explicitly mentioned in the `ini` section of the in the [`UPGRADING`](https://github.com/php/php-src/blob/PHP-7.1.21/UPGRADING) file for PHP 7.1 nor in the [Migrating to PHP 7.1.x](http://php.net/manual/en/migration71.php).
They are, however, annotated in the manual.
Refs:
* http://php.net/manual/en/ini.core.php#ini.sect.language-options
* https://github.com/php/php-src/commit/650c1c0a7d94d3bb052a93407b6e280df9c265a4
Refs:
* http://php.net/manual/en/outcontrol.configuration.php
* http://php.net/manual/en/session.configuration.php
* https://github.com/php/php-src/commit/a53a6b3fb4060c9c71a84b0acaaa0211777f6e17
> PHP 7.1: NewIniDirectives: add some more new directives

- PHPCompatibility/Sniffs/PHP/NewIniDirectivesSniff.php
- PHPCompatibility/Tests/Sniffs/PHP/NewIniDirectivesSniffTest.php
- PHPCompatibility/Tests/sniff-examples/new_ini_directives.php
> - session.cookie_samesite
>    New INI option to allow to set the SameSite directive for cookies. Defaults to "" (empty string), so no SameSite directive is set. Can be set to "Lax" or "Strict", which sets the respective SameSite directive.
Refs:
* https://wiki.php.net/rfc/same-site-cookie
* https://github.com/php/php-src/blob/d22ddd8cf12b5582b11dcba84d93f1b558ce30ae/UPGRADING#L524-L527
* https://github.com/php/php-src/commit/2b58ab23c6ad3301b31a2015f5faa31801147dfd
> PHP 7.3: NewIniDirectives: add new session ini directive

- PHPCompatibility/Sniffs/Lists/NewKeyedListSniff.php
- PHPCompatibility/Tests/Sniffs/Lists/NewKeyedListSniffTest.php
- PHPCompatibility/Tests/Sniffs/Lists/NewKeyedListTestCases.inc
> Support for keys in list()
>
> You can now specify keys in `list()`, or its new shorthand `[]` syntax. This enables destructuring of arrays with non-integer or non-sequential keys.
Refs:
* http://php.net/manual/en/migration71.new-features.php#migration71.new-features.support-for-keys-in-list
* https://wiki.php.net/rfc/list_keys
* https://github.com/php/php-src/commit/37c8bb58686b2d86f145ebe4fe39854f5951dcd7
Notes:
* An error will be thrown for each double arrow encountered. The error will be linked to the double arrow token to provide the closest indication of where the list key was found.
* The sniff has been set up to allow for easily extending it to re-use the logic to a) determine the open/close tokens and b) to check within a list construct.
I already have another sniff lined up …
> PHP 7.1: New sniff to detect keys in list()

- PHPCompatibility/Sniffs/FunctionParameters/NegativeStringOffsetSniff.php
- PHPCompatibility/Tests/Sniffs/FunctionParameters/NegativeStringOffsetSniffTest.php
- PHPCompatibility/Tests/Sniffs/FunctionParameters/NegativeStringOffsetTestCases.inc
> "Support for negative string offsets has been added to the string manipulation functions accepting offsets [...]. In such cases, a negative offset is interpreted as being an offset from the end of the string."
Refs:
* http://php.net/manual/en/migration71.new-features.php#migration71.new-features.support-for-negative-string-offsets
* https://wiki.php.net/rfc/negative-string-offsets
Fixes part 1 of issue #253
> PHP 7.1: New sniff to detect negative string offsets being passed as parameters

- PHPCompatibility/Sniffs/FunctionParameters/IconvEncodingSniff.php
- PHPCompatibility/Tests/Sniffs/FunctionParameters/IconvEncodingSniffTest.php
- PHPCompatibility/Tests/Sniffs/FunctionParameters/IconvEncodingTestCases.inc
> "The iconv and mbstring configuration options related to encoding have been deprecated in favour of default_charset."
Refs:
* http://php.net/manual/en/migration56.deprecated.php#migration56.deprecated.iconv-mbstring-encoding
* https://wiki.php.net/rfc/default_encoding
**Note:**
As it is unclear which MBString functions to target, the sniff only checks the affected `iconv` function.
Based on the commit and the other documentation, I get the impression that for MBString, this only affects the ini directives.
Fixes #475
> PHP 5.6: New sniff to detect passing deprecated $type values to iconv_get_encoding

- PHPCompatibility/Sniff.php
- PHPCompatibility/Sniffs/FunctionParameters/ArrayReduceInitialTypeSniff.php
- PHPCompatibility/Tests/BaseClass/IsNumericCalculationTest.php
- PHPCompatibility/Tests/BaseClass/TestHelperPHPCompatibility.php
- PHPCompatibility/Tests/Sniffs/FunctionParameters/ArrayReduceInitialTypeSniffTest.php
- PHPCompatibility/Tests/Sniffs/FunctionParameters/ArrayReduceInitialTypeTestCases.inc
- PHPCompatibility/Tests/sniff-examples/utility-functions/is_numeric_calculation.php
> Version | Description
> --- | ---
> 5.3.0 | Changed initial to allow mixed, previously integer.
Refs:
* http://php.net/manual/en/function.array-reduce.php#refsect1-function.array-reduce-changelog
* http://php.net/manual/en/migration53.other.php#migration53.other
Fixes #649
----
In support of this sniff, a new utility method is introduced. `isNumericCalculation()`
This utility function can determine whether the tokens between a `$start` and `$end` token would be evaluated as a numeric calculation by PHP.
Mainly useful for verifying function call parameters, where a numeric value is expected, but a calculation can be passed to create the number.
> PHP 5.3: New sniff to detect a non-integer $initial parameter value passed to array_reduce()

- PHPCompatibility/Sniffs/Syntax/NewFlexibleHeredocNowdocSniff.php
- PHPCompatibility/Tests/BaseSniffTest.php
- PHPCompatibility/Tests/Sniffs/Syntax/NewFlexibleHeredocNowdocUnitTest.1.inc
- PHPCompatibility/Tests/Sniffs/Syntax/NewFlexibleHeredocNowdocUnitTest.2.inc
- PHPCompatibility/Tests/Sniffs/Syntax/NewFlexibleHeredocNowdocUnitTest.3.inc
- PHPCompatibility/Tests/Sniffs/Syntax/NewFlexibleHeredocNowdocUnitTest.4.inc
- PHPCompatibility/Tests/Sniffs/Syntax/NewFlexibleHeredocNowdocUnitTest.5.inc
- PHPCompatibility/Tests/Sniffs/Syntax/NewFlexibleHeredocNowdocUnitTest.6.inc
- PHPCompatibility/Tests/Sniffs/Syntax/NewFlexibleHeredocNowdocUnitTest.7.inc
- PHPCompatibility/Tests/Sniffs/Syntax/NewFlexibleHeredocNowdocUnitTest.8.inc
- PHPCompatibility/Tests/Sniffs/Syntax/NewFlexibleHeredocNowdocUnitTest.9.inc
- PHPCompatibility/Tests/Sniffs/Syntax/NewFlexibleHeredocNowdocUnitTest.php
> Implemented flexible heredoc and nowdoc syntax: The closing marker for doc strings is no longer required to be followed by a semicolon or newline.
> Additionally the closing marker may be indented, in which case the indentation will be stripped from all lines in the doc string.
> Due to the introduction of flexible heredoc/nowdoc syntax, doc strings that contain the ending label inside their body may cause syntax errors or change in interpretation. For example in
> ```php
>         $str = <<<FOO
>         abcdefg
>             FOO
>         FOO;
> ```
> the indented occurrence of "FOO" did not previously have any special meaning. Now it will be interpreted as the end of the heredoc string and the following "FOO;" will cause a syntax error. This issue can always be resolved by choosing …
> PHP 7.3: New sniff to detect flexible heredoc/nowdoc cross-version incompatibilities

- PHPCompatibility/Sniffs/ParameterValues/NewPackFormatSniff.php
- PHPCompatibility/Tests/BaseSniffTest.php
- PHPCompatibility/Tests/Sniffs/ParameterValues/NewPackFormatUnitTest.inc
- PHPCompatibility/Tests/Sniffs/ParameterValues/NewPackFormatUnitTest.php
> Version | Description
> --- | ---
> 7.0.15,7.1.1 | The "e", "E", "g" and "G" codes were added to enable byte order support for float and double.
> 5.6.3 | The "q", "Q", "J" and "P" codes were added to enable working with 64-bit numbers.
> 5.5.0 | The "Z" code was added with equivalent functionality to "a" for Perl compatibility.
Ref: http://php.net/manual/en/function.pack.php#refsect1-function.pack-changelog
> New sniff to detect incompatible $formats passed to pack()

- PHPCompatibility/Sniffs/FunctionNameRestrictions/RemovedNamespacedAssertSniff.php
- PHPCompatibility/Tests/BaseSniffTest.php
- PHPCompatibility/Tests/Sniffs/FunctionNameRestrictions/RemovedNamespacedAssertUnitTest.1.inc
- PHPCompatibility/Tests/Sniffs/FunctionNameRestrictions/RemovedNamespacedAssertUnitTest.2.inc
- PHPCompatibility/Tests/Sniffs/FunctionNameRestrictions/RemovedNamespacedAssertUnitTest.php
>  Declaring a function called assert() inside a namespace is deprecated.
>  The assert() function is subject to special handling by the engine, which may lead to inconsistent behavior when defining a namespaced function with the same name.
Refs:
* https://wiki.php.net/rfc/deprecations_php_7_3#defining_a_free-standing_assert_function
* https://github.com/php/php-src/blob/cf3b852109a88a11370d0207cd3b72a53b6a64c3/UPGRADING#L267-L270
* php/php-src@5c4047b
Fixes #718 (last one of the deprecations which needed addressing)
---
Note: This sniff has already been adjusted for the new repo structure.
> PHP 7.3: New sniff to recognize deprecated assert() function declarations

- PHPCompatibility/Sniffs/Lists/NewListReferenceAssignmentSniff.php
- PHPCompatibility/Tests/Sniffs/Lists/NewListReferenceAssignmentUnitTest.inc
- PHPCompatibility/Tests/Sniffs/Lists/NewListReferenceAssignmentUnitTest.php
> Array destructuring now supports reference assignments using the syntax `[&$a, [$b, &$c]] = $d`. The same is also supported for `list()`.
Refs:
* https://wiki.php.net/rfc/list_reference_assignment
* https://github.com/php/php-src/commit/6d4de4cf0582cf33848826ab78aae58077dc2dea
* https://github.com/php/php-src/blob/9b89b09b24ffe29c2b6de24c3d9b21df4f2a9de0/UPGRADING#L58-L60
Now #655 has been merged, this PR can be pulled as it extends the sniff added in #655 as it needs the same basic logic.
> PHP 7.3: New sniff to detect references in list constructs

- PHPCompatibility/Sniff.php
- PHPCompatibility/Sniffs/ControlStructures/NewForeachExpressionReferencingSniff.php
- PHPCompatibility/Sniffs/PHP/EmptyNonVariableSniff.php
- PHPCompatibility/Tests/Sniffs/ControlStructures/NewForeachExpressionReferencingUnitTest.inc
- PHPCompatibility/Tests/Sniffs/ControlStructures/NewForeachExpressionReferencingUnitTest.php
> 5.5.0 	Referencing of $value is supported for expressions. Formerly, only variables have been supported.
> Before PHP 5.5.0, referencing $value is only possible if the iterated array can be referenced (i.e. if it is a variable).
Ref: http://php.net/manual/en/control-structures.foreach.php
**Note:** this change is not mentioned anywhere in the PHP 5.5 changelog, but tests show it has been implemented and that the documentation is correct.
See: https://3v4l.org/gFvaZ
----
Updated the PR after I found a false positive. The "is this a variable ?" determination is now based on the same code as the `EmptyNonVariable` sniff uses. This code has been abstracted to a utility method in the `Sniff` class.
> PHP 5.5: New sniff to detect referenced expressions prior to PHP 5.5

- PHPCompatibility/Sniffs/ControlStructures/NewListInForeachSniff.php
- PHPCompatibility/Tests/Sniffs/ControlStructures/NewListInForeachUnitTest.inc
- PHPCompatibility/Tests/Sniffs/ControlStructures/NewListInForeachUnitTest.php
> `foreach` now supports `list()`
>
> The `foreach` control structure now supports unpacking nested arrays into separate variables via the `list()` construct.
Refs:
* http://php.net/manual/en/migration55.new-features.php#migration55.new-features.foreach-list
* http://php.net/manual/en/control-structures.foreach.php#control-structures.foreach.list
* https://wiki.php.net/rfc/foreachlist
> PHP 5.5: New sniff to detect unpacking nested arrays with list in foreach

- PHPCompatibility/Sniffs/Lists/AssignmentOrderSniff.php
- PHPCompatibility/Tests/Sniffs/Lists/AssignmentOrderUnitTest.inc
- PHPCompatibility/Tests/Sniffs/Lists/AssignmentOrderUnitTest.php
>  `list()` no longer assigns variables in reverse order
>
> `list()` will now assign values to variables in the order they are defined, rather than reverse order. In general, this only affects the case where `list()` is being used in conjunction with the array [] operator
Refs:
* http://php.net/manual/en/migration70.incompatible.php#migration70.incompatible.variable-handling.list.order
* https://wiki.php.net/rfc/abstract_syntax_tree#changes_to_list
* http://php.net/manual/en/function.list.php
**Note:** in contrast to the changelog entry, this actually affects all lists which use the same variable twice in the `list()` construct, so that is the premise the sniff has been based on now.
See: https://3v4l.org/LpUl6
**Open question:**
I've set the sniff up now to throw an error if non-unique …
> PHP 7.0: New sniff to detect list()s affected by the assignment order change

- .gitattributes
- .github/CONTRIBUTING.md
- .gitignore
- CHANGELOG.md
- README.md
- composer.json
See: https://github.com/wimg/PHPCompatibility/milestone/24
* Add detailed changelog for version 9.0.0. Includes entry for - as of yet unmerged - PR #739.
* Replace section about upgrading to v 8.0.0 with section about upgrading to v 9.0.0.
* Remove link to @wimg's blog as the information on it is out of date.
* Add information about the polyfill based rulesets.
* Adjust the information about specific sub-rulesets to cover the polyfill based rulesets.
* Mention the unit test `@group` annotations.
* `.gitattributes`: export-ignore the git files.
* `.gitignore`: add the new PHPCS 3.1+ local override file.
* `composer.json`: minor textual improvement to the project description.
[ci skip]
> Changelog and other documentation updates for version 9.0.0

- PHPCompatibility/Sniffs/TypeCasts/NewTypeCastsSniff.php
- PHPCompatibility/Tests/TypeCasts/NewTypeCastsUnitTest.inc
- PHPCompatibility/Tests/TypeCasts/NewTypeCastsUnitTest.php
A fix for upstream issue #1574 has been committed to PHPCS and will be included in the PHPCS 3.4.0 release.
This PR:
* Makes a work-around used for the issue so far conditional on the PHPCS version detected.
* Recognize `b'singlequoted'` also as binary string casts.
* Adjusts the unit tests to match (for the single quoted fix) and add a test with a double quotes interpolated string.
* Includes fixing test file copy/paste error.
**Note**: This PR fixes the current Travis build failure against the `dev-master` branch.
> NewTypeCasts: updated for compatibility with PHPCS 3.4.0

- PHPCompatibility/Sniffs/IniDirectives/NewIniDirectivesSniff.php
- PHPCompatibility/Tests/IniDirectives/NewIniDirectivesUnitTest.inc
- PHPCompatibility/Tests/IniDirectives/NewIniDirectivesUnitTest.php
The `imap.enable_insecure_rsh` ini directive was introduced in PHP 7.1.25, 7.2.13, 7.3.0 simultaneously.
Refs:
* http://php.net/manual/en/migration73.incompatible.php#migration73.incompatible.imap
> PHP 7.3: NewIniDirectives: account for (more) new ini directives

- PHPCompatibility/Sniffs/FunctionUse/NewFunctionsSniff.php
- PHPCompatibility/Tests/FunctionUse/NewFunctionsUnitTest.inc
- PHPCompatibility/Tests/FunctionUse/NewFunctionsUnitTest.php
Refs:
* https://github.com/php/php-src/blob/cb00ca7cfeea8af8083d28d7bc66957c61899732/UPGRADING#L456-L460
* php/php-src#2640
Looks like the `sapi_add_request_header()` function is an internal C function and not exposed.
> PHP 7.3: NewFunctions: more updates

- PHPCompatibility/Sniff.php
- PHPCompatibility/Sniffs/FunctionNameRestrictions/RemovedMagicAutoloadSniff.php
- PHPCompatibility/Util/Tests/Core/IsClassPropertyUnitTest.inc
- PHPCompatibility/Util/Tests/Core/IsClassPropertyUnitTest.php
When a class would be nested in parenthesis, the method did not recognize class properties properly.
To check for this without code duplication, the return of the `Sniff::validDirectScope()` method has changed. It used to always return a boolean. Now it will return `false` if not in a valid direct scope and the `$stackPtr` to the scope if it is.
Includes unit test.
> Sniff::isClassProperty: bug fix

- PHPCompatibility/Tests/InitialValue/NewHeredocUnitTest.php
While PHPCS 2.5.1 is not currently covered by the Travis matrix, the tests can still be run on it and for this particular sniff they will fail due to a bug outside of our control (bug in the PHPCS Tokenizer in 2.5.1).
> NewHeredocUnitTest: add test skipping for PHPCS 2.5.1

- PHPCompatibility/Sniffs/FunctionNameRestrictions/ReservedFunctionNamesSniff.php
- PHPCompatibility/Tests/FunctionNameRestrictions/ReservedFunctionNamesUnitTest.inc
- PHPCompatibility/Tests/FunctionNameRestrictions/ReservedFunctionNamesUnitTest.php
Loosely related to #751.
When this sniff would run on PHPCS 2.3.x and the function being examined would be in an anonymous class, the class name used in the error message would be incorrect as the `getDeclarationName()` method would use the first `T_STRING` found, which in the case of an anonymous class would be the name of the first constant or function within the anonymous class.
Additionally, the upstream `processTokenWithinScope()` method is called for each valid scope a function is in, so for a function in a nested anonymous class, the method would be called twice and the error would also be thrown twice, though with two different class names - both wrong.
This PR fixes both these issues.
Includes additional unit test for this issue, though as the class/method names being passed to …
> ReservedFunctionNames: bugfix for PHPCS 2.3.x

- .travis.yml
- README.md
Once PHP 7.3-beta came out, the `nightly` build on Travis became PHP 7.4-dev and the builds haven't been tested against PHP 7.3 for months now.
Luckily, Travis has, in the mean time, deemed it appropriate to set up a PHP 7.3 alias now RC3 is out, so I've added PHP 7.3 to the matrix.
**Important note**:
PHP 7.3+ is only fully supported in combination with PHPCS 2.9.2 and 3.3.1+.
When running PHPCompatibility against PHPCS < 2.9.2 or PHPCS 3.x < 3.3.1, PHP warnings about using `continue` within `switch` will be thrown, but will in most cases not affect the functioning of the sniffs.
While on PHPCS 2.x, the tests won't fail, on PHPCS 3.x < 3.3.1, they will, as the error handling during PHPCS runs has changed in PHPCS 3.x.
In other words, for PHP 7.3, we can safely run the unit tests on PHPCS …
> Build/Travis: test builds against PHP 7.3

- PHPCompatibility/Sniffs/MethodUse/NewDirectCallsToCloneSniff.php
- PHPCompatibility/Tests/MethodUse/NewDirectCallsToCloneUnitTest.inc
- PHPCompatibility/Tests/MethodUse/NewDirectCallsToCloneUnitTest.php
- phpcs.xml.dist
> Directly calling __clone is allowed
>
> Doing calls like $obj->__clone() is now allowed. This was the only magic method that had a compile-time check preventing some calls to it, which doesn't make sense. If we allow all other magic methods to be called, there's no reason to forbid this one.
Ref: https://wiki.php.net/rfc/abstract_syntax_tree#directly_calling_clone_is_allowed
Fixes #629
Note: PR includes minor adjustments to the PHPCompatibility native PHPCS ruleset to allow for the new docblock format as per #734. This will be further addressed in a separate PR dedicated to that issue.
> PHP 7.0: New sniff to detect direct calls to __clone()

- PHPCompatibility/Sniffs/Variables/NewThisUsageLimitationsSniff.php
- PHPCompatibility/Tests/Variables/NewThisUsageLimitationsUnitTest.inc
- PHPCompatibility/Tests/Variables/NewThisUsageLimitationsUnitTest.php
- phpcs.xml.dist
> Inconsistency fixes to $this
>
> Whilst $this is considered a special variable in PHP, it lacked proper checks to ensure it wasn't used as a variable name or reassigned. This has now been rectified to ensure that $this cannot be a user-defined variable, reassigned to a different value, or be globalised.
Refs:
* https://wiki.php.net/rfc/this_var
* http://php.net/manual/en/migration71.other-changes.php#migration71.other-changes.inconsistency-fixes-to-this
Notes:
* This sniff only addresses those situations which did *not* throw an error prior to PHP 7.1.
In other words, "_Using $this as static variable._" is not sniffed for (error _message_ change only).
* There is one exception to that, which is using `$this` as a closure parameter, which doesn't throw an error in PHP 7.0 until 7.0.7, so …
> PHP 7.1: New "NewThisUsageLimitations" sniff

- PHPCompatibility/Sniffs/Interfaces/InternalInterfacesSniff.php
- PHPCompatibility/Sniffs/Interfaces/NewInterfacesSniff.php
- PHPCompatibility/Tests/Interfaces/InternalInterfacesUnitTest.inc
- PHPCompatibility/Tests/Interfaces/NewInterfacesUnitTest.inc
Recognize classes implementing PHP native interfaces prefixed with a `\` (to indicate global namespace).
Includes (adjusted) unit tests.
> Internal/NewInterfaces: bug fix - recognize implemented interfaces prefixed with \

- PHPCompatibility/Sniffs/Variables/ForbiddenThisUseContextsSniff.php
- PHPCompatibility/Tests/Variables/ForbiddenThisUseContextsUnitTest.inc
- PHPCompatibility/Tests/Variables/ForbiddenThisUseContextsUnitTest.php
For classes which implement the `ArrayAccess` interface, such as the `ArrayObject` class, using `$this['key']` is a perfectly fine, working syntax and unsetting an item in the object using that syntax will still work and is unaffected by the changes in PHP 7.1.
The sniff, however, would throw a false positive for this.
This PR fixes that.
Fixes #780
> ForbiddenThisUseContexts: allow for array access

- .travis.yml
PHPUnit 8 adds `void` return type declarations to the PHPUnit methods used by PHPCS, making it neigh impossible to make the unit test suite cross-version compatible for the PHP versions supported by PHPCompatibility.
As of the recent update to the Travis images, the images for PHP 7.2+ now ship with PHPUnit 8 which causes the unit tests to fail.
Officially, PHPUnit 7 is compatible with PHP 7.1, 7.2 and 7.3.
Ref: https://phpunit.de/supported-versions.html
So, for Travis images which come natively with PHPUnit 8 (PHP >= 7.2), PHPUnit 7 needs to be installed via Composer.
As PHP 7.3 has been released, the build to test code coverage should be run on PHP 7.3.
This should raise the code coverage as for, for instance, the `FlexibleHeredocNowdoc` sniff, code coverage for a significant part of …
> Travis: test against PHP 7.4, not 8.0 and fix PHPUnit failing

- README.md
- composer.json
Composer treats minors before 1.0.0 as majors. As the DealerDirect plugin has released version 0.5.0 a while back, we should recommend for people to use the latest version instead.
Refs:
* https://github.com/Dealerdirect/phpcodesniffer-composer-installer/releases/tag/v0.5.0
* https://getcomposer.org/doc/articles/versions.md#caret-version-range-
> Composer: update recommended Composer PHPCS installer version

- PHPCompatibility/Sniff.php
You learn something new every day. Never came across this function before, but definitely simplifies the `Sniff::arrayKeysToLowercase()` method.
Ref: https://php.net/manual/en/function.array-change-key-case.php
> Clean up: use array_change_key_case()

- PHPCompatibility/Sniffs/FunctionUse/NewFunctionsSniff.php
- PHPCompatibility/Tests/FunctionUse/NewFunctionsUnitTest.inc
- PHPCompatibility/Tests/FunctionUse/NewFunctionsUnitTest.php
Refs:
* https://wiki.php.net/rfc/mb_str_split
* https://github.com/php/php-src/commit/d77ad27415a34e4f5908cb262567b7b6f0eca17f
> PHP 7.4/NewFunctions: detect new mb_str_split()

- PHPCompatibility/Sniff.php
- PHPCompatibility/Sniffs/Operators/NewShortTernarySniff.php
- PHPCompatibility/Sniffs/Operators/RemovedTernaryAssociativitySniff.php
- PHPCompatibility/Tests/Operators/RemovedTernaryAssociativityUnitTest.inc
- PHPCompatibility/Tests/Operators/RemovedTernaryAssociativityUnitTest.php
PHP 7.4 deprecates nesting of ternaries without explicit use of parentheses.
PHP 8.0 will remove the (left-)associativity of ternaries completely. This will become a compile-time error.
Refs:
* https://wiki.php.net/rfc/ternary_associativity
* php/php-src@09ea55c (PHP 7.4 deprecation)
* https://gist.github.com/nikic/b6214f87b0e4a7c6fe26919ac849194f
To test this sniff, I have run it over some 200.000 files. While I can't say for sure whether there were any missed problem cases (false negatives), all the issues detected by the sniff were actual cases of nested ternaries which would become problematic in PHP 7.4/8.0 (and most, if not all, were bugs).
---
This PR includes adding a new `Sniff::isShortTernary()` method to determine whether a ternary is a …
> PHP 7.4/8.0: new RemovedTernaryAssociativity sniff

- PHPCompatibility/Sniffs/Extensions/RemovedExtensionsSniff.php
- PHPCompatibility/Tests/Extensions/RemovedExtensionsUnitTest.inc
- PHPCompatibility/Tests/Extensions/RemovedExtensionsUnitTest.php
We have a function in our code, for example `pfproduct_update()` which is being caught by the `pfpro` sniff. Adding the `_` should fix this, as it did for mysql in https://github.com/PHPCompatibility/PHPCompatibility/issues/7
> pfpro sniff is conflicting with some custom code

- PHPCompatibility/Sniffs/Classes/NewClassesSniff.php
- PHPCompatibility/Tests/Classes/NewClassesUnitTest.inc
- PHPCompatibility/Tests/Classes/NewClassesUnitTest.php
> - Reflection:
>    A new ReflectionReference class has been added, which allows detecting
>    references and comparing them for identity.
Refs:
* https://wiki.php.net/rfc/reference_reflection
* https://github.com/php/php-src/blob/42cc58ff7b2fee1c17a00dc77a4873552ffb577f/UPGRADING#L388-L391
* https://github.com/php/php-src/pull/3550
* https://github.com/php/php-src/commit/6347f0b937cc3fb3edb38003a41f3f9e8608831d
> PHP 7.4: NewClasses: add ReflectionReference class

- PHPCompatibility/Sniffs/FunctionUse/NewFunctionsSniff.php
- PHPCompatibility/Tests/FunctionUse/NewFunctionsUnitTest.inc
- PHPCompatibility/Tests/FunctionUse/NewFunctionsUnitTest.php
> - Core:
>    Added `get_mangled_object_vars($object)` function, which returns the mangled
>    object properties. It returns the same result as `(array) $object`, with the
>    exception that it ignores overloaded array casts, such as used by
>    `ArrayObject`.
>
> - OpenSSL:
>    Added `openssl_x509_verify(mixed cert, mixed key)` function that verifies the
>    signature of the certificate using a public key. A wrapper around the
>    OpenSSL's `X509_verify()` function.
>    See <https://github.com/php/php-src/pull/3624>.
>
> - Pcntl:
>    Added bool `pcntl_unshare(int flags)` function which allows to dissociate
>    parts of the process execution context which are currently being shared with
>    other processes. Explicitly, it allows you to unshare the mount, IPC, UTS,
>    network, …
> PHP 7.4: NewFunctions: add various new functions

- PHPCompatibility/Sniffs/Classes/RemovedOrphanedParentSniff.php
- PHPCompatibility/Tests/Classes/RemovedOrphanedParentUnitTest.inc
- PHPCompatibility/Tests/Classes/RemovedOrphanedParentUnitTest.php
> - Core
>    Using "parent" inside a class without parent is deprecated, and will throw
>    a compile-time error in the future. Currently an error will only be
>    generated if/when the parent is accessed at run-time.
Refs:
* https://github.com/php/php-src/blob/42cc58ff7b2fee1c17a00dc77a4873552ffb577f/UPGRADING#L303
* https://github.com/php/php-src/pull/3404
* https://github.com/php/php-src/pull/3564
* https://github.com/php/php-src/commit/a9e6667817c38f22f4645ec5b4e5c6b0e4b928fa (originally committed as hard compile time error)
* https://github.com/php/php-src/commit/deb44d405eb27a6654ad9a57c1e5f641218b22a4 (reverted back to deprecation error)
Loosely related to #808
---
I've opted to add this sniff to the `Classes` category as the use of the `parent` keyword in a class without parent …
> PHP 7.4: new RemovedOrphanedParent sniff

- PHPCompatibility/Sniffs/FunctionUse/RequiredToOptionalFunctionParametersSniff.php
- PHPCompatibility/Tests/FunctionUse/RequiredToOptionalFunctionParametersUnitTest.inc
- PHPCompatibility/Tests/FunctionUse/RequiredToOptionalFunctionParametersUnitTest.php
> array_merge() and array_merge_recursive() may now be called without any
> arguments, in which case they will return an empty array. This is useful
> in conjunction with the spread operator, e.g. array_merge(...$arrays).
Refs:
* https://github.com/php/php-src/blob/42cc58ff7b2fee1c17a00dc77a4873552ffb577f/UPGRADING#L276
* https://www.php.net/manual/en/function.array-merge.php
* https://www.php.net/manual/en/function.array-merge-recursive.php
* https://github.com/php/php-src/pull/4175
* https://github.com/php/php-src/commit/77cf3d7b1100dbb2b441b2a75f21b4e8ee0cb9b1
Loosely related to #808
> PHP 7.4: RequiredToOptionalFunctionParameters: account for new optional array_merge() parameters

- PHPCompatibility/Sniffs/FunctionUse/NewFunctionParametersSniff.php
- PHPCompatibility/Tests/FunctionUse/NewFunctionParametersUnitTest.inc
- PHPCompatibility/Tests/FunctionUse/NewFunctionParametersUnitTest.php
> - PCRE:
>   The preg_replace_callback() and preg_replace_callback_array() functions now
>   accept an additional $flags argument, with support for the
>   PREG_OFFSET_CAPTURE and PREG_UNMATCHED_AS_NULL flags. This influences the
>   format of the matches array passed to to the callback function.
Refs:
* https://github.com/php/php-src/blob/42cc58ff7b2fee1c17a00dc77a4873552ffb577f/UPGRADING#L244
* https://bugs.php.net/bug.php?id=77094
* https://github.com/php/php-src/pull/3958
* https://github.com/php/php-src/commit/12bcdd68b421a9da50f7f56ea361003997819675
Loosely related to #808
> PHP 7.4: NewFunctionParameters: account for new PCRE function parameters

- PHPCompatibility/Sniff.php
- PHPCompatibility/Sniffs/Operators/ChangedConcatOperatorPrecedenceSniff.php
- PHPCompatibility/Tests/Operators/ChangedConcatOperatorPrecedenceUnitTest.inc
- PHPCompatibility/Tests/Operators/ChangedConcatOperatorPrecedenceUnitTest.php
As of PHP 8.0, the operator precedence of concatenation will be lowered, with deprecation notices being thrown as of PHP 7.4 for unparenthesized expressions containing an '.' before a '+' or '-'.
Refs:
* https://wiki.php.net/rfc/concatenation_precedence
* php/php-src@3b23694 (PHP 7.4 deprecation)
* php/php-src@61ee869 (PHP 8.0 precedence change)
Notes:
- I've not been able to come up with a valid unit test which would involve `&` as a reference, but I suspect this should be accounted for all the same, so the sniff does account for it.
**NOTE**: the name of the sniff does not comply with the "normal" naming pattern, but I'm not sure what would be a more appropriate name `ForbiddenConcatBeforePlusMinusWithoutParenthesis` seems a bit overly long, just as …
> PHP 7.4/8.0: new ChangedConcatOperatorPrecedence sniff

- PHPCompatibility/Sniffs/LanguageConstructs/NewLanguageConstructsSniff.php
- PHPCompatibility/Tests/LanguageConstructs/NewLanguageConstructsUnitTest.php
The `T_ELLIPSIS` or spread operator can be used for both variadic functions as well as for argument unpacking. Support for both was added in PHP 5.6.
In PHP 7.4, a third use case is added: unpacking arrays at array declaration.
This minor change is intended to make the language of the error message clearer so it will be applicable to all use-cases.
Related #808
> NewLanguageConstructs: improve T_ELLIPSIS error message text

- .travis.yml
- phpcs.xml.dist
As the code base as-is, is currently clean, except for two warnings which are typical acceptable situations, let's explicitly ignore those two and fail builds on new CS warnings being introduced to keep the codebase properly clean.
> Build: whitelist two minor issues and don't ignore warnings

- PHPCompatibility/Sniffs/FunctionDeclarations/NewExceptionsFromToStringSniff.php
- PHPCompatibility/Tests/FunctionDeclarations/NewExceptionsFromToStringUnitTest.inc
- PHPCompatibility/Tests/FunctionDeclarations/NewExceptionsFromToStringUnitTest.php
> As of PHP 7.4, throwing exceptions from __toString() is now permitted. Previously this resulted in a fatal error. Existing recoverable fatals in string conversions have been converted to Error exceptions.
Refs:
* https://wiki.php.net/rfc/tostring_exceptions
* https://github.com/php/php-src/blob/374f7699821eb723a3a82a9854d18c0530b9d4e9/UPGRADING#L190
* https://github.com/php/php-src/commit/a31f46421d7bf6f55dd9ac5876b8e2eacf7e0708
Related #808
> PHP 7.4: new NewExceptionsFromToString sniff

- PHPCompatibility/Sniffs/Classes/NewTypedPropertiesSniff.php
- PHPCompatibility/Tests/Classes/NewTypedPropertiesUnitTest.inc
- PHPCompatibility/Tests/Classes/NewTypedPropertiesUnitTest.php
PHP 7.4 will be introducing support for runtime-enforced first-class property type declarations.
Refs:
* https://wiki.php.net/rfc/typed_properties_v2
* https://github.com/php/php-src/commit/e219ec144ef6682b71e135fd18654ee1bb4676b4
This PR introduces a new sniff to detect the use of these and report an error if PHP < 7.4 is intended to still be supported.
The PHP 7.4 implementation does not allow for properties with the `void` or `callable` type.
If these are detected and PHP 7.4 is supposed to be supported, an error will be thrown as well.
Related #808
> PHP 7.4: new NewTypedProperties sniff

- PHPCompatibility/Sniffs/Classes/ForbiddenAbstractPrivateMethodsSniff.php
- PHPCompatibility/Tests/Classes/ForbiddenAbstractPrivateMethodsUnitTest.inc
- PHPCompatibility/Tests/Classes/ForbiddenAbstractPrivateMethodsUnitTest.php
> Abstract private methods were supported between PHP 5.0.0 and PHP 5.0.4, but were then disallowed on the grounds that the behaviours of private and abstract are mutually exclusive.
Ref:
* https://www.php.net/manual/en/migration51.oop.php#migration51.oop-methods
Note: the tests cannot be run on PHPCS 2.3.x in combination with PHP < 5.4.
> PHP 5.1: new ForbiddenAbstractPrivateMethods sniff

- PHPCompatibility/Sniffs/FunctionDeclarations/ForbiddenToStringParametersSniff.php
- PHPCompatibility/Tests/FunctionDeclarations/ForbiddenToStringParametersUnitTest.inc
- PHPCompatibility/Tests/FunctionDeclarations/ForbiddenToStringParametersUnitTest.php
> The __toString() magic method can no longer accept arguments.
Ref: https://www.php.net/manual/en/migration53.incompatible.php
---
Potential additional enhancement which could be added (now or later):
* Check whether direct calls to `__toString()` methods pass arguments, i.e. `self::__toString($param)`, `$obj->__toString($param)`.
> PHP 5.3: new ForbiddenToStringParameters sniff

- PHPCompatibility/Sniff.php
- PHPCompatibility/Sniffs/ControlStructures/NewExecutionDirectivesSniff.php
- PHPCompatibility/Sniffs/Keywords/NewKeywordsSniff.php
- PHPCompatibility/Sniffs/Lists/NewListReferenceAssignmentSniff.php
- PHPCompatibility/Tests/ControlStructures/ForbiddenBreakContinueVariableArgumentsUnitTest.php
- phpcs.xml.dist
1. Add the `MultipleStatementAlignment` sniff
The code base basically already complies with this rule, which demands that the assignment operators for blocks of variable assignments are aligned.
When an assignment is not in a block, there should be exactly one space between the variable and the assignment.
Includes fixing up the code base for the very few places where the code didn't comply yet.
2. Add the `IncludingFile` sniff
Again, the code base already complies with this rule, safe for the unit test bootstrap, in which case it is ok that the code doesn't comply.
Includes one minor consistency fix, prefixing a global constant when used with a namespace separator to indicate global namespace.
> CS: add two new rules

- PHPCompatibility/Sniffs/Extensions/RemovedExtensionsSniff.php
- PHPCompatibility/Sniffs/FunctionUse/RemovedFunctionsSniff.php
- PHPCompatibility/Sniffs/IniDirectives/RemovedIniDirectivesSniff.php
- PHPCompatibility/Tests/Extensions/RemovedExtensionsUnitTest.php
- PHPCompatibility/Tests/FunctionUse/RemovedFunctionsUnitTest.inc
- PHPCompatibility/Tests/FunctionUse/RemovedFunctionsUnitTest.php
- PHPCompatibility/Tests/IniDirectives/RemovedIniDirectivesUnitTest.inc
- PHPCompatibility/Tests/IniDirectives/RemovedIniDirectivesUnitTest.php
* Fixes the version number of the extension removal.
* Adds the removed functions to the `RemovedFunctions` sniff.
* Adds the removed ini directives to the `RemovedIniDirectives` sniff.
---
Base on what can be found via the Wayback machine, the "Verisign Payflow Pro" Extension - `pfpro` - was moved to PECL with the release of PHP 5.1.0.
Ref: https://web.archive.org/web/20070226211109/http://www.php.net/manual/en/ref.pfpro.php
Refs: https://web.archive.org/web/20070226211109/http://www.php.net/manual/en/ref.pfpro.php
Refs: https://web.archive.org/web/20070226211109/http://www.php.net/manual/en/ref.pfpro.php
> Removed pfpro extension: add functions and inis

- PHPCompatibility/Sniffs/Syntax/NewArrayUnpackingSniff.php
- PHPCompatibility/Tests/Syntax/NewArrayUnpackingUnitTest.inc
- PHPCompatibility/Tests/Syntax/NewArrayUnpackingUnitTest.php
As of PHP 7.4, the spread operator can also be used to expand (unpack) arrays when declaring a new array.
Refs:
* https://wiki.php.net/rfc/spread_operator_for_array
* https://github.com/php/php-src/commit/e829d087299b59e638e91f18ea76f4dbe920c77b
**NOTE**: A critical look at the sniff category & sniff name are very welcome.
Ideas to improve these are welcome.
Related #808
> PHP 7.4: new NewArrayUnpacking sniff

- PHPCompatibility/Sniffs/FunctionDeclarations/ForbiddenToStringParametersSniff.php
- PHPCompatibility/Sniffs/MethodUse/ForbiddenToStringParametersSniff.php
- PHPCompatibility/Tests/MethodUse/ForbiddenToStringParametersUnitTest.inc
- PHPCompatibility/Tests/MethodUse/ForbiddenToStringParametersUnitTest.php
> The __toString() magic method can no longer accept arguments.
Ref: https://www.php.net/manual/en/migration53.incompatible.php
This introduces a sister-sniff called `PHPCompatibility.MethodUse.ForbiddenToStringParameters` to the `PHPCompatibility.FunctionDeclarations.ForbiddenToStringParameters` which will detect parameters being passed in direct calls to the magic `__toString()` method. (as per my previous remark in #815)
> Potential additional enhancement which could be added (now or later):
>
> * Check whether direct calls to `__toString()` methods pass arguments, i.e. `self::__toString($param)`, `$obj->__toString($param)`.
> PHP 5.3: new ForbiddenToStringParameters sniff (part 2)

- PHPCompatibility/Sniffs/FunctionUse/NewFunctionsSniff.php
- PHPCompatibility/Tests/FunctionUse/NewFunctionsUnitTest.inc
- PHPCompatibility/Tests/FunctionUse/NewFunctionsUnitTest.php
> - Standard
>    array password_algos() - return a complete list of all registered password
>    hashing algorithms. For more details see the RFC:
>    https://wiki.php.net/rfc/password_registry
Refs:
* https://github.com/php/php-src/blob/8f4e24eeef7bd1c39fabf5bea016abb287a4c606/UPGRADING#L380
* https://wiki.php.net/rfc/password_registry
* https://github.com/php/php-src/pull/3609
* https://github.com/php/php-src/commit/534df87c9e3c28001986e70844e0ad04e5708d3d
> PHP 7.4: NewFunctions: add password_algos()

- PHPCompatibility/Sniffs/Extensions/RemovedExtensionsSniff.php
- PHPCompatibility/Sniffs/FunctionUse/RemovedFunctionsSniff.php
- PHPCompatibility/Tests/Extensions/RemovedExtensionsUnitTest.inc
- PHPCompatibility/Tests/Extensions/RemovedExtensionsUnitTest.php
- PHPCompatibility/Tests/FunctionUse/RemovedFunctionsUnitTest.inc
- PHPCompatibility/Tests/FunctionUse/RemovedFunctionsUnitTest.php
Refs:
* https://wiki.php.net/rfc/deprecate-and-remove-ext-wddx
* php/php-src@6ac8b0a
* php/php-src@6bbb18a
> PHP 7.4: unbundle ext/wddx

- CHANGELOG.md
... to point to the repo in the PHPCompatibility organisation instead of to the old repo.
> Changelog: update all GH links

- PHPCompatibility/Sniffs/FunctionUse/RemovedFunctionsSniff.php
- PHPCompatibility/Tests/FunctionUse/RemovedFunctionsUnitTest.inc
- PHPCompatibility/Tests/FunctionUse/RemovedFunctionsUnitTest.php
> - LDAP:
>    ldap_control_paged_result_response and ldap_control_paged_result are
>    deprecated. Pagination controls can be sent along with ldap_search instead.
Refs:
* https://github.com/php/php-src/blob/42cc58ff7b2fee1c17a00dc77a4873552ffb577f/UPGRADING#L316
* https://github.com/php/php-src/commit/d93ce1795979e31255717fd770a2f0e901c06081
Loosely related to #808
> PHP 7.4: RemovedFunctions: account for deprecated LDAP functions

- PHPCompatibility/Sniffs/ParameterValues/RemovedImplodeFlexibleParamOrderSniff.php
- PHPCompatibility/Tests/ParameterValues/RemovedImplodeFlexibleParamOrderUnitTest.inc
- PHPCompatibility/Tests/ParameterValues/RemovedImplodeFlexibleParamOrderUnitTest.php
>  For historical reasons, the `implode()` function supports passing the `$glue` and `$pieces` parameters in reverse order from the documented order of arguments. This is inconsistent and makes the argument handling non-standard (for example, strict types are not respected). This also affects the alias `join()`.
>
> Proposal: Emit a deprecation warning when calling `implode($pieces, $glue)` or `join($pieces, $glue)`. Calling the function with just an array continues to be allowed: `implode($pieces)` does not generate a deprecation warning.
The tolerance for the reverse order is expected to be removed completely in PHP 8.0.
Refs:
* https://wiki.php.net/rfc/deprecations_php_7_4#implode_parameter_order_mix
* https://php.net/manual/en/function.implode.php
* …
> PHP 7.4: New ParameterValues/RemovedImplodeFlexibleParamOrder sniff

- PHPCompatibility/Sniffs/Extensions/RemovedExtensionsSniff.php
- PHPCompatibility/Sniffs/FunctionUse/RemovedFunctionsSniff.php
- PHPCompatibility/Tests/Extensions/RemovedExtensionsUnitTest.inc
- PHPCompatibility/Tests/Extensions/RemovedExtensionsUnitTest.php
- PHPCompatibility/Tests/FunctionUse/RemovedFunctionsUnitTest.inc
- PHPCompatibility/Tests/FunctionUse/RemovedFunctionsUnitTest.php
Refs:
* https://wiki.php.net/rfc/unbundle_recode
* https://www.php.net/manual/en/book.recode.php
* php/php-src@58b607c
> PHP 7.4: unbundle ext/recode

- PHPCompatibility/Sniffs/Classes/NewClassesSniff.php
- PHPCompatibility/Tests/Classes/NewClassesUnitTest.inc
- PHPCompatibility/Tests/Classes/NewClassesUnitTest.php
> Support for WeakReferences has been added.
Refs:
* https://wiki.php.net/rfc/weakrefs
* https://github.com/php/php-src/blob/fd6874c64d9e1d80b68b1035c1bb962ffd507798/UPGRADING#L221
* https://github.com/php/php-src/commit/6529d7acd9912a609924633a43e6562799566225
> PHP 7.4/NewClasses: add WeakReferences

- .travis.yml
The "quicktest" stage will only run a CS check, linting and the unit tests against low/high PHP/PHPCS combinations. This should catch most issues.
The more comprehensive complete build against a larger combination of PHP/PHPCS combination, including code coverage will now only be run on PRs and merges to `master`.
To see the difference, compare the output of the `push` and `pr` Travis runs for this PR.
This should solve the Coveralls issue as identified in https://github.com/PHPCompatibility/PHPCompatibility/pull/829#issuecomment-506067270
~~**Note: this PR can wait until after the release and has not been included in the changelog.**~~ (release has been done)
> Travis: add "quicktest" stage for non-PR/merge builds

- PHPCompatibility/Tests/Operators/RemovedTernaryAssociativityUnitTest.php
While examining something else, I noticed that the `testNoFalsePositives()` unit test for the `RemovedTernaryAssociativity` sniff was being marked as "Risky" by PHPUnit when run in combination with PHPCS 2.x.
Turns out that with how we are running the unit tests in PHPCompatibility for PHPCS 2.x, we don't have access to the token array from within the unit tests, which effectively means that the logic which created the data range to test in the `testNoFalsePositives()` test would yield an empty range of lines, resulting in no assertions being made.
While not as shiny as having the test case file line count calculated automatically, setting it via a property - which will need to be updated whenever the unit test case file is adjusted ! -, fixes this and will allow this unit test to run …
> RemovedTernaryAssociativity: fix false positive unit test for PHPCS 2.x

- PHPCompatibility/Tests/ParameterValues/RemovedMbstringModifiersUnitTest.inc
The sniff already handles this correctly, but it was not explicitly tested and if the call to `strtolower()` would be removed, the unit tests would still pass, while they shouldn't.
> RemovedMbstringModifiers: add unit test for non-lowercase function calls

- PHPCompatibility/Tests/ParameterValues/NewNegativeStringOffsetUnitTest.inc
- PHPCompatibility/Tests/ParameterValues/NewNegativeStringOffsetUnitTest.php
The sniff already handles this correctly, but it was not explicitly tested and if the call to `strtolower()` would be removed, the unit tests would still pass, while they shouldn't.
> NewNegativeStringOffset: add unit test for non-lowercase function calls

- PHPCompatibility/Sniffs/FunctionUse/NewFunctionsSniff.php
- PHPCompatibility/Tests/FunctionUse/NewFunctionsUnitTest.inc
- PHPCompatibility/Tests/FunctionUse/NewFunctionsUnitTest.php
>  GD:
>  Added `imagecreatefromtga()` function, which allows reading images in TGA
>  format. TGA support is now also indicated by `gd_info()` and `imagetypes()`.
>  Note that TGA images are not recognized by `imagecreatefromstring()` and `getimagesize()`.
Refs:
* https://github.com/php/php-src/blob/3775d47eee38f3b34f800a0b23f840ec7a94e4c7/UPGRADING#L461-L465
* https://github.com/php/php-src/commit/81fd113506e4c5833e64998651f232734ebb2cb7
> PHP 7.4/NewFunctions: handle new imagecreatefromtga()

- PHPCompatibility/Sniffs/ParameterValues/NewHashAlgorithmsSniff.php
- PHPCompatibility/Tests/ParameterValues/NewHashAlgorithmsUnitTest.inc
- PHPCompatibility/Tests/ParameterValues/NewHashAlgorithmsUnitTest.php
> - Hash:
>    Added "crc32c" hash using Castagnoli's polynomial. This crc32 variant is
>    used by storage systems, such as iSCSI, SCTP, Btrfs and ext4.
Refs:
* https://github.com/php/php-src/blob/3775d47eee38f3b34f800a0b23f840ec7a94e4c7/UPGRADING#L258-L260
* https://github.com/php/php-src/commit/c79ce48ddb2125a3d19723e0fbca1bd770bacab7
> PHP 7.4/NewHashAlgorithms: add new `crc32c` hash algo

- PHPCompatibility/Sniffs/IniDirectives/NewIniDirectivesSniff.php
- PHPCompatibility/Tests/IniDirectives/NewIniDirectivesUnitTest.inc
- PHPCompatibility/Tests/IniDirectives/NewIniDirectivesUnitTest.php
> - zend.exception_ignore_args
>    . New INI directive which displays or hides arguments from the stack traces
generated for exceptions.
Refs:
* https://github.com/php/php-src/blob/30de357fa14480468132bbc22a272aeb91789ba8/UPGRADING#L597-L599
* https://github.com/php/php-src/commit/0819e6dc9b4788e5d44b64f8e606a56c969a1588#diff-7748eb3bfdd3bf962553f6f9f2723c45
> PHP 7.4/NewIniDirectives: detect new  zend.exception_ignore_args directive

- PHPCompatibility/Sniffs/IniDirectives/RemovedIniDirectivesSniff.php
- PHPCompatibility/Tests/IniDirectives/RemovedIniDirectivesUnitTest.inc
- PHPCompatibility/Tests/IniDirectives/RemovedIniDirectivesUnitTest.php
> The `allow_url_include` ini directive is deprecated. Enabling it will generate a deprecation notice at startup.
Refs:
* https://wiki.php.net/rfc/deprecations_php_7_4#allow_url_include
* https://github.com/php/php-src/blob/86d751f696786bcb95c580482c9884e41ccf2406/UPGRADING#L372-L373
* https://github.com/php/php-src/commit/b3f74b0b7d89ee8efe6897b9ed6397d8b80a15e0
> PHP 7.4/RemovedIniDirectives: handle deprecated allow_url_include

- PHPCompatibility/Sniffs/FunctionDeclarations/NonStaticMagicMethodsSniff.php
- PHPCompatibility/Sniffs/FunctionNameRestrictions/NewMagicMethodsSniff.php
- PHPCompatibility/Tests/FunctionDeclarations/NonStaticMagicMethodsUnitTest.1.inc
- PHPCompatibility/Tests/FunctionDeclarations/NonStaticMagicMethodsUnitTest.2.inc
- PHPCompatibility/Tests/FunctionDeclarations/NonStaticMagicMethodsUnitTest.php
- PHPCompatibility/Tests/FunctionNameRestrictions/NewMagicMethodsUnitTest.1.inc
- PHPCompatibility/Tests/FunctionNameRestrictions/NewMagicMethodsUnitTest.2.inc
- PHPCompatibility/Tests/FunctionNameRestrictions/NewMagicMethodsUnitTest.php
> A new mechanism for custom object serialization has been added, which uses two new magic methods:
>
>     ```php
>     // Returns array containing all the necessary state of the object.
>     public function __serialize(): array;
>
>     // Restores the object state from the given data array.
>     public function __unserialize(array $data): void;
>     ```
>
> The new serialization mechanism supersedes the Serializable interface, which will be deprecated in the future.
Refs:
* https://wiki.php.net/rfc/custom_object_serialization
* https://github.com/php/php-src/blob/3775d47eee38f3b34f800a0b23f840ec7a94e4c7/UPGRADING#L305-L315
* php/php-src#3761
* php/php-src@d373c11
From the RFC:
> **Creating objects in __unserialize()**
>
> Some people have expressed a desire to …
> PHP 7.4: Custom object serialization RFC

- PHPCompatibility/Sniff.php
- PHPCompatibility/Sniffs/Classes/NewClassesSniff.php
- PHPCompatibility/Sniffs/Interfaces/NewInterfacesSniff.php
Use a consistent return type and proper return value checking where the function is used.
> Sniff::getReturnTypeHintName(): defensive coding

- PHPCompatibility/Sniffs/FunctionDeclarations/ForbiddenParametersWithSameNameSniff.php
- PHPCompatibility/Tests/FunctionDeclarations/ForbiddenParametersWithSameNameUnitTest.inc
- PHPCompatibility/Tests/FunctionDeclarations/ForbiddenParametersWithSameNameUnitTest.php
While it most definitely should be considered bad practice to use the same name in a different case for two different parameters for the same function, it is not problematic from a PHP/PHPCompatibility point of view.
Variables in PHP are _case-sensitive_, so should be treated as such for the purposes of this sniff.
See: https://3v4l.org/9QXAL
Looks like this bug has been in the sniff from the very beginning - #110 -, so in a way quite surprising that we've not had any bug reports about it.
Includes unit test.
> ForbiddenParametersWithSameName: bug fix - variables names are case-sensitive

- PHPCompatibility/Sniffs/FunctionUse/RemovedFunctionsSniff.php
- PHPCompatibility/Tests/FunctionUse/RemovedFunctionsUnitTest.inc
- PHPCompatibility/Tests/FunctionUse/RemovedFunctionsUnitTest.php
As of PHP 7.4, the `is_real()` function is deprecated. Use `is_float()` instead.
This function is expected to be removed in PHP 8.0.
Refs:
* https://wiki.php.net/rfc/deprecations_php_7_4#the_real_type
* php/php-src#4390
* php/php-src@4e19069
>  PHP's infamous `magic_quotes` configuration was removed in PHP 5.4 and the function implementations of checking whether or not these settings have been enabled have returned `false` since then. With PHP 7.0 not having `magic_quotes` at all, it is time to deprecate these functions and remove them entirely.
>
> Proposal: Mark `get_magic_quotes_gpc()` and `get_magic_quotes_runtime()` as deprecated. This should only impact legacy code bases prior to PHP 5.4, running non-supported versions of PHP.
These functions are expected to be …
> PHP 7.4/RemovedFunctions: handle removed functions from the Deprecations RFC

- PHPCompatibility/Sniffs/TypeCasts/RemovedTypeCastsSniff.php
- PHPCompatibility/Tests/TypeCasts/RemovedTypeCastsUnitTest.inc
- PHPCompatibility/Tests/TypeCasts/RemovedTypeCastsUnitTest.php
As of PHP 7.4, using the `(real)` type-cast will emit a deprecation notice.
This type-cast is expected to be removed in PHP 8.0.
Refs:
* https://wiki.php.net/rfc/deprecations_php_7_4#the_real_type
* https://github.com/php/php-src/pull/4390
* https://github.com/php/php-src/commit/e41b7f6db42472158fd44bb502ee1b8e51dca610
> PHP 7.4/RemovedTypeCasts: handle deprecated (real) typecast

- PHPCompatibility/Sniffs/FunctionUse/NewFunctionsSniff.php
- PHPCompatibility/Sniffs/ParameterValues/NewPCREModifiersSniff.php
Both the `NewFunctions` sniff as well as the `NewPCREModifiers` sniff had an array which contained a duplicate entry.
Fixed now.
> Remove duplicate array entries

- PHPCompatibility/Sniffs/Syntax/NewArrayStringDereferencingSniff.php
- PHPCompatibility/Tests/Syntax/NewArrayStringDereferencingUnitTest.inc
- PHPCompatibility/Tests/Syntax/NewArrayStringDereferencingUnitTest.php
What with PHP 7.4 deprecating the array dereferencing syntax with curly braces, I've been doing some research on where this was supported up to now.
Turns out that, as of PHP 7.0, dereferencing array/string literals using curly braces has been supported.
See: https://3v4l.org/SlXd2
While the PHP 7.0 changelog makes no note of this, the change was probably part of the PHP 7.0 [Uniform Variable Syntax](https://wiki.php.net/rfc/uniform_variable_syntax) changes.
This PR adjusts the `PHPCompatibility.Syntax.NewArrayStringDereferencing` sniff to:
* Also recognize curly braces.;
* Throw an error for each access detected, i.e. `[1, [20, 21, 22], 3][1][1]` would previously throw just the one error, now it will throw two.
The actual logic has been split off to a separate …
> NewArrayStringDereferencing: recognize dereferencing using curly braces

- PHPCompatibility/Sniffs/Syntax/NewClassMemberAccessSniff.php
- PHPCompatibility/Tests/Syntax/NewClassMemberAccessUnitTest.inc
- PHPCompatibility/Tests/Syntax/NewClassMemberAccessUnitTest.php
What with PHP 7.4 deprecating the array dereferencing syntax with curly braces, I've been doing some research on where this was supported up to now.
Turns out that, as of PHP 7.0, dereferencing class member access on instantiation using curly braces has been supported.
See: https://3v4l.org/KsEgH
While the PHP 7.0 changelog makes no note of this, the change was probably part of the PHP 7.0 [Uniform Variable Syntax](https://wiki.php.net/rfc/uniform_variable_syntax) changes.
This PR adjusts the `PHPCompatibility.Syntax.NewClassMemberAcces` sniff to:
* Also recognize curly braces.;
* Throw an error for each access detected, i.e. `(new Foo( array(1, array(4, 5), 3) ))[1][0]` would previously throw just the one error, now it will throw two.
* Throw the error on the token used for the access, …
> NewClassMemberAccess: recognize member access using curly braces

- PHPCompatibility/Sniffs/Syntax/NewFunctionArrayDereferencingSniff.php
- PHPCompatibility/Tests/Syntax/NewFunctionArrayDereferencingUnitTest.inc
- PHPCompatibility/Tests/Syntax/NewFunctionArrayDereferencingUnitTest.php
What with PHP 7.4 deprecating the array dereferencing syntax with curly braces, I've been doing some research on where this was supported up to now.
Turns out that, as of PHP 7.0, function array dereferencing using curly braces has been supported.
See: https://3v4l.org/a1TW6
While the PHP 7.0 changelog makes no note of this, the change was probably part of the PHP 7.0 [Uniform Variable Syntax](https://wiki.php.net/rfc/uniform_variable_syntax) changes.
This PR adjusts the `PHPCompatibility.Syntax.NewFunctionArrayDereferencing` sniff to:
* Also recognize curly braces.;
* Throw an error for each access detected, i.e. `$foo->bar()[1][0]` would previously throw just the one error, now it will throw two.
* Throw the error on the token used for the access, not on the closing parenthesis of the …
> NewFunctionArrayDereferencing: recognize function array dereferencing using curly braces

- PHPCompatibility/Sniffs/FunctionNameRestrictions/NewMagicMethodsSniff.php
- PHPCompatibility/Tests/FunctionNameRestrictions/NewMagicMethodsUnitTest.1.inc
- PHPCompatibility/Tests/FunctionNameRestrictions/NewMagicMethodsUnitTest.2.inc
- PHPCompatibility/Tests/FunctionNameRestrictions/NewMagicMethodsUnitTest.php
Both introduced in PHP 5.0 when the OO model came into play.
> NewMagicMethods: recognize __construct() and __destruct()

- PHPCompatibility/Sniffs/FunctionUse/RemovedFunctionParametersSniff.php
- PHPCompatibility/Tests/FunctionUse/RemovedFunctionParametersUnitTest.inc
- PHPCompatibility/Tests/FunctionUse/RemovedFunctionParametersUnitTest.php
> The $version parameter of curl_version() is deprecated. If any value not
> equal to the default CURLVERSION_NOW is passed, a warning is raised and the
> parameter is ignored.
Notes:
* While the changelog and the PHP native deprecation message call the parameter `$version`, the documentation calls it `$age`, so that's the parameter name used for the error message.
* Using the `CURL_VERSION_NOW` constant for the value is still fine, so the sniff takes that into account.
Refs:
* https://github.com/php/php-src/blob/86d751f696786bcb95c580482c9884e41ccf2406/UPGRADING#L55-L57
* https://www.php.net/manual/en/function.curl-version.php
* https://github.com/php/php-src/commit/357da6bc59268755323bc924b0aae93374c7e227
> PHP 7.4/RemovedFunctionParameters: handle deprecated curl_version() $age

- PHPCompatibility/Sniffs/FunctionDeclarations/NewExceptionsFromToStringSniff.php
- PHPCompatibility/Tests/FunctionDeclarations/NewExceptionsFromToStringUnitTest.inc
- PHPCompatibility/Tests/FunctionDeclarations/NewExceptionsFromToStringUnitTest.php
The `$ooScopeTokens` property is not intended to be set via a custom ruleset, so the property should never have been `public`.
When an exception is thrown within a `try/catch` block, ignore it.
This changes the sniff, in that previously only one error per method would be thrown. Now, an error will be thrown for each `throw` tag not in a `try/catch`.
This adds an additional check based on the docblock to attempt to catch exceptions thrown indirectly from this method.
If the docblock indicates that the function may throw an exception, trust it.
The additional check will only be run if the search for the `throw` keyword didn't yield any errors.
---
Fixes #863
> NewExceptionsFromToString: 2 bugfixes + 1 enhancement

- PHPCompatibility/Sniff.php
- PHPCompatibility/Sniffs/TextStrings/NewUnicodeEscapeSequenceSniff.php
- PHPCompatibility/Tests/TextStrings/NewUnicodeEscapeSequenceUnitTest.inc
- PHPCompatibility/Tests/TextStrings/NewUnicodeEscapeSequenceUnitTest.php
> ### Unicode codepoint escape syntax
>
> This takes a Unicode codepoint in hexadecimal form, and outputs that codepoint in UTF-8 to a double-quoted string or a heredoc. Any valid codepoint is accepted, with leading 0's being optional.
> ```php
> echo "\u{aa}";
> echo "\u{0000aa}";
> echo "\u{9999}";
> ```
> ### `\u{` may cause errors ¶
>
> Due to the addition of the new Unicode codepoint escape syntax, strings containing a literal `\u{` followed by an invalid sequence will cause a fatal error. To avoid this, the leading backslash should be escaped.
Refs:
* https://wiki.php.net/rfc/unicode_escape
* https://www.php.net/manual/en/migration70.new-features.php#migration70.new-features.unicode-codepoint-escape-syntax
* https://www.php.net/manual/en/migration70.incompatible.php#migration70.incom …
> PHP 7.0: new NewUnicodeEscapeSequence sniff

- PHPCompatibility/Sniffs/ParameterValues/NewProcOpenCmdArraySniff.php
- PHPCompatibility/Tests/ParameterValues/NewProcOpenCmdArrayUnitTest.inc
- PHPCompatibility/Tests/ParameterValues/NewProcOpenCmdArrayUnitTest.php
> proc_open() now accepts an array instead of a string for the command. In
>  this case the process will be opened directly (without going through a
>  shell) and PHP will take care of any necessary argument escaping.
>
>  `proc_open(['php', '-r', 'echo "Hello World\n";'], $descriptors, $pipes);`
Refs:
* https://github.com/php/php-src/blob/3775d47eee38f3b34f800a0b23f840ec7a94e4c7/UPGRADING#L323-L327
* https://github.com/php/php-src/commit/8be051015e04ce6151da77581922eea65330f354
> PHP 7.4: new NewProcOpenCmdArray sniff

- PHPCompatibility/Sniffs/ParameterValues/RemovedMbStrrposEncodingThirdParamSniff.php
- PHPCompatibility/Tests/ParameterValues/RemovedMbStrrposEncodingThirdParamUnitTest.inc
- PHPCompatibility/Tests/ParameterValues/RemovedMbStrrposEncodingThirdParamUnitTest.php
> The encoding parameter was moved from the third position to the fourth in PHP 5.2.0.
> For backward compatibility, encoding could be specified as the third parameter, but doing
> so is deprecated and will be removed in the future.
Between PHP 5.2 and PHP 7.3, this was a deprecation in documentation only.
As of PHP 7.4, a deprecation warning will be thrown if an encoding is passed as the 3rd argument.
As of PHP 8, the argument is expected to change to accept an integer only.
Refs:
* https://wiki.php.net/rfc/deprecations_php_7_4#mb_strrpos_with_encoding_as_3rd_argument
* https://github.com/php/php-src/commit/39e756e7fe7b08092b4a75cf253442cba826e910
> PHP 5.2/7.4: new RemovedMbStrrposEncodingThirdParam sniff

- PHPCompatibility/Sniffs/ParameterValues/NewIDNVariantDefaultSniff.php
- PHPCompatibility/Tests/ParameterValues/NewIDNVariantDefaultUnitTest.inc
- PHPCompatibility/Tests/ParameterValues/NewIDNVariantDefaultUnitTest.php
> Intl:
> The default parameter value of idn_to_ascii() and idn_to_utf8() is now
> INTL_IDNA_VARIANT_UTS46 instead of the deprecated INTL_IDNA_VARIANT_2003.
**Note**:  The new sniff will only throw an error when the `testVersion` indicates that both PHP < 7.4 as well as PHP 7.4+ need to be supported.
There is a risk in that, i.e. when people use PHPCompatibility against their code using only their current server version, `7.2`, and when upgrading the server version, only the new version, `7.4`, they will not be shown this message in either run.
The other side of that coin is that it prevents unnecessary errors/warnings for code which only needs to support one PHP version and is therefore not directly affected by this change.
This should possibly be addressed in the `Readme` by advising …
> PHP 7.4: new NewIDNVariantDefault sniff

- PHPCompatibility/Sniffs/ParameterValues/NewHTMLEntitiesEncodingDefaultSniff.php
- PHPCompatibility/Tests/ParameterValues/NewHTMLEntitiesEncodingDefaultUnitTest.inc
- PHPCompatibility/Tests/ParameterValues/NewHTMLEntitiesEncodingDefaultUnitTest.php
> The default character set for htmlspecialchars() and htmlentities() is now UTF-8, instead of ISO-8859-1.
**Note**:  The new sniff will only throw an error when the `testVersion` indicates that both PHP < 5.4 as well as PHP 5.4+ need to be supported.
Refs:
* https://www.php.net/manual/en/migration54.other.php
* https://www.php.net/manual/en/function.htmlentities.php#refsect1-function.htmlentities-changelog
* https://www.php.net/manual/en/function.htmlspecialchars.php#refsect1-function.htmlspecialchars-changelog
Related to #839
> PHP 5.4: new NewHTMLEntitiesEncodingDefault sniff

- PHPCompatibility/Sniffs/ParameterValues/NewPasswordAlgoConstantValuesSniff.php
- PHPCompatibility/Tests/ParameterValues/NewPasswordAlgoConstantValuesUnitTest.inc
- PHPCompatibility/Tests/ParameterValues/NewPasswordAlgoConstantValuesUnitTest.php
> Password hashing algorithm identifiers are now nullable strings rather
>  than integers.
>
>  * PASSWORD_DEFAULT was int 1; now is null
>  * PASSWORD_BCRYPT was int 1; now is string '2y'
>  * PASSWORD_ARGON2I was int 2; now is string 'argon2i'
>  * PASSWORD_ARGON2ID was int 3; now is string 'argon2id'
>
>  Applications correctly using the constants PASSWORD_DEFAULT,
>  PASSWORD_BCRYPT, PASSWORD_ARGON2I, and PASSWORD_ARGON2ID will continue to
function correctly.
Refs:
* https://wiki.php.net/rfc/password_registry
* https://github.com/php/php-src/blob/86d751f696786bcb95c580482c9884e41ccf2406/UPGRADING#L131-L141
* https://github.com/php/php-src/commit/534df87c9e3c28001986e70844e0ad04e5708d3d
**Note**: while deprecated in name, it looks like the deprecation warning for …
> PHP 7.4: new NewPasswordAlgoConstantValues sniff

- PHPCompatibility/Sniffs/ParameterValues/NewIconvMbstringCharsetDefaultSniff.php
- PHPCompatibility/Tests/ParameterValues/NewIconvMbstringCharsetDefaultUnitTest.inc
- PHPCompatibility/Tests/ParameterValues/NewIconvMbstringCharsetDefaultUnitTest.php
> all functions that take encoding option use php.internal_encoding as default (e.g. htmlentities/mb_strlen/mb_regex/etc)
**Note**:  The new sniff will only throw an error when the `testVersion` indicates that both PHP < 5.6 as well as PHP 5.6+ need to be supported.
Refs:
* https://wiki.php.net/rfc/default_encoding
* https://www.php.net/manual/en/migration56.new-features.php#migration56.new-features.default-encoding
* https://www.php.net/manual/en/migration56.deprecated.php#migration56.deprecated.iconv-mbstring-encoding
Fixes #839
This PR does not address the `mb_erg..()` functions. For those to work correctly cross-version the encoding needs to be set using the [`mb_regex_encoding()`](https://www.php.net/manual/en/function.mb-regex-encoding.php) function.
As PHPCS …
> PHP 5.6: new NewIconvMbstringCharsetDefault sniff

- PHPCompatibility/Sniffs/ParameterValues/ForbiddenStripTagsSelfClosingXHTMLSniff.php
- PHPCompatibility/Tests/ParameterValues/ForbiddenStripTagsSelfClosingXHTMLUnitTest.inc
- PHPCompatibility/Tests/ParameterValues/ForbiddenStripTagsSelfClosingXHTMLUnitTest.php
> In PHP 5.3.4 and later, self-closing XHTML tags are ignored and only non-self-closing tags should be used in allowable_tags. For example, to allow both `<br>` and `<br/>`, you should use:
> ```php
> <?php
> strip_tags($input, '<br>');
> ?>
> ```
Ref:
* https://www.php.net/manual/en/function.strip-tags.php#refsect1-function.strip-tags-changelog
> PHP 5.3.4: new ForbiddenStripTagsSelfClosingXHTML sniff

- PHPCompatibility/Sniffs/ParameterValues/NewStripTagsAllowableTagsArraySniff.php
- PHPCompatibility/Tests/ParameterValues/NewStripTagsAllowableTagsArrayUnitTest.inc
- PHPCompatibility/Tests/ParameterValues/NewStripTagsAllowableTagsArrayUnitTest.php
> `strip_tags()` now also accepts an array of allowed tags: Instead of
`strip_tags($str, '<a><p>')` you can now write `strip_tags($str, ['a', 'p'])`.
Refs:
* https://github.com/php/php-src/blob/3775d47eee38f3b34f800a0b23f840ec7a94e4c7/UPGRADING#L301-L303
* https://github.com/php/php-src/commit/b1e9c73b2777b802925bcdcec6d7012b6d98f1cb
> PHP 7.4: new NewStripTagsAllowableTagsArray sniff

- PHPCompatibility/Sniffs/Syntax/RemovedCurlyBraceArrayAccessSniff.php
- PHPCompatibility/Tests/Syntax/RemovedCurlyBraceArrayAccessUnitTest.inc
- PHPCompatibility/Tests/Syntax/RemovedCurlyBraceArrayAccessUnitTest.inc.fixed
- PHPCompatibility/Tests/Syntax/RemovedCurlyBraceArrayAccessUnitTest.php
> The array and string offset access syntax using curly braces is deprecated.
> Use $str[$idx] instead of $str{$idx}.
Refs:
* https://wiki.php.net/rfc/deprecate_curly_braces_array_access
* https://github.com/php/php-src/blob/ef165b4422f4cef60f963833dddffa26fe1b2759/UPGRADING#L351-L353
* https://github.com/php/php-src/pull/4416
* https://github.com/php/php-src/commit/d574df63dc375f5fc9202ce5afde23f866b6450a
Based on a lot of testing, I have come to the conclusion that the curly braces for array access worked in quite a lot of cases, though mostly since PHP 7.0.
The other sniffs which should take curly brace access into account - `NewArrayStringDereferencing`, `NewClassMemberAccess` and `NewFunctionArrayDereferencing` - have been adjusted in separate PRs. See: #851, #852, #853
This PR can …
> PHP 7.4: New RemovedCurlyBraceArrayAccess sniff

- PHPCompatibility/Sniffs/FunctionDeclarations/NewExceptionsFromToStringSniff.php
- PHPCompatibility/Sniffs/Syntax/NewArrayStringDereferencingSniff.php
- PHPCompatibility/Sniffs/Syntax/NewClassMemberAccessSniff.php
- PHPCompatibility/Sniffs/Syntax/NewFunctionArrayDereferencingSniff.php
- PHPCompatibility/Sniffs/Syntax/RemovedCurlyBraceArrayAccessSniff.php
... to comply with the guidelines in the proposed PSR-19: https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc-tags.md#55-internal
> Documentation: fix up some @internal tags

- PHPCompatibility/Sniff.php
- PHPCompatibility/Tests/BaseSniffTest.php
- PHPCompatibility/Tests/ControlStructures/ForbiddenBreakContinueVariableArgumentsUnitTest.php
- PHPCompatibility/Tests/FunctionDeclarations/ForbiddenVariableNamesInClosureUseUnitTest.php
- PHPCompatibility/Tests/FunctionNameRestrictions/RemovedMagicAutoloadUnitTest.php
- PHPCompatibility/Tests/FunctionNameRestrictions/RemovedNamespacedAssertUnitTest.php
- PHPCompatibility/Tests/Miscellaneous/NewPHPOpenTagEOFUnitTest.php
- PHPCompatibility/Tests/Syntax/NewFlexibleHeredocNowdocUnitTest.php
Note: only the docblocks for user-facing code and abstract classes contain `@since` tags.
> Documentation: add docblocks to class constants

- PHPCompatibility/Sniffs/ParameterValues/RemovedImplodeFlexibleParamOrderSniff.php
- PHPCompatibility/Tests/ParameterValues/RemovedImplodeFlexibleParamOrderUnitTest.inc
- PHPCompatibility/Tests/ParameterValues/RemovedImplodeFlexibleParamOrderUnitTest.php
Bugs:
1. "Empty" tokens (whitespace, comments) were not disregarded when determining whether the first parameter was only a text string, which could lead to the second parameter being examined when it doesn't need to be.
2. If either parameter contained a ternary, potentially nested in some other construct, the ternary would confuse the sniff.
Both fixed now.
In addition to this if one of the parameters contains an `(array)` cast, let's presume that's the array parameter. This may lead to some false positives for complexly build parameters, but we'll deal with that later if needs be.
Fixes #890
> RemovedImplodeFlexibleParamOrder: fix two bugs + one enhancement

- .travis.yml
As `develop` is now the default branch, the conditions based on which the various build stages are being triggered need to be updated, otherwise, builds will only run the `sniff` stage for pull requests against `develop`.
> Travis: update stage conditions

- .github/CONTRIBUTING.md
- README.md
- Updated contribution documentation to reflect change from master to develop
- Removed WPEngine logo (wasn't working anymore). Kept link.
> Updated contribution documentation + Removed WPEngine logo

- README.md
As the Readme is getting quite long, adding a table of contents seems appropriate.
Includes adding a mini-section about contributing to the project and fixing a minor grammar error.
> Readme: add table of contents

- PHPCompatibility/Sniffs/FunctionNameRestrictions/RemovedPHP4StyleConstructorsSniff.php
- PHPCompatibility/Tests/FunctionNameRestrictions/RemovedPHP4StyleConstructorsUnitTest.inc
Make the sniff a little faster by skipping over complete docblocks instead of walking them via `findNext()`.
> RemovedPHP4StyleConstructors: efficiency fix

- PHPCompatibility/Sniffs/MethodUse/NewDirectCallsToCloneSniff.php
- PHPCompatibility/Tests/MethodUse/NewDirectCallsToCloneUnitTest.inc
- PHPCompatibility/Tests/MethodUse/NewDirectCallsToCloneUnitTest.php
Direct calls to `__clone()` from within a class using `self`, `static` or `parent` were always allowed.
Ref: https://3v4l.org/BmmPT
Fixes https://github.com/PHPCompatibility/PHPCompatibility/issues/629#issuecomment-532607809
> NewDirectCallsToClone: bug fix - exclude class internal calls

- PHPCompatibility/Sniffs/FunctionDeclarations/ForbiddenToStringParametersSniff.php
The `$ooScopeTokens` property is not intended to be set via a custom ruleset, so the property should never have been `public`.
> ForbiddenToStringParameters: property should not be public

- PHPCompatibility/Sniffs/Miscellaneous/ValidIntegersSniff.php
- PHPCompatibility/Tests/Miscellaneous/ValidIntegersUnitTest.inc
- PHPCompatibility/Tests/Miscellaneous/ValidIntegersUnitTest.php
* Hex numbers were already handled correctly, but there was no unit test safe-guarding the case-insensitive matching.
* Binary numbers using an uppercase `B` were _not_ handled correctly so far.
This has been fixed, including adding a unit test to safe guard this.
> ValidIntegers: bug fix - binary and hex numbers are case-insensitive

- PHPCompatibility/Sniffs/FunctionUse/RequiredToOptionalFunctionParametersSniff.php
- PHPCompatibility/Tests/FunctionUse/OptionalToRequiredFunctionParametersUnitTest.inc
Prevent recognizing class instantiation as if it were a function call.
Includes unit test.
Fixes #913
> RequiredToOptionalFunctionParameters: bug fix for class instantiation

- PHPCompatibility/Sniffs/FunctionNameRestrictions/ReservedFunctionNamesSniff.php
- PHPCompatibility/Tests/FunctionNameRestrictions/ReservedFunctionNamesUnitTest.inc
- PHPCompatibility/Tests/FunctionNameRestrictions/ReservedFunctionNamesUnitTest.php
- phpcs.xml.dist
Check the function docblock for a `@deprecated` tag and if found, bow out.
Fixes #911
> ReservedFunctionNames: ignore deprecated functions

- PHPCompatibility/Sniffs/FunctionNameRestrictions/RemovedPHP4StyleConstructorsSniff.php
- PHPCompatibility/Tests/FunctionNameRestrictions/RemovedPHP4StyleConstructorsUnitTest.php
Introduced in #751 / PHPCompatibility 9.1.0.
While interfaces can declare methods with the same name as the interface, as the class in which the method will be implemented will be called differently, those methods will never be seen as constructors, so shouldn't trigger this error.
Mea culpa.
Related: squizlabs/PHP_CodeSniffer#2663
Also see: https://3v4l.org/qbXJS
> RemovedPHP4StyleConstructors: should not apply to interfaces

- CHANGELOG.md
Includes adding some missing "Fixes" to the 9.3.2 changelog. (already fixed up in the tag description on GH)
> Changelog for PHPCompatibility 9.3.3

- PHPCompatibility/Sniffs/Keywords/ForbiddenNamesSniff.php
- PHPCompatibility/Tests/Keywords/ForbiddenNamesUnitTest.inc
The changes in PR #923 did not take `foreach ( ...as list() ) {}` into account.
Fixed now. Includes unit test.
Fixes #928
Closes #929
> ForbiddenNames: allow for `foreach( ... as list() ) {}`

- CHANGELOG.md
Includes adding missing milestone links for the 9.3.3 release.
> Changelog for PHPCompatibility 9.3.4

- PHPCompatibility/Sniffs/Syntax/NewShortArraySniff.php
- PHPCompatibility/Tests/Syntax/NewShortArrayUnitTest.php
Most error messages in PHPCompatibility follow one of the below formats:
* "Feature x is not supported in PHP x.x and below" (new features)
* "Feature x was deprecated in PHP x.x and removed in PHP x.x" (removed features)
The error message for short array syntax did not follow that typical pattern and was confusing to some - I've recently had questions about it from a few different people -, so I'm proposing to adjust the error message to be more in line with other messages in the PHPCompatibility library.
> NewShortArray: improve error message

- .travis.yml
- README.md
As [PHP 7.4 has been released](https://www.php.net/archive/2019.php#2019-11-28-1), the build against PHP 7.4 should no longer be allowed to fail.
Includes some tweaking of the matrix to have the coverage stage and the quick test stage include PHP 7.4.
> Travis: don't allow PHP 7.4 build to fail

- PHPCompatibility/Sniffs/Interfaces/NewInterfacesSniff.php
- PHPCompatibility/Tests/Interfaces/NewInterfacesUnitTest.php
The base URL for the php.net manual site has changed.
> NewInterfaces: update reference URLs

- PHPCompatibility/Sniffs/Classes/NewClassesSniff.php
- PHPCompatibility/Tests/Classes/NewClassesUnitTest.php
The two new PHP 7.4 classes had inadvertently been added to the `$newExceptions` array, while they should have been added to the `$newClasses` aray.
> NewClasses: minor bug fix - move two classes

- PHPCSAliases.php
- PHPCompatibility/PHPCSHelper.php
- PHPCompatibility/Sniffs/Classes/NewClassesSniff.php
- PHPCompatibility/Sniffs/Extensions/RemovedExtensionsSniff.php
- PHPCompatibility/Sniffs/FunctionDeclarations/ForbiddenParameterShadowSuperGlobalsSniff.php
- PHPCompatibility/Sniffs/FunctionDeclarations/NewExceptionsFromToStringSniff.php
- PHPCompatibility/Sniffs/FunctionDeclarations/NewNullableTypesSniff.php
- PHPCompatibility/Sniffs/FunctionNameRestrictions/ReservedFunctionNamesSniff.php
- PHPCompatibility/Sniffs/FunctionUse/ArgumentFunctionsReportCurrentValueSniff.php
- PHPCompatibility/Sniffs/Miscellaneous/NewPHPOpenTagEOFSniff.php
- PHPCompatibility/Sniffs/Miscellaneous/RemovedAlternativePHPTagsSniff.php
- PHPCompatibility/Sniffs/Operators/ForbiddenNegativeBitshiftSniff.php
- PHPCompatibility/Sniffs/Operators/NewOperatorsSniff.php
- PHPCompatibility/Sniffs/ParameterValues/RemovedIconvEncodingSniff.php
- PHPCompatibility/Sniffs/ParameterValues/RemovedPCREModifiersSniff.php
- PHPCompatibility/Sniffs/Syntax/NewArrayStringDereferencingSniff.php
- PHPCompatibility/Sniffs/Syntax/NewClassMemberAccessSniff.php
- PHPCompatibility/Sniffs/Syntax/NewFunctionArrayDereferencingSniff.php
- PHPCompatibility/Sniffs/Syntax/RemovedCurlyBraceArrayAccessSniff.php
- PHPCompatibility/Sniffs/Upgrade/LowPHPCSSniff.php
- PHPCompatibility/Sniffs/Upgrade/LowPHPSniff.php
- PHPCompatibility/Sniffs/Variables/ForbiddenThisUseContextsSniff.php
- PHPCompatibility/Tests/FunctionDeclarations/NonStaticMagicMethodsUnitTest.php
- PHPCompatibility/Tests/FunctionNameRestrictions/NewMagicMethodsUnitTest.php
- PHPCompatibility/Tests/Syntax/NewFlexibleHeredocNowdocUnitTest.php
- PHPCompatibility/Util/Tests/Core/IsNumberUnitTest.php
For the use of `@internal` tags with comments for dev internal information, it used to be recommended to use `{@internal ... }}` (not the double curlies at the end) format to help IDEs parse these correctly.
This format has since been superseded as the parsing of docblocks in IDEs has improved a lot since then.
The current recommendation is to just use a single curly at the end.
Ref: https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc-tags.md#55-internal
> Documentation: improve use of `@internal` tags
